Ally'sPetStoreAPI: Ally\PetStore\Schema\User Class Reference
Ally\PetStore\Schema\User Class Reference
Public Member Functions
isNullableSetToNull (string $property)
Checks if a nullable property is set to null.
getModelName ()
The original name of the model.
__construct (array $data=null)
Constructor.
listInvalidProperties ()
Show all the invalid properties with reasons.
valid ()
Validate all the properties in the model return true if all passed.
getId ()
Gets id.
setId ($id)
Sets id.
getUsername ()
Gets username.
setUsername ($username)
Sets username.
getFirstName ()
Gets first_name.
setFirstName ($first_name)
Sets first_name.
getLastName ()
Gets last_name.
setLastName ($last_name)
Sets last_name.
getEmail ()
Gets email.
setEmail ($email)
Sets email.
getPassword ()
Gets password.
setPassword ($password)
Sets password.
getPhone ()
Gets phone.
setPhone ($phone)
Sets phone.
getUserStatus ()
Gets user_status.
setUserStatus ($user_status)
Sets user_status.
offsetExists ($offset)
Returns true if offset exists.
offsetGet ($offset)
Gets offset.
offsetSet ($offset, $value)
Sets value based on offset.
offsetUnset ($offset)
Unsets offset.
jsonSerialize ()
Serializes the object to a value that can be serialized natively by json_encode().
__toString ()
Gets the string presentation of the object.
toHeaderValue ()
Gets a header-safe presentation of the object.
Static Public Member Functions
static openAPITypes ()
Array of property to type mappings.
static openAPIFormats ()
Array of property to format mappings.
static isNullable (string $property)
Checks if a property is nullable.
static static attributeMap ()
Array of attributes where the key is the local name, and the value is the original name.
static setters ()
Array of attributes to setter functions (for deserialization of responses)
static getters ()
Array of attributes to getter functions (for serialization of requests)
Public Attributes
const DISCRIMINATOR = null
Static Protected Member Functions
static openAPINullables ()
Array of nullable properties.
Protected Attributes
array $openAPINullablesSetToNull = []
$container = []
Static Protected Attributes
static $openAPIModelName = 'User'
static $openAPITypes
static $openAPIFormats
static array $openAPINullables
static $attributeMap
static $setters
static $getters
Private Member Functions
getOpenAPINullablesSetToNull ()
Array of nullable field names deliberately set to null.
setIfExists (string $variableName, array $fields, $defaultValue)
Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the $this->openAPINullablesSetToNull array.
Detailed Description
Definition at line 44 of file User.php.
Constructor & Destructor Documentation
__construct()
Ally\PetStore\Schema\User::__construct (array $data = null)
Constructor.
Parameters
mixed[] $data Associated array of property values initializing the model
Definition at line 278 of file User.php.
References Ally\PetStore\Schema\User\setIfExists().
     {
         $this->setIfExists('id', $data ?? [], null);
         $this->setIfExists('username', $data ?? [], null);
         $this->setIfExists('first_name', $data ?? [], null);
         $this->setIfExists('last_name', $data ?? [], null);
         $this->setIfExists('email', $data ?? [], null);
         $this->setIfExists('password', $data ?? [], null);
         $this->setIfExists('phone', $data ?? [], null);
         $this->setIfExists('user_status', $data ?? [], null);
     }
Member Function Documentation
__toString()
Ally\PetStore\Schema\User::__toString ()
Gets the string presentation of the object.
Returns
string
Definition at line 635 of file User.php.
References Ally\PetStore\ObjectSerializer\sanitizeForSerialization().
     {
         return json_encode(
             ObjectSerializer::sanitizeForSerialization($this),
             JSON_PRETTY_PRINT
         );
     }
attributeMap()
static static Ally\PetStore\Schema\User::attributeMap () static
Array of attributes where the key is the local name, and the value is the original name.
Returns
array
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 229 of file User.php.
     {
         return self::$attributeMap;
     }
getEmail()
Ally\PetStore\Schema\User::getEmail ()
Gets email.
Returns
string|null
Definition at line 453 of file User.php.
     {
         return $this->container['email'];
     }
getFirstName()
Ally\PetStore\Schema\User::getFirstName ()
Gets first_name.
Returns
string|null
Definition at line 395 of file User.php.
     {
         return $this->container['first_name'];
     }
getId()
Ally\PetStore\Schema\User::getId ()
Gets id.
Returns
int|null
Definition at line 337 of file User.php.
     {
         return $this->container['id'];
     }
getLastName()
Ally\PetStore\Schema\User::getLastName ()
Gets last_name.
Returns
string|null
Definition at line 424 of file User.php.
     {
         return $this->container['last_name'];
     }
getModelName()
Ally\PetStore\Schema\User::getModelName ()
The original name of the model.
Returns
string
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 259 of file User.php.
     {
         return self::$openAPIModelName;
     }
getOpenAPINullablesSetToNull()
Ally\PetStore\Schema\User::getOpenAPINullablesSetToNull () private
Array of nullable field names deliberately set to null.
Returns
boolean[]
Definition at line 147 of file User.php.
References Ally\PetStore\Schema\User\$openAPINullablesSetToNull.
Referenced by Ally\PetStore\Schema\User\isNullableSetToNull().
                                                    : array
     {
         return $this->openAPINullablesSetToNull;
     }
getPassword()
Ally\PetStore\Schema\User::getPassword ()
Gets password.
Returns
string|null
Definition at line 482 of file User.php.
     {
         return $this->container['password'];
     }
getPhone()
Ally\PetStore\Schema\User::getPhone ()
Gets phone.
Returns
string|null
Definition at line 511 of file User.php.
     {
         return $this->container['phone'];
     }
getters()
static Ally\PetStore\Schema\User::getters () static
Array of attributes to getter functions (for serialization of requests)
Returns
array
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 249 of file User.php.
     {
         return self::$getters;
     }
getUsername()
Ally\PetStore\Schema\User::getUsername ()
Gets username.
Returns
string|null
Definition at line 366 of file User.php.
     {
         return $this->container['username'];
     }
getUserStatus()
Ally\PetStore\Schema\User::getUserStatus ()
Gets user_status.
Returns
int|null
Definition at line 540 of file User.php.
     {
         return $this->container['user_status'];
     }
isNullable()
static Ally\PetStore\Schema\User::isNullable (string $property) static
Checks if a property is nullable.
Parameters
string $property
Returns
bool
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 158 of file User.php.
                                                        : bool
     {
         return self::openAPINullables()[$property] ?? false;
     }
isNullableSetToNull()
Ally\PetStore\Schema\User::isNullableSetToNull (string $property)
Checks if a nullable property is set to null.
Parameters
string $property
Returns
bool
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 169 of file User.php.
References Ally\PetStore\Schema\User\getOpenAPINullablesSetToNull().
                                                          : bool
     {
         return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
     }
jsonSerialize()
Ally\PetStore\Schema\User::jsonSerialize ()
Serializes the object to a value that can be serialized natively by json_encode().
mixed Returns data which can be serialized by json_encode(), which is a value of any type other than a resource.
Definition at line 625 of file User.php.
References Ally\PetStore\ObjectSerializer\sanitizeForSerialization().
     {
        return ObjectSerializer::sanitizeForSerialization($this);
     }
listInvalidProperties()
Ally\PetStore\Schema\User::listInvalidProperties ()
Show all the invalid properties with reasons.
Returns
array invalid properties with reasons
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 313 of file User.php.
Referenced by Ally\PetStore\Schema\User\valid().
     {
         $invalidProperties = [];
         return $invalidProperties;
     }
offsetExists()
Ally\PetStore\Schema\User::offsetExists ($offset)
Returns true if offset exists.
False otherwise.
Parameters
integer $offset Offset
Returns
boolean
Definition at line 570 of file User.php.
                                          : bool
     {
         return isset($this->container[$offset]);
     }
offsetGet()
Ally\PetStore\Schema\User::offsetGet ($offset)
Gets offset.
Parameters
integer $offset Offset
Returns
mixed|null
Definition at line 583 of file User.php.
     {
         return $this->container[$offset] ?? null;
     }
offsetSet()
Ally\PetStore\Schema\User::offsetSet ($offset, $value)
Sets value based on offset.
Parameters
int | null $offset Offset
mixed $value Value to be set
Returns
void
Definition at line 596 of file User.php.
                                               : void
     {
         if (is_null($offset)) {
             $this->container[] = $value;
         } else {
             $this->container[$offset] = $value;
         }
     }
offsetUnset()
Ally\PetStore\Schema\User::offsetUnset ($offset)
Unsets offset.
Parameters
integer $offset Offset
Returns
void
Definition at line 612 of file User.php.
                                         : void
     {
         unset($this->container[$offset]);
     }
openAPIFormats()
static Ally\PetStore\Schema\User::openAPIFormats () static
Array of property to format mappings.
Used for (de)serialization
Returns
array
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 127 of file User.php.
     {
         return self::$openAPIFormats;
     }
openAPINullables()
static Ally\PetStore\Schema\User::openAPINullables () static protected
Array of nullable properties.
Returns
array
Definition at line 137 of file User.php.
                                                 : array
     {
         return self::$openAPINullables;
     }
openAPITypes()
static Ally\PetStore\Schema\User::openAPITypes () static
Array of property to type mappings.
Used for (de)serialization
Returns
array
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 117 of file User.php.
     {
         return self::$openAPITypes;
     }
setEmail()
Ally\PetStore\Schema\User::setEmail ($email)
Sets email.
Parameters
string | null $email email
Returns
self
Definition at line 465 of file User.php.
     {
         if (is_null($email)) {
             throw new \InvalidArgumentException('non-nullable email cannot be null');
         }
         $this->container['email'] = $email;
         return $this;
     }
setFirstName()
Ally\PetStore\Schema\User::setFirstName ($first_name)
Sets first_name.
Parameters
string | null $first_name first_name
Returns
self
Definition at line 407 of file User.php.
     {
         if (is_null($first_name)) {
             throw new \InvalidArgumentException('non-nullable first_name cannot be null');
         }
         $this->container['first_name'] = $first_name;
         return $this;
     }
setId()
Ally\PetStore\Schema\User::setId ($id)
Sets id.
Parameters
int | null $id id
Returns
self
Definition at line 349 of file User.php.
     {
         if (is_null($id)) {
             throw new \InvalidArgumentException('non-nullable id cannot be null');
         }
         $this->container['id'] = $id;
         return $this;
     }
setIfExists()
Ally\PetStore\Schema\User::setIfExists (string $variableName, array $fields, $defaultValue) private
Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the $this->openAPINullablesSetToNull array.
Parameters
string $variableName
array $fields
mixed $defaultValue
Definition at line 299 of file User.php.
Referenced by Ally\PetStore\Schema\User\__construct().
                                                                                     : void
     {
         if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
             $this->openAPINullablesSetToNull[] = $variableName;
         }
         $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
     }
setLastName()
Ally\PetStore\Schema\User::setLastName ($last_name)
Sets last_name.
Parameters
string | null $last_name last_name
Returns
self
Definition at line 436 of file User.php.
     {
         if (is_null($last_name)) {
             throw new \InvalidArgumentException('non-nullable last_name cannot be null');
         }
         $this->container['last_name'] = $last_name;
         return $this;
     }
setPassword()
Ally\PetStore\Schema\User::setPassword ($password)
Sets password.
Parameters
string | null $password password
Returns
self
Definition at line 494 of file User.php.
     {
         if (is_null($password)) {
             throw new \InvalidArgumentException('non-nullable password cannot be null');
         }
         $this->container['password'] = $password;
         return $this;
     }
setPhone()
Ally\PetStore\Schema\User::setPhone ($phone)
Sets phone.
Parameters
string | null $phone phone
Returns
self
Definition at line 523 of file User.php.
     {
         if (is_null($phone)) {
             throw new \InvalidArgumentException('non-nullable phone cannot be null');
         }
         $this->container['phone'] = $phone;
         return $this;
     }
setters()
static Ally\PetStore\Schema\User::setters () static
Array of attributes to setter functions (for deserialization of responses)
Returns
array
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 239 of file User.php.
     {
         return self::$setters;
     }
setUsername()
Ally\PetStore\Schema\User::setUsername ($username)
Sets username.
Parameters
string | null $username username
Returns
self
Definition at line 378 of file User.php.
     {
         if (is_null($username)) {
             throw new \InvalidArgumentException('non-nullable username cannot be null');
         }
         $this->container['username'] = $username;
         return $this;
     }
setUserStatus()
Ally\PetStore\Schema\User::setUserStatus ($user_status)
Sets user_status.
Parameters
int | null $user_status User Status
Returns
self
Definition at line 552 of file User.php.
     {
         if (is_null($user_status)) {
             throw new \InvalidArgumentException('non-nullable user_status cannot be null');
         }
         $this->container['user_status'] = $user_status;
         return $this;
     }
toHeaderValue()
Ally\PetStore\Schema\User::toHeaderValue ()
Gets a header-safe presentation of the object.
Returns
string
Definition at line 648 of file User.php.
References Ally\PetStore\ObjectSerializer\sanitizeForSerialization().
     {
         return json_encode(ObjectSerializer::sanitizeForSerialization($this));
     }
valid()
Ally\PetStore\Schema\User::valid ()
Validate all the properties in the model return true if all passed.
Returns
bool True if all properties are valid
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 326 of file User.php.
References Ally\PetStore\Schema\User\listInvalidProperties().
     {
         return count($this->listInvalidProperties()) === 0;
     }
Member Data Documentation
$attributeMap
Ally\PetStore\Schema\User::$attributeMap static protected
Initial value:
= [
        'id' => 'id'
Definition at line 180 of file User.php.
$container
Ally\PetStore\Schema\User::$container = [] protected
Definition at line 270 of file User.php.
$getters
Ally\PetStore\Schema\User::$getters static protected
Initial value:
= [
        'id' => 'getId'
Definition at line 212 of file User.php.
$openAPIFormats
Ally\PetStore\Schema\User::$openAPIFormats static protected
Initial value:
= [
        'id' => 'int64'
Definition at line 78 of file User.php.
$openAPIModelName
Ally\PetStore\Schema\User::$openAPIModelName = 'User' static protected
Definition at line 53 of file User.php.
$openAPINullables
array Ally\PetStore\Schema\User::$openAPINullables static protected
Initial value:
= [
        'id' => false
Definition at line 94 of file User.php.
$openAPINullablesSetToNull
array Ally\PetStore\Schema\User::$openAPINullablesSetToNull = [] protected
Definition at line 110 of file User.php.
Referenced by Ally\PetStore\Schema\User\getOpenAPINullablesSetToNull().
$openAPITypes
Ally\PetStore\Schema\User::$openAPITypes static protected
Initial value:
= [
        'id' => 'int'
Definition at line 60 of file User.php.
$setters
Ally\PetStore\Schema\User::$setters static protected
Initial value:
= [
        'id' => 'setId'
Definition at line 196 of file User.php.
DISCRIMINATOR
const Ally\PetStore\Schema\User::DISCRIMINATOR = null
Definition at line 46 of file User.php.
The documentation for this class was generated from the following file:
src/Schema/User.php