Ally'sPetStoreAPI: Ally\PetStore\Schema\Order Class Reference
Ally\PetStore\Schema\Order Class Reference
Public Member Functions
isNullableSetToNull (string $property)
Checks if a nullable property is set to null.
getModelName ()
The original name of the model.
getStatusAllowableValues ()
Gets allowable values of the enum.
__construct (array $data=null)
Constructor.
listInvalidProperties ()
Show all the invalid properties with reasons.
valid ()
Validate all the properties in the model return true if all passed.
getId ()
Gets id.
setId ($id)
Sets id.
getPetId ()
Gets pet_id.
setPetId ($pet_id)
Sets pet_id.
getQuantity ()
Gets quantity.
setQuantity ($quantity)
Sets quantity.
getShipDate ()
Gets ship_date.
setShipDate ($ship_date)
Sets ship_date.
getStatus ()
Gets status.
setStatus ($status)
Sets status.
getComplete ()
Gets complete.
setComplete ($complete)
Sets complete.
offsetExists ($offset)
Returns true if offset exists.
offsetGet ($offset)
Gets offset.
offsetSet ($offset, $value)
Sets value based on offset.
offsetUnset ($offset)
Unsets offset.
jsonSerialize ()
Serializes the object to a value that can be serialized natively by json_encode().
__toString ()
Gets the string presentation of the object.
toHeaderValue ()
Gets a header-safe presentation of the object.
Static Public Member Functions
static openAPITypes ()
Array of property to type mappings.
static openAPIFormats ()
Array of property to format mappings.
static isNullable (string $property)
Checks if a property is nullable.
static static attributeMap ()
Array of attributes where the key is the local name, and the value is the original name.
static setters ()
Array of attributes to setter functions (for deserialization of responses)
static getters ()
Array of attributes to getter functions (for serialization of requests)
Public Attributes
const DISCRIMINATOR = null
const STATUS_PLACED = 'placed'
const STATUS_APPROVED = 'approved'
const STATUS_DELIVERED = 'delivered'
Static Protected Member Functions
static openAPINullables ()
Array of nullable properties.
Protected Attributes
array $openAPINullablesSetToNull = []
$container = []
Static Protected Attributes
static $openAPIModelName = 'Order'
static $openAPITypes
static $openAPIFormats
static array $openAPINullables
static $attributeMap
static $setters
static $getters
Private Member Functions
getOpenAPINullablesSetToNull ()
Array of nullable field names deliberately set to null.
setIfExists (string $variableName, array $fields, $defaultValue)
Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the $this->openAPINullablesSetToNull array.
Detailed Description
Definition at line 44 of file Order.php.
Constructor & Destructor Documentation
__construct()
Ally\PetStore\Schema\Order::__construct (array $data = null)
Constructor.
Parameters
mixed[] $data Associated array of property values initializing the model
Definition at line 283 of file Order.php.
References Ally\PetStore\Schema\Order\setIfExists().
     {
         $this->setIfExists('id', $data ?? [], null);
         $this->setIfExists('pet_id', $data ?? [], null);
         $this->setIfExists('quantity', $data ?? [], null);
         $this->setIfExists('ship_date', $data ?? [], null);
         $this->setIfExists('status', $data ?? [], null);
         $this->setIfExists('complete', $data ?? [], false);
     }
Member Function Documentation
__toString()
Ally\PetStore\Schema\Order::__toString ()
Gets the string presentation of the object.
Returns
string
Definition at line 599 of file Order.php.
References Ally\PetStore\ObjectSerializer\sanitizeForSerialization().
     {
         return json_encode(
             ObjectSerializer::sanitizeForSerialization($this),
             JSON_PRETTY_PRINT
         );
     }
attributeMap()
static static Ally\PetStore\Schema\Order::attributeMap () static
Array of attributes where the key is the local name, and the value is the original name.
Returns
array
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 217 of file Order.php.
     {
         return self::$attributeMap;
     }
getComplete()
Ally\PetStore\Schema\Order::getComplete ()
Gets complete.
Returns
bool|null
Definition at line 504 of file Order.php.
     {
         return $this->container['complete'];
     }
getId()
Ally\PetStore\Schema\Order::getId ()
Gets id.
Returns
int|null
Definition at line 349 of file Order.php.
     {
         return $this->container['id'];
     }
getModelName()
Ally\PetStore\Schema\Order::getModelName ()
The original name of the model.
Returns
string
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 247 of file Order.php.
     {
         return self::$openAPIModelName;
     }
getOpenAPINullablesSetToNull()
Ally\PetStore\Schema\Order::getOpenAPINullablesSetToNull () private
Array of nullable field names deliberately set to null.
Returns
boolean[]
Definition at line 141 of file Order.php.
References Ally\PetStore\Schema\Order\$openAPINullablesSetToNull.
Referenced by Ally\PetStore\Schema\Order\isNullableSetToNull().
                                                    : array
     {
         return $this->openAPINullablesSetToNull;
     }
getPetId()
Ally\PetStore\Schema\Order::getPetId ()
Gets pet_id.
Returns
int|null
Definition at line 378 of file Order.php.
     {
         return $this->container['pet_id'];
     }
getQuantity()
Ally\PetStore\Schema\Order::getQuantity ()
Gets quantity.
Returns
int|null
Definition at line 407 of file Order.php.
     {
         return $this->container['quantity'];
     }
getShipDate()
Ally\PetStore\Schema\Order::getShipDate ()
Gets ship_date.
Returns
|null
Definition at line 436 of file Order.php.
     {
         return $this->container['ship_date'];
     }
getStatus()
Ally\PetStore\Schema\Order::getStatus ()
Gets status.
Returns
string|null
Definition at line 465 of file Order.php.
     {
         return $this->container['status'];
     }
getStatusAllowableValues()
Ally\PetStore\Schema\Order::getStatusAllowableValues ()
Gets allowable values of the enum.
Returns
string[]
Definition at line 261 of file Order.php.
Referenced by Ally\PetStore\Schema\Order\listInvalidProperties(), and Ally\PetStore\Schema\Order\setStatus().
     {
         return [
             self::STATUS_PLACED,
             self::STATUS_APPROVED,
             self::STATUS_DELIVERED,
         ];
     }
getters()
static Ally\PetStore\Schema\Order::getters () static
Array of attributes to getter functions (for serialization of requests)
Returns
array
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 237 of file Order.php.
     {
         return self::$getters;
     }
isNullable()
static Ally\PetStore\Schema\Order::isNullable (string $property) static
Checks if a property is nullable.
Parameters
string $property
Returns
bool
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 152 of file Order.php.
                                                        : bool
     {
         return self::openAPINullables()[$property] ?? false;
     }
isNullableSetToNull()
Ally\PetStore\Schema\Order::isNullableSetToNull (string $property)
Checks if a nullable property is set to null.
Parameters
string $property
Returns
bool
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 163 of file Order.php.
References Ally\PetStore\Schema\Order\getOpenAPINullablesSetToNull().
                                                          : bool
     {
         return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
     }
jsonSerialize()
Ally\PetStore\Schema\Order::jsonSerialize ()
Serializes the object to a value that can be serialized natively by json_encode().
mixed Returns data which can be serialized by json_encode(), which is a value of any type other than a resource.
Definition at line 589 of file Order.php.
References Ally\PetStore\ObjectSerializer\sanitizeForSerialization().
     {
        return ObjectSerializer::sanitizeForSerialization($this);
     }
listInvalidProperties()
Ally\PetStore\Schema\Order::listInvalidProperties ()
Show all the invalid properties with reasons.
Returns
array invalid properties with reasons
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 316 of file Order.php.
References Ally\PetStore\Schema\Order\getStatusAllowableValues().
Referenced by Ally\PetStore\Schema\Order\valid().
     {
         $invalidProperties = [];
         $allowedValues = $this->getStatusAllowableValues();
         if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
             $invalidProperties[] = sprintf(
                 "invalid value '%s' for 'status', must be one of '%s'",
                 $this->container['status'],
                 implode("', '", $allowedValues)
             );
         }
         return $invalidProperties;
     }
offsetExists()
Ally\PetStore\Schema\Order::offsetExists ($offset)
Returns true if offset exists.
False otherwise.
Parameters
integer $offset Offset
Returns
boolean
Definition at line 534 of file Order.php.
                                          : bool
     {
         return isset($this->container[$offset]);
     }
offsetGet()
Ally\PetStore\Schema\Order::offsetGet ($offset)
Gets offset.
Parameters
integer $offset Offset
Returns
mixed|null
Definition at line 547 of file Order.php.
     {
         return $this->container[$offset] ?? null;
     }
offsetSet()
Ally\PetStore\Schema\Order::offsetSet ($offset, $value)
Sets value based on offset.
Parameters
int | null $offset Offset
mixed $value Value to be set
Returns
void
Definition at line 560 of file Order.php.
                                               : void
     {
         if (is_null($offset)) {
             $this->container[] = $value;
         } else {
             $this->container[$offset] = $value;
         }
     }
offsetUnset()
Ally\PetStore\Schema\Order::offsetUnset ($offset)
Unsets offset.
Parameters
integer $offset Offset
Returns
void
Definition at line 576 of file Order.php.
                                         : void
     {
         unset($this->container[$offset]);
     }
openAPIFormats()
static Ally\PetStore\Schema\Order::openAPIFormats () static
Array of property to format mappings.
Used for (de)serialization
Returns
array
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 121 of file Order.php.
     {
         return self::$openAPIFormats;
     }
openAPINullables()
static Ally\PetStore\Schema\Order::openAPINullables () static protected
Array of nullable properties.
Returns
array
Definition at line 131 of file Order.php.
                                                 : array
     {
         return self::$openAPINullables;
     }
openAPITypes()
static Ally\PetStore\Schema\Order::openAPITypes () static
Array of property to type mappings.
Used for (de)serialization
Returns
array
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 111 of file Order.php.
     {
         return self::$openAPITypes;
     }
setComplete()
Ally\PetStore\Schema\Order::setComplete ($complete)
Sets complete.
Parameters
bool | null $complete complete
Returns
self
Definition at line 516 of file Order.php.
     {
         if (is_null($complete)) {
             throw new \InvalidArgumentException('non-nullable complete cannot be null');
         }
         $this->container['complete'] = $complete;
         return $this;
     }
setId()
Ally\PetStore\Schema\Order::setId ($id)
Sets id.
Parameters
int | null $id id
Returns
self
Definition at line 361 of file Order.php.
     {
         if (is_null($id)) {
             throw new \InvalidArgumentException('non-nullable id cannot be null');
         }
         $this->container['id'] = $id;
         return $this;
     }
setIfExists()
Ally\PetStore\Schema\Order::setIfExists (string $variableName, array $fields, $defaultValue) private
Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the $this->openAPINullablesSetToNull array.
Parameters
string $variableName
array $fields
mixed $defaultValue
Definition at line 302 of file Order.php.
Referenced by Ally\PetStore\Schema\Order\__construct().
                                                                                     : void
     {
         if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
             $this->openAPINullablesSetToNull[] = $variableName;
         }
         $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
     }
setPetId()
Ally\PetStore\Schema\Order::setPetId ($pet_id)
Sets pet_id.
Parameters
int | null $pet_id pet_id
Returns
self
Definition at line 390 of file Order.php.
     {
         if (is_null($pet_id)) {
             throw new \InvalidArgumentException('non-nullable pet_id cannot be null');
         }
         $this->container['pet_id'] = $pet_id;
         return $this;
     }
setQuantity()
Ally\PetStore\Schema\Order::setQuantity ($quantity)
Sets quantity.
Parameters
int | null $quantity quantity
Returns
self
Definition at line 419 of file Order.php.
     {
         if (is_null($quantity)) {
             throw new \InvalidArgumentException('non-nullable quantity cannot be null');
         }
         $this->container['quantity'] = $quantity;
         return $this;
     }
setShipDate()
Ally\PetStore\Schema\Order::setShipDate ($ship_date)
Sets ship_date.
Parameters
\DateTime | null $ship_date ship_date
Returns
self
Definition at line 448 of file Order.php.
     {
         if (is_null($ship_date)) {
             throw new \InvalidArgumentException('non-nullable ship_date cannot be null');
         }
         $this->container['ship_date'] = $ship_date;
         return $this;
     }
setStatus()
Ally\PetStore\Schema\Order::setStatus ($status)
Sets status.
Parameters
string | null $status Order Status
Returns
self
Definition at line 477 of file Order.php.
References Ally\PetStore\Schema\Order\getStatusAllowableValues().
     {
         $allowedValues = $this->getStatusAllowableValues();
         if (!is_null($status) && !in_array($status, $allowedValues, true)) {
             throw new \InvalidArgumentException(
                 sprintf(
                     "Invalid value '%s' for 'status', must be one of '%s'",
                     $status,
                     implode("', '", $allowedValues)
                 )
             );
         }
         if (is_null($status)) {
             throw new \InvalidArgumentException('non-nullable status cannot be null');
         }
         $this->container['status'] = $status;
         return $this;
     }
setters()
static Ally\PetStore\Schema\Order::setters () static
Array of attributes to setter functions (for deserialization of responses)
Returns
array
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 227 of file Order.php.
     {
         return self::$setters;
     }
toHeaderValue()
Ally\PetStore\Schema\Order::toHeaderValue ()
Gets a header-safe presentation of the object.
Returns
string
Definition at line 612 of file Order.php.
References Ally\PetStore\ObjectSerializer\sanitizeForSerialization().
     {
         return json_encode(ObjectSerializer::sanitizeForSerialization($this));
     }
valid()
Ally\PetStore\Schema\Order::valid ()
Validate all the properties in the model return true if all passed.
Returns
bool True if all properties are valid
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 338 of file Order.php.
References Ally\PetStore\Schema\Order\listInvalidProperties().
     {
         return count($this->listInvalidProperties()) === 0;
     }
Member Data Documentation
$attributeMap
Ally\PetStore\Schema\Order::$attributeMap static protected
Initial value:
= [
        'id' => 'id'
Definition at line 174 of file Order.php.
$container
Ally\PetStore\Schema\Order::$container = [] protected
Definition at line 275 of file Order.php.
$getters
Ally\PetStore\Schema\Order::$getters static protected
Initial value:
= [
        'id' => 'getId'
Definition at line 202 of file Order.php.
$openAPIFormats
Ally\PetStore\Schema\Order::$openAPIFormats static protected
Initial value:
= [
        'id' => 'int64'
Definition at line 76 of file Order.php.
$openAPIModelName
Ally\PetStore\Schema\Order::$openAPIModelName = 'Order' static protected
Definition at line 53 of file Order.php.
$openAPINullables
array Ally\PetStore\Schema\Order::$openAPINullables static protected
Initial value:
= [
        'id' => false
Definition at line 90 of file Order.php.
$openAPINullablesSetToNull
array Ally\PetStore\Schema\Order::$openAPINullablesSetToNull = [] protected
Definition at line 104 of file Order.php.
Referenced by Ally\PetStore\Schema\Order\getOpenAPINullablesSetToNull().
$openAPITypes
Ally\PetStore\Schema\Order::$openAPITypes static protected
Initial value:
= [
        'id' => 'int'
Definition at line 60 of file Order.php.
$setters
Ally\PetStore\Schema\Order::$setters static protected
Initial value:
= [
        'id' => 'setId'
Definition at line 188 of file Order.php.
DISCRIMINATOR
const Ally\PetStore\Schema\Order::DISCRIMINATOR = null
Definition at line 46 of file Order.php.
STATUS_APPROVED
const Ally\PetStore\Schema\Order::STATUS_APPROVED = 'approved'
Definition at line 253 of file Order.php.
STATUS_DELIVERED
const Ally\PetStore\Schema\Order::STATUS_DELIVERED = 'delivered'
Definition at line 254 of file Order.php.
STATUS_PLACED
const Ally\PetStore\Schema\Order::STATUS_PLACED = 'placed'
Definition at line 252 of file Order.php.
The documentation for this class was generated from the following file:
src/Schema/Order.php