Ally'sPetStoreAPI: Ally\PetStore\Api\StoreApi Class Reference
Ally\PetStore\Api\StoreApi Class Reference
Public Member Functions
__construct (ClientInterface $client=null, Configuration $config=null, HeaderSelector $selector=null, $hostIndex=0)
setHostIndex ($hostIndex)
Set the host index.
getHostIndex ()
Get the host index.
getConfig ()
deleteOrder ($order_id)
Operation deleteOrder.
deleteOrderWithHttpInfo ($order_id)
Operation deleteOrderWithHttpInfo.
deleteOrderAsync ($order_id)
Operation deleteOrderAsync.
deleteOrderAsyncWithHttpInfo ($order_id)
Operation deleteOrderAsyncWithHttpInfo.
deleteOrderRequest ($order_id)
Create request for operation 'deleteOrder'.
getInventory ()
Operation getInventory.
getInventoryWithHttpInfo ()
Operation getInventoryWithHttpInfo.
getInventoryAsync ()
Operation getInventoryAsync.
getInventoryAsyncWithHttpInfo ()
Operation getInventoryAsyncWithHttpInfo.
getInventoryRequest ()
Create request for operation 'getInventory'.
getOrderById ($order_id)
Operation getOrderById.
getOrderByIdWithHttpInfo ($order_id)
Operation getOrderByIdWithHttpInfo.
getOrderByIdAsync ($order_id)
Operation getOrderByIdAsync.
getOrderByIdAsyncWithHttpInfo ($order_id)
Operation getOrderByIdAsyncWithHttpInfo.
getOrderByIdRequest ($order_id)
Create request for operation 'getOrderById'.
placeOrder ($order)
Operation placeOrder.
placeOrderWithHttpInfo ($order)
Operation placeOrderWithHttpInfo.
placeOrderAsync ($order)
Operation placeOrderAsync.
placeOrderAsyncWithHttpInfo ($order)
Operation placeOrderAsyncWithHttpInfo.
placeOrderRequest ($order)
Create request for operation 'placeOrder'.
Protected Member Functions
createHttpClientOption ()
Create http client option.
Protected Attributes
$client
$config
$headerSelector
$hostIndex
Detailed Description
Definition at line 50 of file StoreApi.php.
Constructor & Destructor Documentation
__construct()
Ally\PetStore\Api\StoreApi::__construct (ClientInterface $client = null, Configuration $config = null, HeaderSelector $selector = null, $hostIndex = 0)
Parameters
ClientInterface $client
Configuration $config
HeaderSelector $selector
int $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
Definition at line 78 of file StoreApi.php.
References Ally\PetStore\Api\StoreApi\$client, Ally\PetStore\Api\StoreApi\$config, and Ally\PetStore\Api\StoreApi\$hostIndex.
       {
         $this->client = $client ?: new Client();
         $this->config = $config ?: new Configuration();
         $this->headerSelector = $selector ?: new HeaderSelector();
         $this->hostIndex = $hostIndex;
     }
Member Function Documentation
createHttpClientOption()
Ally\PetStore\Api\StoreApi::createHttpClientOption () protected
Create http client option.
Exceptions
Definition at line 1188 of file StoreApi.php.
Referenced by Ally\PetStore\Api\StoreApi\deleteOrderAsyncWithHttpInfo(), Ally\PetStore\Api\StoreApi\deleteOrderWithHttpInfo(), Ally\PetStore\Api\StoreApi\getInventoryAsyncWithHttpInfo(), Ally\PetStore\Api\StoreApi\getInventoryWithHttpInfo(), Ally\PetStore\Api\StoreApi\getOrderByIdAsyncWithHttpInfo(), Ally\PetStore\Api\StoreApi\getOrderByIdWithHttpInfo(), Ally\PetStore\Api\StoreApi\placeOrderAsyncWithHttpInfo(), and Ally\PetStore\Api\StoreApi\placeOrderWithHttpInfo().
     {
         $options = [];
         if ($this->config->getDebug()) {
             $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
             if (!$options[RequestOptions::DEBUG]) {
                 throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
             }
         }
         return $options;
     }
deleteOrder()
Ally\PetStore\Api\StoreApi::deleteOrder ($order_id)
Operation deleteOrder.
Delete purchase order by ID
Parameters
string $order_id ID of the order that needs to be deleted (required)
Exceptions
Definition at line 129 of file StoreApi.php.
References Ally\PetStore\Api\StoreApi\deleteOrderWithHttpInfo().
     {
         $this->deleteOrderWithHttpInfo($order_id);
     }
deleteOrderAsync()
Ally\PetStore\Api\StoreApi::deleteOrderAsync ($order_id)
Operation deleteOrderAsync.
Delete purchase order by ID
Parameters
string $order_id ID of the order that needs to be deleted (required)
Exceptions
Definition at line 203 of file StoreApi.php.
References Ally\PetStore\Api\StoreApi\deleteOrderAsyncWithHttpInfo().
     {
         return $this->deleteOrderAsyncWithHttpInfo($order_id)
             ->then(
                 function ($response) {
                     return $response[0];
                 }
             );
     }
deleteOrderAsyncWithHttpInfo()
Ally\PetStore\Api\StoreApi::deleteOrderAsyncWithHttpInfo ($order_id)
Operation deleteOrderAsyncWithHttpInfo.
Delete purchase order by ID
Parameters
string $order_id ID of the order that needs to be deleted (required)
Exceptions
Definition at line 223 of file StoreApi.php.
References Ally\PetStore\Api\StoreApi\createHttpClientOption(), and Ally\PetStore\Api\StoreApi\deleteOrderRequest().
Referenced by Ally\PetStore\Api\StoreApi\deleteOrderAsync().
     {
         $returnType = '';
         $request = $this->deleteOrderRequest($order_id);
         return $this->client
             ->sendAsync($request, $this->createHttpClientOption())
             ->then(
                 function ($response) use ($returnType) {
                     return [null, $response->getStatusCode(), $response->getHeaders()];
                 },
                 function ($exception) {
                     $response = $exception->getResponse();
                     $statusCode = $response->getStatusCode();
                     throw new ApiException(
                         sprintf(
                             '[%d] Error connecting to the API (%s)',
                             $statusCode,
                             $exception->getRequest()->getUri()
                         ),
                         $statusCode,
                         $response->getHeaders(),
                         (string) $response->getBody()
                     );
                 }
             );
     }
deleteOrderRequest()
Ally\PetStore\Api\StoreApi::deleteOrderRequest ($order_id)
Create request for operation 'deleteOrder'.
Parameters
string $order_id ID of the order that needs to be deleted (required)
Exceptions
Definition at line 259 of file StoreApi.php.
References Ally\PetStore\ObjectSerializer\buildQuery(), and Ally\PetStore\ObjectSerializer\toPathValue().
Referenced by Ally\PetStore\Api\StoreApi\deleteOrderAsyncWithHttpInfo(), and Ally\PetStore\Api\StoreApi\deleteOrderWithHttpInfo().
     {
         // verify the required parameter 'order_id' is set
         if ($order_id === null || (is_array($order_id) && count($order_id) === 0)) {
             throw new \InvalidArgumentException(
                 'Missing the required parameter $order_id when calling deleteOrder'
             );
         }
         $resourcePath = '/store/order/{orderId}';
         $formParams = [];
         $queryParams = [];
         $headerParams = [];
         $httpBody = '';
         $multipart = false;
         // path params
         if ($order_id !== null) {
             $resourcePath = str_replace(
                 '{' . 'orderId' . '}',
                 ObjectSerializer::toPathValue($order_id),
                 $resourcePath
             );
         }
         if ($multipart) {
             $headers = $this->headerSelector->selectHeadersForMultipart(
                 []
             );
         } else {
             $headers = $this->headerSelector->selectHeaders(
                 [],
                 []
             );
         }
         // for model (json/xml)
         if (count($formParams) > 0) {
             if ($multipart) {
                 $multipartContents = [];
                 foreach ($formParams as $formParamName => $formParamValue) {
                     $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                     foreach ($formParamValueItems as $formParamValueItem) {
                         $multipartContents[] = [
                             'name' => $formParamName,
                             'contents' => $formParamValueItem
                         ];
                     }
                 }
                 // for HTTP post (form)
                 $httpBody = new MultipartStream($multipartContents);
             } elseif ($headers['Content-Type'] === 'application/json') {
                 $httpBody = \GuzzleHttp\json_encode($formParams);
             } else {
                 // for HTTP post (form)
                 $httpBody = ObjectSerializer::buildQuery($formParams);
             }
         }
         $defaultHeaders = [];
         if ($this->config->getUserAgent()) {
             $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
         }
         $headers = array_merge(
             $defaultHeaders,
             $headerParams,
             $headers
         );
         $operationHost = $this->config->getHost();
         $query = ObjectSerializer::buildQuery($queryParams);
         return new Request(
             'DELETE',
             $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
             $headers,
             $httpBody
         );
     }
deleteOrderWithHttpInfo()
Ally\PetStore\Api\StoreApi::deleteOrderWithHttpInfo ($order_id)
Operation deleteOrderWithHttpInfo.
Delete purchase order by ID
Parameters
string $order_id ID of the order that needs to be deleted (required)
Exceptions
Definition at line 145 of file StoreApi.php.
References Ally\PetStore\Api\StoreApi\createHttpClientOption(), and Ally\PetStore\Api\StoreApi\deleteOrderRequest().
Referenced by Ally\PetStore\Api\StoreApi\deleteOrder().
     {
         $request = $this->deleteOrderRequest($order_id);
         try {
             $options = $this->createHttpClientOption();
             try {
                 $response = $this->client->send($request, $options);
             } catch (RequestException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                     $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                 );
             } catch (ConnectException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     null,
                     null
                 );
             }
             $statusCode = $response->getStatusCode();
             if ($statusCode < 200 || $statusCode > 299) {
                 throw new ApiException(
                     sprintf(
                         '[%d] Error connecting to the API (%s)',
                         $statusCode,
                         (string) $request->getUri()
                     ),
                     $statusCode,
                     $response->getHeaders(),
                     (string) $response->getBody()
                 );
             }
             return [null, $statusCode, $response->getHeaders()];
         } catch (ApiException $e) {
             switch ($e->getCode()) {
             }
             throw $e;
         }
     }
getConfig()
Ally\PetStore\Api\StoreApi::getConfig ()
Returns
Configuration
Definition at line 113 of file StoreApi.php.
References Ally\PetStore\Api\StoreApi\$config.
     {
         return $this->config;
     }
getHostIndex()
Ally\PetStore\Api\StoreApi::getHostIndex ()
Get the host index.
Returns
int Host index
Definition at line 105 of file StoreApi.php.
References Ally\PetStore\Api\StoreApi\$hostIndex.
     {
         return $this->hostIndex;
     }
getInventory()
Ally\PetStore\Api\StoreApi::getInventory ()
Operation getInventory.
Returns pet inventories by status
Exceptions
Definition at line 356 of file StoreApi.php.
References Ally\PetStore\Api\StoreApi\getInventoryWithHttpInfo().
     {
         list($response) = $this->getInventoryWithHttpInfo();
         return $response;
     }
getInventoryAsync()
Ally\PetStore\Api\StoreApi::getInventoryAsync ()
Operation getInventoryAsync.
Returns pet inventories by status
Exceptions
Definition at line 469 of file StoreApi.php.
References Ally\PetStore\Api\StoreApi\getInventoryAsyncWithHttpInfo().
     {
         return $this->getInventoryAsyncWithHttpInfo()
             ->then(
                 function ($response) {
                     return $response[0];
                 }
             );
     }
getInventoryAsyncWithHttpInfo()
Ally\PetStore\Api\StoreApi::getInventoryAsyncWithHttpInfo ()
Operation getInventoryAsyncWithHttpInfo.
Returns pet inventories by status
Exceptions
Definition at line 488 of file StoreApi.php.
References Ally\PetStore\Api\StoreApi\createHttpClientOption(), and Ally\PetStore\Api\StoreApi\getInventoryRequest().
Referenced by Ally\PetStore\Api\StoreApi\getInventoryAsync().
     {
         $returnType = 'array<string,int>';
         $request = $this->getInventoryRequest();
         return $this->client
             ->sendAsync($request, $this->createHttpClientOption())
             ->then(
                 function ($response) use ($returnType) {
                     if ($returnType === '\SplFileObject') {
                         $content = $response->getBody(); //stream goes to serializer
                     } else {
                         $content = (string) $response->getBody();
                         if ($returnType !== 'string') {
                             $content = json_decode($content);
                         }
                     }
                     return [
                         ObjectSerializer::deserialize($content, $returnType, []),
                         $response->getStatusCode(),
                         $response->getHeaders()
                     ];
                 },
                 function ($exception) {
                     $response = $exception->getResponse();
                     $statusCode = $response->getStatusCode();
                     throw new ApiException(
                         sprintf(
                             '[%d] Error connecting to the API (%s)',
                             $statusCode,
                             $exception->getRequest()->getUri()
                         ),
                         $statusCode,
                         $response->getHeaders(),
                         (string) $response->getBody()
                     );
                 }
             );
     }
getInventoryRequest()
Ally\PetStore\Api\StoreApi::getInventoryRequest ()
Create request for operation 'getInventory'.
Exceptions
Definition at line 536 of file StoreApi.php.
References Ally\PetStore\ObjectSerializer\buildQuery().
Referenced by Ally\PetStore\Api\StoreApi\getInventoryAsyncWithHttpInfo(), and Ally\PetStore\Api\StoreApi\getInventoryWithHttpInfo().
     {
         $resourcePath = '/store/inventory';
         $formParams = [];
         $queryParams = [];
         $headerParams = [];
         $httpBody = '';
         $multipart = false;
         if ($multipart) {
             $headers = $this->headerSelector->selectHeadersForMultipart(
                 ['application/json']
             );
         } else {
             $headers = $this->headerSelector->selectHeaders(
                 ['application/json'],
                 []
             );
         }
         // for model (json/xml)
         if (count($formParams) > 0) {
             if ($multipart) {
                 $multipartContents = [];
                 foreach ($formParams as $formParamName => $formParamValue) {
                     $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                     foreach ($formParamValueItems as $formParamValueItem) {
                         $multipartContents[] = [
                             'name' => $formParamName,
                             'contents' => $formParamValueItem
                         ];
                     }
                 }
                 // for HTTP post (form)
                 $httpBody = new MultipartStream($multipartContents);
             } elseif ($headers['Content-Type'] === 'application/json') {
                 $httpBody = \GuzzleHttp\json_encode($formParams);
             } else {
                 // for HTTP post (form)
                 $httpBody = ObjectSerializer::buildQuery($formParams);
             }
         }
         // this endpoint requires API key authentication
         $apiKey = $this->config->getApiKeyWithPrefix('api_key');
         if ($apiKey !== null) {
             $headers['api_key'] = $apiKey;
         }
         $defaultHeaders = [];
         if ($this->config->getUserAgent()) {
             $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
         }
         $headers = array_merge(
             $defaultHeaders,
             $headerParams,
             $headers
         );
         $operationHost = $this->config->getHost();
         $query = ObjectSerializer::buildQuery($queryParams);
         return new Request(
             'GET',
             $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
             $headers,
             $httpBody
         );
     }
getInventoryWithHttpInfo()
Ally\PetStore\Api\StoreApi::getInventoryWithHttpInfo ()
Operation getInventoryWithHttpInfo.
Returns pet inventories by status
Exceptions
Definition at line 372 of file StoreApi.php.
References Ally\PetStore\Api\StoreApi\createHttpClientOption(), Ally\PetStore\Api\StoreApi\getInventoryRequest(), Ally\PetStore\ApiException\getResponseBody(), Ally\PetStore\ApiException\getResponseHeaders(), and Ally\PetStore\ApiException\setResponseObject().
Referenced by Ally\PetStore\Api\StoreApi\getInventory().
     {
         $request = $this->getInventoryRequest();
         try {
             $options = $this->createHttpClientOption();
             try {
                 $response = $this->client->send($request, $options);
             } catch (RequestException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                     $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                 );
             } catch (ConnectException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     null,
                     null
                 );
             }
             $statusCode = $response->getStatusCode();
             if ($statusCode < 200 || $statusCode > 299) {
                 throw new ApiException(
                     sprintf(
                         '[%d] Error connecting to the API (%s)',
                         $statusCode,
                         (string) $request->getUri()
                     ),
                     $statusCode,
                     $response->getHeaders(),
                     (string) $response->getBody()
                 );
             }
             switch($statusCode) {
                 case 200:
                     if ('array<string,int>' === '\SplFileObject') {
                         $content = $response->getBody(); //stream goes to serializer
                     } else {
                         $content = (string) $response->getBody();
                         if ('array<string,int>' !== 'string') {
                             $content = json_decode($content);
                         }
                     }
                     return [
                         ObjectSerializer::deserialize($content, 'array<string,int>', []),
                         $response->getStatusCode(),
                         $response->getHeaders()
                     ];
             }
             $returnType = 'array<string,int>';
             if ($returnType === '\SplFileObject') {
                 $content = $response->getBody(); //stream goes to serializer
             } else {
                 $content = (string) $response->getBody();
                 if ($returnType !== 'string') {
                     $content = json_decode($content);
                 }
             }
             return [
                 ObjectSerializer::deserialize($content, $returnType, []),
                 $response->getStatusCode(),
                 $response->getHeaders()
             ];
         } catch (ApiException $e) {
             switch ($e->getCode()) {
                 case 200:
                     $data = ObjectSerializer::deserialize(
                         $e->getResponseBody(),
                         'array<string,int>',
                         $e->getResponseHeaders()
                     );
                     $e->setResponseObject($data);
                     break;
             }
             throw $e;
         }
     }
getOrderById()
Ally\PetStore\Api\StoreApi::getOrderById ($order_id)
Operation getOrderById.
Find purchase order by ID
Parameters
int $order_id ID of pet that needs to be fetched (required)
Exceptions
Definition at line 624 of file StoreApi.php.
References Ally\PetStore\Api\StoreApi\getOrderByIdWithHttpInfo().
     {
         list($response) = $this->getOrderByIdWithHttpInfo($order_id);
         return $response;
     }
getOrderByIdAsync()
Ally\PetStore\Api\StoreApi::getOrderByIdAsync ($order_id)
Operation getOrderByIdAsync.
Find purchase order by ID
Parameters
int $order_id ID of pet that needs to be fetched (required)
Exceptions
Definition at line 739 of file StoreApi.php.
References Ally\PetStore\Api\StoreApi\getOrderByIdAsyncWithHttpInfo().
     {
         return $this->getOrderByIdAsyncWithHttpInfo($order_id)
             ->then(
                 function ($response) {
                     return $response[0];
                 }
             );
     }
getOrderByIdAsyncWithHttpInfo()
Ally\PetStore\Api\StoreApi::getOrderByIdAsyncWithHttpInfo ($order_id)
Operation getOrderByIdAsyncWithHttpInfo.
Find purchase order by ID
Parameters
int $order_id ID of pet that needs to be fetched (required)
Exceptions
Definition at line 759 of file StoreApi.php.
References Ally\PetStore\Api\StoreApi\createHttpClientOption(), and Ally\PetStore\Api\StoreApi\getOrderByIdRequest().
Referenced by Ally\PetStore\Api\StoreApi\getOrderByIdAsync().
     {
         $returnType = '\Ally\PetStore\Schema\Order';
         $request = $this->getOrderByIdRequest($order_id);
         return $this->client
             ->sendAsync($request, $this->createHttpClientOption())
             ->then(
                 function ($response) use ($returnType) {
                     if ($returnType === '\SplFileObject') {
                         $content = $response->getBody(); //stream goes to serializer
                     } else {
                         $content = (string) $response->getBody();
                         if ($returnType !== 'string') {
                             $content = json_decode($content);
                         }
                     }
                     return [
                         ObjectSerializer::deserialize($content, $returnType, []),
                         $response->getStatusCode(),
                         $response->getHeaders()
                     ];
                 },
                 function ($exception) {
                     $response = $exception->getResponse();
                     $statusCode = $response->getStatusCode();
                     throw new ApiException(
                         sprintf(
                             '[%d] Error connecting to the API (%s)',
                             $statusCode,
                             $exception->getRequest()->getUri()
                         ),
                         $statusCode,
                         $response->getHeaders(),
                         (string) $response->getBody()
                     );
                 }
             );
     }
getOrderByIdRequest()
Ally\PetStore\Api\StoreApi::getOrderByIdRequest ($order_id)
Create request for operation 'getOrderById'.
Parameters
int $order_id ID of pet that needs to be fetched (required)
Exceptions
Definition at line 808 of file StoreApi.php.
References Ally\PetStore\ObjectSerializer\buildQuery(), and Ally\PetStore\ObjectSerializer\toPathValue().
Referenced by Ally\PetStore\Api\StoreApi\getOrderByIdAsyncWithHttpInfo(), and Ally\PetStore\Api\StoreApi\getOrderByIdWithHttpInfo().
     {
         // verify the required parameter 'order_id' is set
         if ($order_id === null || (is_array($order_id) && count($order_id) === 0)) {
             throw new \InvalidArgumentException(
                 'Missing the required parameter $order_id when calling getOrderById'
             );
         }
         if ($order_id > 5) {
             throw new \InvalidArgumentException('invalid value for "$order_id" when calling StoreApi.getOrderById, must be smaller than or equal to 5.');
         }
         if ($order_id < 1) {
             throw new \InvalidArgumentException('invalid value for "$order_id" when calling StoreApi.getOrderById, must be bigger than or equal to 1.');
         }
         $resourcePath = '/store/order/{orderId}';
         $formParams = [];
         $queryParams = [];
         $headerParams = [];
         $httpBody = '';
         $multipart = false;
         // path params
         if ($order_id !== null) {
             $resourcePath = str_replace(
                 '{' . 'orderId' . '}',
                 ObjectSerializer::toPathValue($order_id),
                 $resourcePath
             );
         }
         if ($multipart) {
             $headers = $this->headerSelector->selectHeadersForMultipart(
                 ['application/xml', 'application/json']
             );
         } else {
             $headers = $this->headerSelector->selectHeaders(
                 ['application/xml', 'application/json'],
                 []
             );
         }
         // for model (json/xml)
         if (count($formParams) > 0) {
             if ($multipart) {
                 $multipartContents = [];
                 foreach ($formParams as $formParamName => $formParamValue) {
                     $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                     foreach ($formParamValueItems as $formParamValueItem) {
                         $multipartContents[] = [
                             'name' => $formParamName,
                             'contents' => $formParamValueItem
                         ];
                     }
                 }
                 // for HTTP post (form)
                 $httpBody = new MultipartStream($multipartContents);
             } elseif ($headers['Content-Type'] === 'application/json') {
                 $httpBody = \GuzzleHttp\json_encode($formParams);
             } else {
                 // for HTTP post (form)
                 $httpBody = ObjectSerializer::buildQuery($formParams);
             }
         }
         $defaultHeaders = [];
         if ($this->config->getUserAgent()) {
             $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
         }
         $headers = array_merge(
             $defaultHeaders,
             $headerParams,
             $headers
         );
         $operationHost = $this->config->getHost();
         $query = ObjectSerializer::buildQuery($queryParams);
         return new Request(
             'GET',
             $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
             $headers,
             $httpBody
         );
     }
getOrderByIdWithHttpInfo()
Ally\PetStore\Api\StoreApi::getOrderByIdWithHttpInfo ($order_id)
Operation getOrderByIdWithHttpInfo.
Find purchase order by ID
Parameters
int $order_id ID of pet that needs to be fetched (required)
Exceptions
Definition at line 641 of file StoreApi.php.
References Ally\PetStore\Api\StoreApi\createHttpClientOption(), Ally\PetStore\Api\StoreApi\getOrderByIdRequest(), Ally\PetStore\ApiException\getResponseBody(), Ally\PetStore\ApiException\getResponseHeaders(), and Ally\PetStore\ApiException\setResponseObject().
Referenced by Ally\PetStore\Api\StoreApi\getOrderById().
     {
         $request = $this->getOrderByIdRequest($order_id);
         try {
             $options = $this->createHttpClientOption();
             try {
                 $response = $this->client->send($request, $options);
             } catch (RequestException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                     $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                 );
             } catch (ConnectException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     null,
                     null
                 );
             }
             $statusCode = $response->getStatusCode();
             if ($statusCode < 200 || $statusCode > 299) {
                 throw new ApiException(
                     sprintf(
                         '[%d] Error connecting to the API (%s)',
                         $statusCode,
                         (string) $request->getUri()
                     ),
                     $statusCode,
                     $response->getHeaders(),
                     (string) $response->getBody()
                 );
             }
             switch($statusCode) {
                 case 200:
                     if ('\Ally\PetStore\Schema\Order' === '\SplFileObject') {
                         $content = $response->getBody(); //stream goes to serializer
                     } else {
                         $content = (string) $response->getBody();
                         if ('\Ally\PetStore\Schema\Order' !== 'string') {
                             $content = json_decode($content);
                         }
                     }
                     return [
                         ObjectSerializer::deserialize($content, '\Ally\PetStore\Schema\Order', []),
                         $response->getStatusCode(),
                         $response->getHeaders()
                     ];
             }
             $returnType = '\Ally\PetStore\Schema\Order';
             if ($returnType === '\SplFileObject') {
                 $content = $response->getBody(); //stream goes to serializer
             } else {
                 $content = (string) $response->getBody();
                 if ($returnType !== 'string') {
                     $content = json_decode($content);
                 }
             }
             return [
                 ObjectSerializer::deserialize($content, $returnType, []),
                 $response->getStatusCode(),
                 $response->getHeaders()
             ];
         } catch (ApiException $e) {
             switch ($e->getCode()) {
                 case 200:
                     $data = ObjectSerializer::deserialize(
                         $e->getResponseBody(),
                         '\Ally\PetStore\Schema\Order',
                         $e->getResponseHeaders()
                     );
                     $e->setResponseObject($data);
                     break;
             }
             throw $e;
         }
     }
placeOrder()
Ally\PetStore\Api\StoreApi::placeOrder ($order)
Operation placeOrder.
Place an order for a pet
Parameters
\Ally\PetStore\Schema\Order $order order placed for purchasing the pet (required)
Exceptions
Definition at line 913 of file StoreApi.php.
References Ally\PetStore\Api\StoreApi\placeOrderWithHttpInfo().
     {
         list($response) = $this->placeOrderWithHttpInfo($order);
         return $response;
     }
placeOrderAsync()
Ally\PetStore\Api\StoreApi::placeOrderAsync ($order)
Operation placeOrderAsync.
Place an order for a pet
Parameters
\Ally\PetStore\Schema\Order $order order placed for purchasing the pet (required)
Exceptions
Definition at line 1028 of file StoreApi.php.
References Ally\PetStore\Api\StoreApi\placeOrderAsyncWithHttpInfo().
     {
         return $this->placeOrderAsyncWithHttpInfo($order)
             ->then(
                 function ($response) {
                     return $response[0];
                 }
             );
     }
placeOrderAsyncWithHttpInfo()
Ally\PetStore\Api\StoreApi::placeOrderAsyncWithHttpInfo ($order)
Operation placeOrderAsyncWithHttpInfo.
Place an order for a pet
Parameters
\Ally\PetStore\Schema\Order $order order placed for purchasing the pet (required)
Exceptions
Definition at line 1048 of file StoreApi.php.
References Ally\PetStore\Api\StoreApi\createHttpClientOption(), and Ally\PetStore\Api\StoreApi\placeOrderRequest().
Referenced by Ally\PetStore\Api\StoreApi\placeOrderAsync().
     {
         $returnType = '\Ally\PetStore\Schema\Order';
         $request = $this->placeOrderRequest($order);
         return $this->client
             ->sendAsync($request, $this->createHttpClientOption())
             ->then(
                 function ($response) use ($returnType) {
                     if ($returnType === '\SplFileObject') {
                         $content = $response->getBody(); //stream goes to serializer
                     } else {
                         $content = (string) $response->getBody();
                         if ($returnType !== 'string') {
                             $content = json_decode($content);
                         }
                     }
                     return [
                         ObjectSerializer::deserialize($content, $returnType, []),
                         $response->getStatusCode(),
                         $response->getHeaders()
                     ];
                 },
                 function ($exception) {
                     $response = $exception->getResponse();
                     $statusCode = $response->getStatusCode();
                     throw new ApiException(
                         sprintf(
                             '[%d] Error connecting to the API (%s)',
                             $statusCode,
                             $exception->getRequest()->getUri()
                         ),
                         $statusCode,
                         $response->getHeaders(),
                         (string) $response->getBody()
                     );
                 }
             );
     }
placeOrderRequest()
Ally\PetStore\Api\StoreApi::placeOrderRequest ($order)
Create request for operation 'placeOrder'.
Parameters
\Ally\PetStore\Schema\Order $order order placed for purchasing the pet (required)
Exceptions
Definition at line 1097 of file StoreApi.php.
References Ally\PetStore\ObjectSerializer\buildQuery(), and Ally\PetStore\ObjectSerializer\sanitizeForSerialization().
Referenced by Ally\PetStore\Api\StoreApi\placeOrderAsyncWithHttpInfo(), and Ally\PetStore\Api\StoreApi\placeOrderWithHttpInfo().
     {
         // verify the required parameter 'order' is set
         if ($order === null || (is_array($order) && count($order) === 0)) {
             throw new \InvalidArgumentException(
                 'Missing the required parameter $order when calling placeOrder'
             );
         }
         $resourcePath = '/store/order';
         $formParams = [];
         $queryParams = [];
         $headerParams = [];
         $httpBody = '';
         $multipart = false;
         if ($multipart) {
             $headers = $this->headerSelector->selectHeadersForMultipart(
                 ['application/xml', 'application/json']
             );
         } else {
             $headers = $this->headerSelector->selectHeaders(
                 ['application/xml', 'application/json'],
                 ['application/json']
             );
         }
         // for model (json/xml)
         if (isset($order)) {
             if ($headers['Content-Type'] === 'application/json') {
                 $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($order));
             } else {
                 $httpBody = $order;
             }
         } elseif (count($formParams) > 0) {
             if ($multipart) {
                 $multipartContents = [];
                 foreach ($formParams as $formParamName => $formParamValue) {
                     $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                     foreach ($formParamValueItems as $formParamValueItem) {
                         $multipartContents[] = [
                             'name' => $formParamName,
                             'contents' => $formParamValueItem
                         ];
                     }
                 }
                 // for HTTP post (form)
                 $httpBody = new MultipartStream($multipartContents);
             } elseif ($headers['Content-Type'] === 'application/json') {
                 $httpBody = \GuzzleHttp\json_encode($formParams);
             } else {
                 // for HTTP post (form)
                 $httpBody = ObjectSerializer::buildQuery($formParams);
             }
         }
         $defaultHeaders = [];
         if ($this->config->getUserAgent()) {
             $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
         }
         $headers = array_merge(
             $defaultHeaders,
             $headerParams,
             $headers
         );
         $operationHost = $this->config->getHost();
         $query = ObjectSerializer::buildQuery($queryParams);
         return new Request(
             'POST',
             $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
             $headers,
             $httpBody
         );
     }
placeOrderWithHttpInfo()
Ally\PetStore\Api\StoreApi::placeOrderWithHttpInfo ($order)
Operation placeOrderWithHttpInfo.
Place an order for a pet
Parameters
\Ally\PetStore\Schema\Order $order order placed for purchasing the pet (required)
Exceptions
Definition at line 930 of file StoreApi.php.
References Ally\PetStore\Api\StoreApi\createHttpClientOption(), Ally\PetStore\ApiException\getResponseBody(), Ally\PetStore\ApiException\getResponseHeaders(), Ally\PetStore\Api\StoreApi\placeOrderRequest(), and Ally\PetStore\ApiException\setResponseObject().
Referenced by Ally\PetStore\Api\StoreApi\placeOrder().
     {
         $request = $this->placeOrderRequest($order);
         try {
             $options = $this->createHttpClientOption();
             try {
                 $response = $this->client->send($request, $options);
             } catch (RequestException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                     $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                 );
             } catch (ConnectException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     null,
                     null
                 );
             }
             $statusCode = $response->getStatusCode();
             if ($statusCode < 200 || $statusCode > 299) {
                 throw new ApiException(
                     sprintf(
                         '[%d] Error connecting to the API (%s)',
                         $statusCode,
                         (string) $request->getUri()
                     ),
                     $statusCode,
                     $response->getHeaders(),
                     (string) $response->getBody()
                 );
             }
             switch($statusCode) {
                 case 200:
                     if ('\Ally\PetStore\Schema\Order' === '\SplFileObject') {
                         $content = $response->getBody(); //stream goes to serializer
                     } else {
                         $content = (string) $response->getBody();
                         if ('\Ally\PetStore\Schema\Order' !== 'string') {
                             $content = json_decode($content);
                         }
                     }
                     return [
                         ObjectSerializer::deserialize($content, '\Ally\PetStore\Schema\Order', []),
                         $response->getStatusCode(),
                         $response->getHeaders()
                     ];
             }
             $returnType = '\Ally\PetStore\Schema\Order';
             if ($returnType === '\SplFileObject') {
                 $content = $response->getBody(); //stream goes to serializer
             } else {
                 $content = (string) $response->getBody();
                 if ($returnType !== 'string') {
                     $content = json_decode($content);
                 }
             }
             return [
                 ObjectSerializer::deserialize($content, $returnType, []),
                 $response->getStatusCode(),
                 $response->getHeaders()
             ];
         } catch (ApiException $e) {
             switch ($e->getCode()) {
                 case 200:
                     $data = ObjectSerializer::deserialize(
                         $e->getResponseBody(),
                         '\Ally\PetStore\Schema\Order',
                         $e->getResponseHeaders()
                     );
                     $e->setResponseObject($data);
                     break;
             }
             throw $e;
         }
     }
setHostIndex()
Ally\PetStore\Api\StoreApi::setHostIndex ($hostIndex)
Set the host index.
Parameters
int $hostIndex Host index (required)
Definition at line 95 of file StoreApi.php.
References Ally\PetStore\Api\StoreApi\$hostIndex.
                                             : void
     {
         $this->hostIndex = $hostIndex;
     }
Member Data Documentation
$client
Ally\PetStore\Api\StoreApi::$client protected
Definition at line 55 of file StoreApi.php.
Referenced by Ally\PetStore\Api\StoreApi\__construct().
$config
Ally\PetStore\Api\StoreApi::$config protected
Definition at line 60 of file StoreApi.php.
Referenced by Ally\PetStore\Api\StoreApi\__construct(), and Ally\PetStore\Api\StoreApi\getConfig().
$headerSelector
Ally\PetStore\Api\StoreApi::$headerSelector protected
Definition at line 65 of file StoreApi.php.
$hostIndex
Ally\PetStore\Api\StoreApi::$hostIndex protected
Definition at line 70 of file StoreApi.php.
Referenced by Ally\PetStore\Api\StoreApi\__construct(), Ally\PetStore\Api\StoreApi\getHostIndex(), and Ally\PetStore\Api\StoreApi\setHostIndex().
The documentation for this class was generated from the following file:
src/Api/StoreApi.php