Ally'sPetStoreAPI: Ally\PetStore\Schema\Category Class Reference
Ally\PetStore\Schema\Category Class Reference
Public Member Functions
isNullableSetToNull (string $property)
Checks if a nullable property is set to null.
getModelName ()
The original name of the model.
__construct (array $data=null)
Constructor.
listInvalidProperties ()
Show all the invalid properties with reasons.
valid ()
Validate all the properties in the model return true if all passed.
getId ()
Gets id.
setId ($id)
Sets id.
getName ()
Gets name.
setName ($name)
Sets name.
offsetExists ($offset)
Returns true if offset exists.
offsetGet ($offset)
Gets offset.
offsetSet ($offset, $value)
Sets value based on offset.
offsetUnset ($offset)
Unsets offset.
jsonSerialize ()
Serializes the object to a value that can be serialized natively by json_encode().
__toString ()
Gets the string presentation of the object.
toHeaderValue ()
Gets a header-safe presentation of the object.
Static Public Member Functions
static openAPITypes ()
Array of property to type mappings.
static openAPIFormats ()
Array of property to format mappings.
static isNullable (string $property)
Checks if a property is nullable.
static static attributeMap ()
Array of attributes where the key is the local name, and the value is the original name.
static setters ()
Array of attributes to setter functions (for deserialization of responses)
static getters ()
Array of attributes to getter functions (for serialization of requests)
Public Attributes
const DISCRIMINATOR = null
Static Protected Member Functions
static openAPINullables ()
Array of nullable properties.
Protected Attributes
array $openAPINullablesSetToNull = []
$container = []
Static Protected Attributes
static $openAPIModelName = 'Category'
static $openAPITypes
static $openAPIFormats
static array $openAPINullables
static $attributeMap
static $setters
static $getters
Private Member Functions
getOpenAPINullablesSetToNull ()
Array of nullable field names deliberately set to null.
setIfExists (string $variableName, array $fields, $defaultValue)
Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the $this->openAPINullablesSetToNull array.
Detailed Description
Definition at line 44 of file Category.php.
Constructor & Destructor Documentation
__construct()
Ally\PetStore\Schema\Category::__construct (array $data = null)
Constructor.
Parameters
mixed[] $data Associated array of property values initializing the model
Definition at line 242 of file Category.php.
References Ally\PetStore\Schema\Category\setIfExists().
     {
         $this->setIfExists('id', $data ?? [], null);
         $this->setIfExists('name', $data ?? [], null);
     }
Member Function Documentation
__toString()
Ally\PetStore\Schema\Category::__toString ()
Gets the string presentation of the object.
Returns
string
Definition at line 428 of file Category.php.
References Ally\PetStore\ObjectSerializer\sanitizeForSerialization().
     {
         return json_encode(
             ObjectSerializer::sanitizeForSerialization($this),
             JSON_PRETTY_PRINT
         );
     }
attributeMap()
static static Ally\PetStore\Schema\Category::attributeMap () static
Array of attributes where the key is the local name, and the value is the original name.
Returns
array
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 193 of file Category.php.
     {
         return self::$attributeMap;
     }
getId()
Ally\PetStore\Schema\Category::getId ()
Gets id.
Returns
int|null
Definition at line 299 of file Category.php.
     {
         return $this->container['id'];
     }
getModelName()
Ally\PetStore\Schema\Category::getModelName ()
The original name of the model.
Returns
string
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 223 of file Category.php.
     {
         return self::$openAPIModelName;
     }
getName()
Ally\PetStore\Schema\Category::getName ()
Gets name.
Returns
string|null
Definition at line 328 of file Category.php.
     {
         return $this->container['name'];
     }
getOpenAPINullablesSetToNull()
Ally\PetStore\Schema\Category::getOpenAPINullablesSetToNull () private
Array of nullable field names deliberately set to null.
Returns
boolean[]
Definition at line 129 of file Category.php.
References Ally\PetStore\Schema\Category\$openAPINullablesSetToNull.
Referenced by Ally\PetStore\Schema\Category\isNullableSetToNull().
                                                    : array
     {
         return $this->openAPINullablesSetToNull;
     }
getters()
static Ally\PetStore\Schema\Category::getters () static
Array of attributes to getter functions (for serialization of requests)
Returns
array
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 213 of file Category.php.
     {
         return self::$getters;
     }
isNullable()
static Ally\PetStore\Schema\Category::isNullable (string $property) static
Checks if a property is nullable.
Parameters
string $property
Returns
bool
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 140 of file Category.php.
                                                        : bool
     {
         return self::openAPINullables()[$property] ?? false;
     }
isNullableSetToNull()
Ally\PetStore\Schema\Category::isNullableSetToNull (string $property)
Checks if a nullable property is set to null.
Parameters
string $property
Returns
bool
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 151 of file Category.php.
References Ally\PetStore\Schema\Category\getOpenAPINullablesSetToNull().
                                                          : bool
     {
         return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
     }
jsonSerialize()
Ally\PetStore\Schema\Category::jsonSerialize ()
Serializes the object to a value that can be serialized natively by json_encode().
mixed Returns data which can be serialized by json_encode(), which is a value of any type other than a resource.
Definition at line 418 of file Category.php.
References Ally\PetStore\ObjectSerializer\sanitizeForSerialization().
     {
        return ObjectSerializer::sanitizeForSerialization($this);
     }
listInvalidProperties()
Ally\PetStore\Schema\Category::listInvalidProperties ()
Show all the invalid properties with reasons.
Returns
array invalid properties with reasons
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 271 of file Category.php.
Referenced by Ally\PetStore\Schema\Category\valid().
     {
         $invalidProperties = [];
         if (!is_null($this->container['name']) && !preg_match("/^[a-zA-Z0-9]+[a-zA-Z0-9\\.\\-_]*[a-zA-Z0-9]+$/", $this->container['name'])) {
             $invalidProperties[] = "invalid value for 'name', must be conform to the pattern /^[a-zA-Z0-9]+[a-zA-Z0-9\\.\\-_]*[a-zA-Z0-9]+$/.";
         }
         return $invalidProperties;
     }
offsetExists()
Ally\PetStore\Schema\Category::offsetExists ($offset)
Returns true if offset exists.
False otherwise.
Parameters
integer $offset Offset
Returns
boolean
Definition at line 363 of file Category.php.
                                          : bool
     {
         return isset($this->container[$offset]);
     }
offsetGet()
Ally\PetStore\Schema\Category::offsetGet ($offset)
Gets offset.
Parameters
integer $offset Offset
Returns
mixed|null
Definition at line 376 of file Category.php.
     {
         return $this->container[$offset] ?? null;
     }
offsetSet()
Ally\PetStore\Schema\Category::offsetSet ($offset, $value)
Sets value based on offset.
Parameters
int | null $offset Offset
mixed $value Value to be set
Returns
void
Definition at line 389 of file Category.php.
                                               : void
     {
         if (is_null($offset)) {
             $this->container[] = $value;
         } else {
             $this->container[$offset] = $value;
         }
     }
offsetUnset()
Ally\PetStore\Schema\Category::offsetUnset ($offset)
Unsets offset.
Parameters
integer $offset Offset
Returns
void
Definition at line 405 of file Category.php.
                                         : void
     {
         unset($this->container[$offset]);
     }
openAPIFormats()
static Ally\PetStore\Schema\Category::openAPIFormats () static
Array of property to format mappings.
Used for (de)serialization
Returns
array
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 109 of file Category.php.
     {
         return self::$openAPIFormats;
     }
openAPINullables()
static Ally\PetStore\Schema\Category::openAPINullables () static protected
Array of nullable properties.
Returns
array
Definition at line 119 of file Category.php.
                                                 : array
     {
         return self::$openAPINullables;
     }
openAPITypes()
static Ally\PetStore\Schema\Category::openAPITypes () static
Array of property to type mappings.
Used for (de)serialization
Returns
array
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 99 of file Category.php.
     {
         return self::$openAPITypes;
     }
setId()
Ally\PetStore\Schema\Category::setId ($id)
Sets id.
Parameters
int | null $id id
Returns
self
Definition at line 311 of file Category.php.
     {
         if (is_null($id)) {
             throw new \InvalidArgumentException('non-nullable id cannot be null');
         }
         $this->container['id'] = $id;
         return $this;
     }
setIfExists()
Ally\PetStore\Schema\Category::setIfExists (string $variableName, array $fields, $defaultValue) private
Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the $this->openAPINullablesSetToNull array.
Parameters
string $variableName
array $fields
mixed $defaultValue
Definition at line 257 of file Category.php.
Referenced by Ally\PetStore\Schema\Category\__construct().
                                                                                     : void
     {
         if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
             $this->openAPINullablesSetToNull[] = $variableName;
         }
         $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
     }
setName()
Ally\PetStore\Schema\Category::setName ($name)
Sets name.
Parameters
string | null $name name
Returns
self
Definition at line 340 of file Category.php.
     {
         if (!is_null($name) && (!preg_match("/^[a-zA-Z0-9]+[a-zA-Z0-9\\.\\-_]*[a-zA-Z0-9]+$/", $name))) {
             throw new \InvalidArgumentException("invalid value for \$name when calling Category., must conform to the pattern /^[a-zA-Z0-9]+[a-zA-Z0-9\\.\\-_]*[a-zA-Z0-9]+$/.");
         }
         if (is_null($name)) {
             throw new \InvalidArgumentException('non-nullable name cannot be null');
         }
         $this->container['name'] = $name;
         return $this;
     }
setters()
static Ally\PetStore\Schema\Category::setters () static
Array of attributes to setter functions (for deserialization of responses)
Returns
array
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 203 of file Category.php.
     {
         return self::$setters;
     }
toHeaderValue()
Ally\PetStore\Schema\Category::toHeaderValue ()
Gets a header-safe presentation of the object.
Returns
string
Definition at line 441 of file Category.php.
References Ally\PetStore\ObjectSerializer\sanitizeForSerialization().
     {
         return json_encode(ObjectSerializer::sanitizeForSerialization($this));
     }
valid()
Ally\PetStore\Schema\Category::valid ()
Validate all the properties in the model return true if all passed.
Returns
bool True if all properties are valid
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 288 of file Category.php.
References Ally\PetStore\Schema\Category\listInvalidProperties().
     {
         return count($this->listInvalidProperties()) === 0;
     }
Member Data Documentation
$attributeMap
Ally\PetStore\Schema\Category::$attributeMap static protected
Initial value:
= [
        'id' => 'id'
Definition at line 162 of file Category.php.
$container
Ally\PetStore\Schema\Category::$container = [] protected
Definition at line 234 of file Category.php.
$getters
Ally\PetStore\Schema\Category::$getters static protected
Initial value:
= [
        'id' => 'getId'
Definition at line 182 of file Category.php.
$openAPIFormats
Ally\PetStore\Schema\Category::$openAPIFormats static protected
Initial value:
= [
        'id' => 'int64'
Definition at line 72 of file Category.php.
$openAPIModelName
Ally\PetStore\Schema\Category::$openAPIModelName = 'Category' static protected
Definition at line 53 of file Category.php.
$openAPINullables
array Ally\PetStore\Schema\Category::$openAPINullables static protected
Initial value:
= [
        'id' => false
Definition at line 82 of file Category.php.
$openAPINullablesSetToNull
array Ally\PetStore\Schema\Category::$openAPINullablesSetToNull = [] protected
Definition at line 92 of file Category.php.
Referenced by Ally\PetStore\Schema\Category\getOpenAPINullablesSetToNull().
$openAPITypes
Ally\PetStore\Schema\Category::$openAPITypes static protected
Initial value:
= [
        'id' => 'int'
Definition at line 60 of file Category.php.
$setters
Ally\PetStore\Schema\Category::$setters static protected
Initial value:
= [
        'id' => 'setId'
Definition at line 172 of file Category.php.
DISCRIMINATOR
const Ally\PetStore\Schema\Category::DISCRIMINATOR = null
Definition at line 46 of file Category.php.
The documentation for this class was generated from the following file:
src/Schema/Category.php