Ally'sPetStoreAPI: Ally\PetStore\ObjectSerializer Class Reference
Ally\PetStore\ObjectSerializer Class Reference
Static Public Member Functions
static setDateTimeFormat ($format)
Change the date format.
static sanitizeForSerialization ($data, $type=null, $format=null)
Serialize data.
static sanitizeFilename ($filename)
Sanitize filename by removing path.
static sanitizeTimestamp ($timestamp)
Shorter timestamp microseconds to 6 digits length.
static toPathValue ($value)
Take value and turn it into a string suitable for inclusion in the path, by url-encoding.
static toQueryValue ($value, string $paramName, string $openApiType='string', string $style='form', bool $explode=true, bool $required=true)
Take query parameter properties and turn it into an array suitable for native http_build_query or GuzzleHttp::build.
static convertBoolToQueryStringFormat (bool $value)
Convert boolean value to format for query string.
static toHeaderValue ($value)
Take value and turn it into a string suitable for inclusion in the header.
static toFormValue ($value)
Take value and turn it into a string suitable for inclusion in the http body (form parameter).
static toString ($value)
Take value and turn it into a string suitable for inclusion in the parameter.
static serializeCollection (array $collection, $style, $allowCollectionFormatMulti=false)
Serialize an array to a string.
static buildQuery ($data, string $numeric_prefix='', ?string $arg_separator=null, int $encoding_type=\PHP_QUERY_RFC3986)
Native http_build_query wrapper.
Static Private Attributes
static $dateTimeFormat = \DateTime::ATOM
Detailed Description
Definition at line 42 of file ObjectSerializer.php.
Member Function Documentation
buildQuery()
static Ally\PetStore\ObjectSerializer::buildQuery ($data, string $numeric_prefix = '', ?string $arg_separator = null, int $encoding_type = \PHP_QUERY_RFC3986) static
Native http_build_query wrapper.
See also
https://www.php.net/manual/en/function.http-build-query
Parameters
array | object $data May be an array or object containing properties.
string $numeric_prefix If numeric indices are used in the base array and this parameter is provided, it will be prepended to the numeric index for elements in the base array only.
string | null $arg_separator arg_separator.output is used to separate arguments but may be overridden by specifying this parameter.
int $encoding_type Encoding type. By default, PHP_QUERY_RFC1738.
Returns
string
Definition at line 509 of file ObjectSerializer.php.
Referenced by Ally\PetStore\Api\PetApi\addPetRequest(), Ally\PetStore\Api\UserApi\createUserRequest(), Ally\PetStore\Api\UserApi\createUsersWithArrayInputRequest(), Ally\PetStore\Api\UserApi\createUsersWithListInputRequest(), Ally\PetStore\Api\StoreApi\deleteOrderRequest(), Ally\PetStore\Api\PetApi\deletePetRequest(), Ally\PetStore\Api\UserApi\deleteUserRequest(), Ally\PetStore\Api\PetApi\findPetsByStatusRequest(), Ally\PetStore\Api\PetApi\findPetsByTagsRequest(), Ally\PetStore\Api\StoreApi\getInventoryRequest(), Ally\PetStore\Api\StoreApi\getOrderByIdRequest(), Ally\PetStore\Api\PetApi\getPetByIdRequest(), Ally\PetStore\Api\UserApi\getUserByNameRequest(), Ally\PetStore\Api\UserApi\loginUserRequest(), Ally\PetStore\Api\UserApi\logoutUserRequest(), Ally\PetStore\Api\StoreApi\placeOrderRequest(), Ally\PetStore\Api\PetApi\updatePetRequest(), Ally\PetStore\Api\PetApi\updatePetWithFormRequest(), Ally\PetStore\Api\UserApi\updateUserRequest(), and Ally\PetStore\Api\PetApi\uploadFileRequest().
      : string {
         return \GuzzleHttp\Psr7\Query::build($data, $encoding_type);
     }
convertBoolToQueryStringFormat()
static Ally\PetStore\ObjectSerializer::convertBoolToQueryStringFormat (bool $value) static
Convert boolean value to format for query string.
Parameters
bool $value Boolean value
Returns
int|string Boolean value in format
Definition at line 239 of file ObjectSerializer.php.
References Ally\PetStore\Configuration\BOOLEAN_FORMAT_STRING, and Ally\PetStore\Configuration\getDefaultConfiguration().
     {
         if (Configuration::BOOLEAN_FORMAT_STRING == Configuration::getDefaultConfiguration()->getBooleanFormatForQueryString()) {
             return $value ? 'true' : 'false';
         }
         return (int) $value;
     }
sanitizeFilename()
static Ally\PetStore\ObjectSerializer::sanitizeFilename ($filename) static
Sanitize filename by removing path.
e.g. ../../sun.gif becomes sun.gif
Parameters
string $filename filename to be sanitized
Returns
string the sanitized filename
Definition at line 124 of file ObjectSerializer.php.
     {
         if (preg_match("/.*[\/\\\\](.*)$/", $filename, $match)) {
             return $match[1];
         } else {
             return $filename;
         }
     }
sanitizeForSerialization()
static Ally\PetStore\ObjectSerializer::sanitizeForSerialization ($data, $type = null, $format = null) static
Serialize data.
Parameters
mixed $data the data to serialize
string $type the OpenAPIToolsType of the data
string $format the format of the OpenAPITools type of the data
Returns
scalar|object|array|null serialized form of $data
array $callable
Definition at line 66 of file ObjectSerializer.php.
Referenced by Ally\PetStore\Schema\Tag\__toString(), Ally\PetStore\Schema\Category\__toString(), Ally\PetStore\Schema\ApiResponse\__toString(), Ally\PetStore\Schema\Order\__toString(), Ally\PetStore\Schema\Pet\__toString(), Ally\PetStore\Schema\User\__toString(), Ally\PetStore\Api\PetApi\addPetRequest(), Ally\PetStore\Api\UserApi\createUserRequest(), Ally\PetStore\Api\UserApi\createUsersWithArrayInputRequest(), Ally\PetStore\Api\UserApi\createUsersWithListInputRequest(), Ally\PetStore\Schema\Tag\jsonSerialize(), Ally\PetStore\Schema\Category\jsonSerialize(), Ally\PetStore\Schema\ApiResponse\jsonSerialize(), Ally\PetStore\Schema\Order\jsonSerialize(), Ally\PetStore\Schema\Pet\jsonSerialize(), Ally\PetStore\Schema\User\jsonSerialize(), Ally\PetStore\Api\StoreApi\placeOrderRequest(), Ally\PetStore\Schema\Tag\toHeaderValue(), Ally\PetStore\Schema\Category\toHeaderValue(), Ally\PetStore\Schema\ApiResponse\toHeaderValue(), Ally\PetStore\Schema\Order\toHeaderValue(), Ally\PetStore\Schema\Pet\toHeaderValue(), Ally\PetStore\Schema\User\toHeaderValue(), Ally\PetStore\Api\PetApi\updatePetRequest(), and Ally\PetStore\Api\UserApi\updateUserRequest().
     {
         if (is_scalar($data) || null === $data) {
             return $data;
         }
         if ($data instanceof \DateTime) {
             return ($format === 'date') ? $data->format('Y-m-d') : $data->format(self::$dateTimeFormat);
         }
         if (is_array($data)) {
             foreach ($data as $property => $value) {
                 $data[$property] = self::sanitizeForSerialization($value);
             }
             return $data;
         }
         if (is_object($data)) {
             $values = [];
             if ($data instanceof ModelInterface) {
                 $formats = $data::openAPIFormats();
                 foreach ($data::openAPITypes() as $property => $openAPIType) {
                     $getter = $data::getters()[$property];
                     $value = $data->$getter();
                     if ($value !== null && !in_array($openAPIType, ['\DateTime', '\SplFileObject', 'array', 'bool', 'boolean', 'byte', 'double', 'float', 'int', 'integer', 'mixed', 'number', 'object', 'string', 'void'], true)) {
                         $callable = [$openAPIType, 'getAllowableEnumValues'];
                         if (is_callable($callable)) {
                             /** array $callable */
                             $allowedEnumTypes = $callable();
                             if (!in_array($value, $allowedEnumTypes, true)) {
                                 $imploded = implode("', '", $allowedEnumTypes);
                                 throw new \InvalidArgumentException("Invalid value for enum '$openAPIType', must be one of: '$imploded'");
                             }
                         }
                     }
                     if (($data::isNullable($property) && $data->isNullableSetToNull($property)) || $value !== null) {
                         $values[$data::attributeMap()[$property]] = self::sanitizeForSerialization($value, $openAPIType, $formats[$property]);
                     }
                 }
             } else {
                 foreach($data as $property => $value) {
                     $values[$property] = self::sanitizeForSerialization($value);
                 }
             }
             return (object)$values;
         } else {
             return (string)$data;
         }
     }
sanitizeTimestamp()
static Ally\PetStore\ObjectSerializer::sanitizeTimestamp ($timestamp) static
Shorter timestamp microseconds to 6 digits length.
Parameters
string $timestamp Original timestamp
Returns
string the shorten timestamp
Definition at line 140 of file ObjectSerializer.php.
     {
         if (!is_string($timestamp)) return $timestamp;
         return preg_replace('/(:\d{2}.\d{6})\d*/', '$1', $timestamp);
     }
serializeCollection()
static Ally\PetStore\ObjectSerializer::serializeCollection (array $collection, $style, $allowCollectionFormatMulti = false) static
Serialize an array to a string.
Parameters
array $collection collection to serialize to a string
string $style the format use for serialization (csv, ssv, tsv, pipes, multi)
bool $allowCollectionFormatMulti allow collection format to be a multidimensional array
Returns
string
Definition at line 316 of file ObjectSerializer.php.
References Ally\PetStore\Configuration\getDefaultConfiguration().
     {
         if ($allowCollectionFormatMulti && ('multi' === $style)) {
             // http_build_query() almost does the job for us. We just
             // need to fix the result of multidimensional arrays.
             return preg_replace('/%5B[0-9]+%5D=/', '=', http_build_query($collection, '', '&'));
         }
         switch ($style) {
             case 'pipeDelimited':
             case 'pipes':
                 return implode('|', $collection);
             case 'tsv':
                 return implode("\t", $collection);
             case 'spaceDelimited':
             case 'ssv':
                 return implode(' ', $collection);
             case 'simple':
             case 'csv':
                 // Deliberate fall through. CSV is default format.
             default:
                 return implode(',', $collection);
         }
     }
setDateTimeFormat()
static Ally\PetStore\ObjectSerializer::setDateTimeFormat ($format) static
Change the date format.
Parameters
string $format the new date format to use
Definition at line 52 of file ObjectSerializer.php.
     {
         self::$dateTimeFormat = $format;
     }
toFormValue()
static Ally\PetStore\ObjectSerializer::toFormValue ($value) static
Take value and turn it into a string suitable for inclusion in the http body (form parameter).
If it's a string, pass through unchanged If it's a datetime object, format it in ISO8601
Parameters
string | \SplFileObject $value the value of the form parameter
Returns
string the form string
Definition at line 276 of file ObjectSerializer.php.
Referenced by Ally\PetStore\Api\PetApi\updatePetWithFormRequest(), and Ally\PetStore\Api\PetApi\uploadFileRequest().
     {
         if ($value instanceof \SplFileObject) {
             return $value->getRealPath();
         } else {
             return self::toString($value);
         }
     }
toHeaderValue()
static Ally\PetStore\ObjectSerializer::toHeaderValue ($value) static
Take value and turn it into a string suitable for inclusion in the header.
If it's a string, pass through unchanged If it's a datetime object, format it in ISO8601
Parameters
string $value a string which will be part of the header
Returns
string the header string
Definition at line 257 of file ObjectSerializer.php.
Referenced by Ally\PetStore\Api\PetApi\deletePetRequest().
     {
         $callable = [$value, 'toHeaderValue'];
         if (is_callable($callable)) {
             return $callable();
         }
         return self::toString($value);
     }
toPathValue()
static Ally\PetStore\ObjectSerializer::toPathValue ($value) static
Take value and turn it into a string suitable for inclusion in the path, by url-encoding.
Parameters
string $value a string which will be part of the path
Returns
string the serialized object
Definition at line 155 of file ObjectSerializer.php.
Referenced by Ally\PetStore\Api\StoreApi\deleteOrderRequest(), Ally\PetStore\Api\PetApi\deletePetRequest(), Ally\PetStore\Api\UserApi\deleteUserRequest(), Ally\PetStore\Api\StoreApi\getOrderByIdRequest(), Ally\PetStore\Api\PetApi\getPetByIdRequest(), Ally\PetStore\Api\UserApi\getUserByNameRequest(), Ally\PetStore\Api\PetApi\updatePetWithFormRequest(), Ally\PetStore\Api\UserApi\updateUserRequest(), and Ally\PetStore\Api\PetApi\uploadFileRequest().
     {
         return rawurlencode(self::toString($value));
     }
toQueryValue()
static Ally\PetStore\ObjectSerializer::toQueryValue ($value, string $paramName, string $openApiType = 'string', string $style = 'form', bool $explode = true, bool $required = true) static
Take query parameter properties and turn it into an array suitable for native http_build_query or GuzzleHttp::build.
Parameters
mixed $value Parameter value
string $paramName Parameter name
string $openApiType OpenAPIType eg. array or object
string $style Parameter serialization style
bool $explode Parameter explode option
bool $required Whether query param is required or not
Returns
array
Definition at line 173 of file ObjectSerializer.php.
Referenced by Ally\PetStore\Api\PetApi\findPetsByStatusRequest(), Ally\PetStore\Api\PetApi\findPetsByTagsRequest(), and Ally\PetStore\Api\UserApi\loginUserRequest().
      : array {
         if (
             empty($value)
             && ($value !== false || $openApiType !== 'boolean') // if $value === false and $openApiType ==='boolean' it isn't empty
         ) {
             if ($required) {
                 return ["{$paramName}" => ''];
             } else {
                 return [];
             }
         }
         $query = [];
         $value = (in_array($openApiType, ['object', 'array'], true)) ? (array)$value : $value;
         // since \GuzzleHttp\Psr7\Query::build fails with nested arrays
         // need to flatten array first
         $flattenArray = function ($arr, $name, &$result = []) use (&$flattenArray, $style, $explode) {
             if (!is_array($arr)) return $arr;
             foreach ($arr as $k => $v) {
                 $prop = ($style === 'deepObject') ? $prop = "{$name}[{$k}]" : $k;
                 if (is_array($v)) {
                     $flattenArray($v, $prop, $result);
                 } else {
                     if ($style !== 'deepObject' && !$explode) {
                         // push key itself
                         $result[] = $prop;
                     }
                     $result[$prop] = $v;
                 }
             }
             return $result;
         };
         $value = $flattenArray($value, $paramName);
         if ($openApiType === 'object' && ($style === 'deepObject' || $explode)) {
             return $value;
         }
         if ('boolean' === $openApiType && is_bool($value)) {
             $value = self::convertBoolToQueryStringFormat($value);
         }
         // handle style in serializeCollection
         $query[$paramName] = ($explode) ? $value : self::serializeCollection((array)$value, $style);
         return $query;
     }
toString()
static Ally\PetStore\ObjectSerializer::toString ($value) static
Take value and turn it into a string suitable for inclusion in the parameter.
If it's a string, pass through unchanged If it's a datetime object, format it in ISO8601 If it's a boolean, convert it to "true" or "false".
Parameters
string | bool | \DateTime $value the value of the parameter
Returns
string the header string
Definition at line 295 of file ObjectSerializer.php.
     {
         if ($value instanceof \DateTime) { // datetime in ISO8601 format
             return $value->format(self::$dateTimeFormat);
         } elseif (is_bool($value)) {
             return $value ? 'true' : 'false';
         } else {
             return (string) $value;
         }
     }
Member Data Documentation
$dateTimeFormat
Ally\PetStore\ObjectSerializer::$dateTimeFormat = \DateTime::ATOM static private
Definition at line 45 of file ObjectSerializer.php.
The documentation for this class was generated from the following file:
src/ObjectSerializer.php