Ally'sPetStoreAPI: Ally\PetStore\Api\PetApi Class Reference
Ally\PetStore\Api\PetApi Class Reference
Public Member Functions
__construct (ClientInterface $client=null, Configuration $config=null, HeaderSelector $selector=null, $hostIndex=0)
setHostIndex ($hostIndex)
Set the host index.
getHostIndex ()
Get the host index.
getConfig ()
addPet ($pet)
Operation addPet.
addPetWithHttpInfo ($pet)
Operation addPetWithHttpInfo.
addPetAsync ($pet)
Operation addPetAsync.
addPetAsyncWithHttpInfo ($pet)
Operation addPetAsyncWithHttpInfo.
addPetRequest ($pet)
Create request for operation 'addPet'.
deletePet ($pet_id, $api_key=null)
Operation deletePet.
deletePetWithHttpInfo ($pet_id, $api_key=null)
Operation deletePetWithHttpInfo.
deletePetAsync ($pet_id, $api_key=null)
Operation deletePetAsync.
deletePetAsyncWithHttpInfo ($pet_id, $api_key=null)
Operation deletePetAsyncWithHttpInfo.
deletePetRequest ($pet_id, $api_key=null)
Create request for operation 'deletePet'.
findPetsByStatus ($status)
Operation findPetsByStatus.
findPetsByStatusWithHttpInfo ($status)
Operation findPetsByStatusWithHttpInfo.
findPetsByStatusAsync ($status)
Operation findPetsByStatusAsync.
findPetsByStatusAsyncWithHttpInfo ($status)
Operation findPetsByStatusAsyncWithHttpInfo.
findPetsByStatusRequest ($status)
Create request for operation 'findPetsByStatus'.
findPetsByTags ($tags)
Operation findPetsByTags.
findPetsByTagsWithHttpInfo ($tags)
Operation findPetsByTagsWithHttpInfo.
findPetsByTagsAsync ($tags)
Operation findPetsByTagsAsync.
findPetsByTagsAsyncWithHttpInfo ($tags)
Operation findPetsByTagsAsyncWithHttpInfo.
findPetsByTagsRequest ($tags)
Create request for operation 'findPetsByTags'.
getPetById ($pet_id)
Operation getPetById.
getPetByIdWithHttpInfo ($pet_id)
Operation getPetByIdWithHttpInfo.
getPetByIdAsync ($pet_id)
Operation getPetByIdAsync.
getPetByIdAsyncWithHttpInfo ($pet_id)
Operation getPetByIdAsyncWithHttpInfo.
getPetByIdRequest ($pet_id)
Create request for operation 'getPetById'.
updatePet ($pet)
Operation updatePet.
updatePetWithHttpInfo ($pet)
Operation updatePetWithHttpInfo.
updatePetAsync ($pet)
Operation updatePetAsync.
updatePetAsyncWithHttpInfo ($pet)
Operation updatePetAsyncWithHttpInfo.
updatePetRequest ($pet)
Create request for operation 'updatePet'.
updatePetWithForm ($pet_id, $name=null, $status=null)
Operation updatePetWithForm.
updatePetWithFormWithHttpInfo ($pet_id, $name=null, $status=null)
Operation updatePetWithFormWithHttpInfo.
updatePetWithFormAsync ($pet_id, $name=null, $status=null)
Operation updatePetWithFormAsync.
updatePetWithFormAsyncWithHttpInfo ($pet_id, $name=null, $status=null)
Operation updatePetWithFormAsyncWithHttpInfo.
updatePetWithFormRequest ($pet_id, $name=null, $status=null)
Create request for operation 'updatePetWithForm'.
uploadFile ($pet_id, $additional_metadata=null, $file=null)
Operation uploadFile.
uploadFileWithHttpInfo ($pet_id, $additional_metadata=null, $file=null)
Operation uploadFileWithHttpInfo.
uploadFileAsync ($pet_id, $additional_metadata=null, $file=null)
Operation uploadFileAsync.
uploadFileAsyncWithHttpInfo ($pet_id, $additional_metadata=null, $file=null)
Operation uploadFileAsyncWithHttpInfo.
uploadFileRequest ($pet_id, $additional_metadata=null, $file=null)
Create request for operation 'uploadFile'.
Protected Member Functions
createHttpClientOption ()
Create http client option.
Protected Attributes
$client
$config
$headerSelector
$hostIndex
Detailed Description
Definition at line 50 of file PetApi.php.
Constructor & Destructor Documentation
__construct()
Ally\PetStore\Api\PetApi::__construct (ClientInterface $client = null, Configuration $config = null, HeaderSelector $selector = null, $hostIndex = 0)
Parameters
ClientInterface $client
Configuration $config
HeaderSelector $selector
int $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
Definition at line 78 of file PetApi.php.
References Ally\PetStore\Api\PetApi\$client, Ally\PetStore\Api\PetApi\$config, and Ally\PetStore\Api\PetApi\$hostIndex.
       {
         $this->client = $client ?: new Client();
         $this->config = $config ?: new Configuration();
         $this->headerSelector = $selector ?: new HeaderSelector();
         $this->hostIndex = $hostIndex;
     }
Member Function Documentation
addPet()
Ally\PetStore\Api\PetApi::addPet ($pet)
Operation addPet.
Add a new pet to the store
Parameters
\Ally\PetStore\Schema\Pet $pet Pet object that needs to be added to the store (required)
Exceptions
Definition at line 129 of file PetApi.php.
References Ally\PetStore\Api\PetApi\addPetWithHttpInfo().
     {
         list($response) = $this->addPetWithHttpInfo($pet);
         return $response;
     }
addPetAsync()
Ally\PetStore\Api\PetApi::addPetAsync ($pet)
Operation addPetAsync.
Add a new pet to the store
Parameters
\Ally\PetStore\Schema\Pet $pet Pet object that needs to be added to the store (required)
Exceptions
Definition at line 244 of file PetApi.php.
References Ally\PetStore\Api\PetApi\addPetAsyncWithHttpInfo().
     {
         return $this->addPetAsyncWithHttpInfo($pet)
             ->then(
                 function ($response) {
                     return $response[0];
                 }
             );
     }
addPetAsyncWithHttpInfo()
Ally\PetStore\Api\PetApi::addPetAsyncWithHttpInfo ($pet)
Operation addPetAsyncWithHttpInfo.
Add a new pet to the store
Parameters
\Ally\PetStore\Schema\Pet $pet Pet object that needs to be added to the store (required)
Exceptions
Definition at line 264 of file PetApi.php.
References Ally\PetStore\Api\PetApi\addPetRequest(), and Ally\PetStore\Api\PetApi\createHttpClientOption().
Referenced by Ally\PetStore\Api\PetApi\addPetAsync().
     {
         $returnType = '\Ally\PetStore\Schema\Pet';
         $request = $this->addPetRequest($pet);
         return $this->client
             ->sendAsync($request, $this->createHttpClientOption())
             ->then(
                 function ($response) use ($returnType) {
                     if ($returnType === '\SplFileObject') {
                         $content = $response->getBody(); //stream goes to serializer
                     } else {
                         $content = (string) $response->getBody();
                         if ($returnType !== 'string') {
                             $content = json_decode($content);
                         }
                     }
                     return [
                         ObjectSerializer::deserialize($content, $returnType, []),
                         $response->getStatusCode(),
                         $response->getHeaders()
                     ];
                 },
                 function ($exception) {
                     $response = $exception->getResponse();
                     $statusCode = $response->getStatusCode();
                     throw new ApiException(
                         sprintf(
                             '[%d] Error connecting to the API (%s)',
                             $statusCode,
                             $exception->getRequest()->getUri()
                         ),
                         $statusCode,
                         $response->getHeaders(),
                         (string) $response->getBody()
                     );
                 }
             );
     }
addPetRequest()
Ally\PetStore\Api\PetApi::addPetRequest ($pet)
Create request for operation 'addPet'.
Parameters
\Ally\PetStore\Schema\Pet $pet Pet object that needs to be added to the store (required)
Exceptions
Definition at line 313 of file PetApi.php.
References Ally\PetStore\ObjectSerializer\buildQuery(), and Ally\PetStore\ObjectSerializer\sanitizeForSerialization().
Referenced by Ally\PetStore\Api\PetApi\addPetAsyncWithHttpInfo(), and Ally\PetStore\Api\PetApi\addPetWithHttpInfo().
     {
         // verify the required parameter 'pet' is set
         if ($pet === null || (is_array($pet) && count($pet) === 0)) {
             throw new \InvalidArgumentException(
                 'Missing the required parameter $pet when calling addPet'
             );
         }
         $resourcePath = '/pet';
         $formParams = [];
         $queryParams = [];
         $headerParams = [];
         $httpBody = '';
         $multipart = false;
         if ($multipart) {
             $headers = $this->headerSelector->selectHeadersForMultipart(
                 ['application/xml', 'application/json']
             );
         } else {
             $headers = $this->headerSelector->selectHeaders(
                 ['application/xml', 'application/json'],
                 ['application/json', 'application/xml']
             );
         }
         // for model (json/xml)
         if (isset($pet)) {
             if ($headers['Content-Type'] === 'application/json') {
                 $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($pet));
             } else {
                 $httpBody = $pet;
             }
         } elseif (count($formParams) > 0) {
             if ($multipart) {
                 $multipartContents = [];
                 foreach ($formParams as $formParamName => $formParamValue) {
                     $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                     foreach ($formParamValueItems as $formParamValueItem) {
                         $multipartContents[] = [
                             'name' => $formParamName,
                             'contents' => $formParamValueItem
                         ];
                     }
                 }
                 // for HTTP post (form)
                 $httpBody = new MultipartStream($multipartContents);
             } elseif ($headers['Content-Type'] === 'application/json') {
                 $httpBody = \GuzzleHttp\json_encode($formParams);
             } else {
                 // for HTTP post (form)
                 $httpBody = ObjectSerializer::buildQuery($formParams);
             }
         }
         // this endpoint requires OAuth (access token)
         if (!empty($this->config->getAccessToken())) {
             $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
         }
         $defaultHeaders = [];
         if ($this->config->getUserAgent()) {
             $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
         }
         $headers = array_merge(
             $defaultHeaders,
             $headerParams,
             $headers
         );
         $operationHost = $this->config->getHost();
         $query = ObjectSerializer::buildQuery($queryParams);
         return new Request(
             'POST',
             $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
             $headers,
             $httpBody
         );
     }
addPetWithHttpInfo()
Ally\PetStore\Api\PetApi::addPetWithHttpInfo ($pet)
Operation addPetWithHttpInfo.
Add a new pet to the store
Parameters
\Ally\PetStore\Schema\Pet $pet Pet object that needs to be added to the store (required)
Exceptions
Definition at line 146 of file PetApi.php.
References Ally\PetStore\Api\PetApi\addPetRequest(), Ally\PetStore\Api\PetApi\createHttpClientOption(), Ally\PetStore\ApiException\getResponseBody(), Ally\PetStore\ApiException\getResponseHeaders(), and Ally\PetStore\ApiException\setResponseObject().
Referenced by Ally\PetStore\Api\PetApi\addPet().
     {
         $request = $this->addPetRequest($pet);
         try {
             $options = $this->createHttpClientOption();
             try {
                 $response = $this->client->send($request, $options);
             } catch (RequestException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                     $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                 );
             } catch (ConnectException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     null,
                     null
                 );
             }
             $statusCode = $response->getStatusCode();
             if ($statusCode < 200 || $statusCode > 299) {
                 throw new ApiException(
                     sprintf(
                         '[%d] Error connecting to the API (%s)',
                         $statusCode,
                         (string) $request->getUri()
                     ),
                     $statusCode,
                     $response->getHeaders(),
                     (string) $response->getBody()
                 );
             }
             switch($statusCode) {
                 case 200:
                     if ('\Ally\PetStore\Schema\Pet' === '\SplFileObject') {
                         $content = $response->getBody(); //stream goes to serializer
                     } else {
                         $content = (string) $response->getBody();
                         if ('\Ally\PetStore\Schema\Pet' !== 'string') {
                             $content = json_decode($content);
                         }
                     }
                     return [
                         ObjectSerializer::deserialize($content, '\Ally\PetStore\Schema\Pet', []),
                         $response->getStatusCode(),
                         $response->getHeaders()
                     ];
             }
             $returnType = '\Ally\PetStore\Schema\Pet';
             if ($returnType === '\SplFileObject') {
                 $content = $response->getBody(); //stream goes to serializer
             } else {
                 $content = (string) $response->getBody();
                 if ($returnType !== 'string') {
                     $content = json_decode($content);
                 }
             }
             return [
                 ObjectSerializer::deserialize($content, $returnType, []),
                 $response->getStatusCode(),
                 $response->getHeaders()
             ];
         } catch (ApiException $e) {
             switch ($e->getCode()) {
                 case 200:
                     $data = ObjectSerializer::deserialize(
                         $e->getResponseBody(),
                         '\Ally\PetStore\Schema\Pet',
                         $e->getResponseHeaders()
                     );
                     $e->setResponseObject($data);
                     break;
             }
             throw $e;
         }
     }
createHttpClientOption()
Ally\PetStore\Api\PetApi::createHttpClientOption () protected
Create http client option.
Exceptions
Definition at line 2366 of file PetApi.php.
Referenced by Ally\PetStore\Api\PetApi\addPetAsyncWithHttpInfo(), Ally\PetStore\Api\PetApi\addPetWithHttpInfo(), Ally\PetStore\Api\PetApi\deletePetAsyncWithHttpInfo(), Ally\PetStore\Api\PetApi\deletePetWithHttpInfo(), Ally\PetStore\Api\PetApi\findPetsByStatusAsyncWithHttpInfo(), Ally\PetStore\Api\PetApi\findPetsByStatusWithHttpInfo(), Ally\PetStore\Api\PetApi\findPetsByTagsAsyncWithHttpInfo(), Ally\PetStore\Api\PetApi\findPetsByTagsWithHttpInfo(), Ally\PetStore\Api\PetApi\getPetByIdAsyncWithHttpInfo(), Ally\PetStore\Api\PetApi\getPetByIdWithHttpInfo(), Ally\PetStore\Api\PetApi\updatePetAsyncWithHttpInfo(), Ally\PetStore\Api\PetApi\updatePetWithFormAsyncWithHttpInfo(), Ally\PetStore\Api\PetApi\updatePetWithFormWithHttpInfo(), Ally\PetStore\Api\PetApi\updatePetWithHttpInfo(), Ally\PetStore\Api\PetApi\uploadFileAsyncWithHttpInfo(), and Ally\PetStore\Api\PetApi\uploadFileWithHttpInfo().
     {
         $options = [];
         if ($this->config->getDebug()) {
             $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
             if (!$options[RequestOptions::DEBUG]) {
                 throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
             }
         }
         return $options;
     }
deletePet()
Ally\PetStore\Api\PetApi::deletePet ($pet_id, $api_key = null)
Operation deletePet.
Deletes a pet
Parameters
int $pet_id Pet id to delete (required)
string $api_key api_key (optional)
Exceptions
Definition at line 414 of file PetApi.php.
References Ally\PetStore\Api\PetApi\deletePetWithHttpInfo().
     {
         $this->deletePetWithHttpInfo($pet_id, $api_key);
     }
deletePetAsync()
Ally\PetStore\Api\PetApi::deletePetAsync ($pet_id, $api_key = null)
Operation deletePetAsync.
Deletes a pet
Parameters
int $pet_id Pet id to delete (required)
string $api_key (optional)
Exceptions
Definition at line 490 of file PetApi.php.
References Ally\PetStore\Api\PetApi\deletePetAsyncWithHttpInfo().
     {
         return $this->deletePetAsyncWithHttpInfo($pet_id, $api_key)
             ->then(
                 function ($response) {
                     return $response[0];
                 }
             );
     }
deletePetAsyncWithHttpInfo()
Ally\PetStore\Api\PetApi::deletePetAsyncWithHttpInfo ($pet_id, $api_key = null)
Operation deletePetAsyncWithHttpInfo.
Deletes a pet
Parameters
int $pet_id Pet id to delete (required)
string $api_key (optional)
Exceptions
Definition at line 511 of file PetApi.php.
References Ally\PetStore\Api\PetApi\createHttpClientOption(), and Ally\PetStore\Api\PetApi\deletePetRequest().
Referenced by Ally\PetStore\Api\PetApi\deletePetAsync().
     {
         $returnType = '';
         $request = $this->deletePetRequest($pet_id, $api_key);
         return $this->client
             ->sendAsync($request, $this->createHttpClientOption())
             ->then(
                 function ($response) use ($returnType) {
                     return [null, $response->getStatusCode(), $response->getHeaders()];
                 },
                 function ($exception) {
                     $response = $exception->getResponse();
                     $statusCode = $response->getStatusCode();
                     throw new ApiException(
                         sprintf(
                             '[%d] Error connecting to the API (%s)',
                             $statusCode,
                             $exception->getRequest()->getUri()
                         ),
                         $statusCode,
                         $response->getHeaders(),
                         (string) $response->getBody()
                     );
                 }
             );
     }
deletePetRequest()
Ally\PetStore\Api\PetApi::deletePetRequest ($pet_id, $api_key = null)
Create request for operation 'deletePet'.
Parameters
int $pet_id Pet id to delete (required)
string $api_key (optional)
Exceptions
Definition at line 548 of file PetApi.php.
References Ally\PetStore\ObjectSerializer\buildQuery(), Ally\PetStore\ObjectSerializer\toHeaderValue(), and Ally\PetStore\ObjectSerializer\toPathValue().
Referenced by Ally\PetStore\Api\PetApi\deletePetAsyncWithHttpInfo(), and Ally\PetStore\Api\PetApi\deletePetWithHttpInfo().
     {
         // verify the required parameter 'pet_id' is set
         if ($pet_id === null || (is_array($pet_id) && count($pet_id) === 0)) {
             throw new \InvalidArgumentException(
                 'Missing the required parameter $pet_id when calling deletePet'
             );
         }
         $resourcePath = '/pet/{petId}';
         $formParams = [];
         $queryParams = [];
         $headerParams = [];
         $httpBody = '';
         $multipart = false;
         // header params
         if ($api_key !== null) {
             $headerParams['api_key'] = ObjectSerializer::toHeaderValue($api_key);
         }
         // path params
         if ($pet_id !== null) {
             $resourcePath = str_replace(
                 '{' . 'petId' . '}',
                 ObjectSerializer::toPathValue($pet_id),
                 $resourcePath
             );
         }
         if ($multipart) {
             $headers = $this->headerSelector->selectHeadersForMultipart(
                 []
             );
         } else {
             $headers = $this->headerSelector->selectHeaders(
                 [],
                 []
             );
         }
         // for model (json/xml)
         if (count($formParams) > 0) {
             if ($multipart) {
                 $multipartContents = [];
                 foreach ($formParams as $formParamName => $formParamValue) {
                     $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                     foreach ($formParamValueItems as $formParamValueItem) {
                         $multipartContents[] = [
                             'name' => $formParamName,
                             'contents' => $formParamValueItem
                         ];
                     }
                 }
                 // for HTTP post (form)
                 $httpBody = new MultipartStream($multipartContents);
             } elseif ($headers['Content-Type'] === 'application/json') {
                 $httpBody = \GuzzleHttp\json_encode($formParams);
             } else {
                 // for HTTP post (form)
                 $httpBody = ObjectSerializer::buildQuery($formParams);
             }
         }
         // this endpoint requires OAuth (access token)
         if (!empty($this->config->getAccessToken())) {
             $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
         }
         $defaultHeaders = [];
         if ($this->config->getUserAgent()) {
             $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
         }
         $headers = array_merge(
             $defaultHeaders,
             $headerParams,
             $headers
         );
         $operationHost = $this->config->getHost();
         $query = ObjectSerializer::buildQuery($queryParams);
         return new Request(
             'DELETE',
             $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
             $headers,
             $httpBody
         );
     }
deletePetWithHttpInfo()
Ally\PetStore\Api\PetApi::deletePetWithHttpInfo ($pet_id, $api_key = null)
Operation deletePetWithHttpInfo.
Deletes a pet
Parameters
int $pet_id Pet id to delete (required)
string $api_key (optional)
Exceptions
Definition at line 431 of file PetApi.php.
References Ally\PetStore\Api\PetApi\createHttpClientOption(), and Ally\PetStore\Api\PetApi\deletePetRequest().
Referenced by Ally\PetStore\Api\PetApi\deletePet().
     {
         $request = $this->deletePetRequest($pet_id, $api_key);
         try {
             $options = $this->createHttpClientOption();
             try {
                 $response = $this->client->send($request, $options);
             } catch (RequestException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                     $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                 );
             } catch (ConnectException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     null,
                     null
                 );
             }
             $statusCode = $response->getStatusCode();
             if ($statusCode < 200 || $statusCode > 299) {
                 throw new ApiException(
                     sprintf(
                         '[%d] Error connecting to the API (%s)',
                         $statusCode,
                         (string) $request->getUri()
                     ),
                     $statusCode,
                     $response->getHeaders(),
                     (string) $response->getBody()
                 );
             }
             return [null, $statusCode, $response->getHeaders()];
         } catch (ApiException $e) {
             switch ($e->getCode()) {
             }
             throw $e;
         }
     }
findPetsByStatus()
Ally\PetStore\Api\PetApi::findPetsByStatus ($status)
Operation findPetsByStatus.
Finds Pets by status
Parameters
string[] $status Status values that need to be considered for filter (required) (deprecated)
Exceptions
Definition at line 655 of file PetApi.php.
References Ally\PetStore\Api\PetApi\findPetsByStatusWithHttpInfo().
     {
         list($response) = $this->findPetsByStatusWithHttpInfo($status);
         return $response;
     }
findPetsByStatusAsync()
Ally\PetStore\Api\PetApi::findPetsByStatusAsync ($status)
Operation findPetsByStatusAsync.
Finds Pets by status
Parameters
string[] $status Status values that need to be considered for filter (required) (deprecated)
Exceptions
Definition at line 770 of file PetApi.php.
References Ally\PetStore\Api\PetApi\findPetsByStatusAsyncWithHttpInfo().
     {
         return $this->findPetsByStatusAsyncWithHttpInfo($status)
             ->then(
                 function ($response) {
                     return $response[0];
                 }
             );
     }
findPetsByStatusAsyncWithHttpInfo()
Ally\PetStore\Api\PetApi::findPetsByStatusAsyncWithHttpInfo ($status)
Operation findPetsByStatusAsyncWithHttpInfo.
Finds Pets by status
Parameters
string[] $status Status values that need to be considered for filter (required) (deprecated)
Exceptions
Definition at line 790 of file PetApi.php.
References Ally\PetStore\Api\PetApi\createHttpClientOption(), and Ally\PetStore\Api\PetApi\findPetsByStatusRequest().
Referenced by Ally\PetStore\Api\PetApi\findPetsByStatusAsync().
     {
         $returnType = '\Ally\PetStore\Schema\Pet[]';
         $request = $this->findPetsByStatusRequest($status);
         return $this->client
             ->sendAsync($request, $this->createHttpClientOption())
             ->then(
                 function ($response) use ($returnType) {
                     if ($returnType === '\SplFileObject') {
                         $content = $response->getBody(); //stream goes to serializer
                     } else {
                         $content = (string) $response->getBody();
                         if ($returnType !== 'string') {
                             $content = json_decode($content);
                         }
                     }
                     return [
                         ObjectSerializer::deserialize($content, $returnType, []),
                         $response->getStatusCode(),
                         $response->getHeaders()
                     ];
                 },
                 function ($exception) {
                     $response = $exception->getResponse();
                     $statusCode = $response->getStatusCode();
                     throw new ApiException(
                         sprintf(
                             '[%d] Error connecting to the API (%s)',
                             $statusCode,
                             $exception->getRequest()->getUri()
                         ),
                         $statusCode,
                         $response->getHeaders(),
                         (string) $response->getBody()
                     );
                 }
             );
     }
findPetsByStatusRequest()
Ally\PetStore\Api\PetApi::findPetsByStatusRequest ($status)
Create request for operation 'findPetsByStatus'.
Parameters
string[] $status Status values that need to be considered for filter (required) (deprecated)
Exceptions
Definition at line 839 of file PetApi.php.
References Ally\PetStore\ObjectSerializer\buildQuery(), and Ally\PetStore\ObjectSerializer\toQueryValue().
Referenced by Ally\PetStore\Api\PetApi\findPetsByStatusAsyncWithHttpInfo(), and Ally\PetStore\Api\PetApi\findPetsByStatusWithHttpInfo().
     {
         // verify the required parameter 'status' is set
         if ($status === null || (is_array($status) && count($status) === 0)) {
             throw new \InvalidArgumentException(
                 'Missing the required parameter $status when calling findPetsByStatus'
             );
         }
         $resourcePath = '/pet/findByStatus';
         $formParams = [];
         $queryParams = [];
         $headerParams = [];
         $httpBody = '';
         $multipart = false;
         // query params
         $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
             $status,
             'status', // param base name
             'array', // openApiType
             'form', // style
             false, // explode
             true // required
         ) ?? []);
         if ($multipart) {
             $headers = $this->headerSelector->selectHeadersForMultipart(
                 ['application/xml', 'application/json']
             );
         } else {
             $headers = $this->headerSelector->selectHeaders(
                 ['application/xml', 'application/json'],
                 []
             );
         }
         // for model (json/xml)
         if (count($formParams) > 0) {
             if ($multipart) {
                 $multipartContents = [];
                 foreach ($formParams as $formParamName => $formParamValue) {
                     $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                     foreach ($formParamValueItems as $formParamValueItem) {
                         $multipartContents[] = [
                             'name' => $formParamName,
                             'contents' => $formParamValueItem
                         ];
                     }
                 }
                 // for HTTP post (form)
                 $httpBody = new MultipartStream($multipartContents);
             } elseif ($headers['Content-Type'] === 'application/json') {
                 $httpBody = \GuzzleHttp\json_encode($formParams);
             } else {
                 // for HTTP post (form)
                 $httpBody = ObjectSerializer::buildQuery($formParams);
             }
         }
         // this endpoint requires OAuth (access token)
         if (!empty($this->config->getAccessToken())) {
             $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
         }
         $defaultHeaders = [];
         if ($this->config->getUserAgent()) {
             $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
         }
         $headers = array_merge(
             $defaultHeaders,
             $headerParams,
             $headers
         );
         $operationHost = $this->config->getHost();
         $query = ObjectSerializer::buildQuery($queryParams);
         return new Request(
             'GET',
             $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
             $headers,
             $httpBody
         );
     }
findPetsByStatusWithHttpInfo()
Ally\PetStore\Api\PetApi::findPetsByStatusWithHttpInfo ($status)
Operation findPetsByStatusWithHttpInfo.
Finds Pets by status
Parameters
string[] $status Status values that need to be considered for filter (required) (deprecated)
Exceptions
Definition at line 672 of file PetApi.php.
References Ally\PetStore\Api\PetApi\createHttpClientOption(), Ally\PetStore\Api\PetApi\findPetsByStatusRequest(), Ally\PetStore\ApiException\getResponseBody(), Ally\PetStore\ApiException\getResponseHeaders(), and Ally\PetStore\ApiException\setResponseObject().
Referenced by Ally\PetStore\Api\PetApi\findPetsByStatus().
     {
         $request = $this->findPetsByStatusRequest($status);
         try {
             $options = $this->createHttpClientOption();
             try {
                 $response = $this->client->send($request, $options);
             } catch (RequestException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                     $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                 );
             } catch (ConnectException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     null,
                     null
                 );
             }
             $statusCode = $response->getStatusCode();
             if ($statusCode < 200 || $statusCode > 299) {
                 throw new ApiException(
                     sprintf(
                         '[%d] Error connecting to the API (%s)',
                         $statusCode,
                         (string) $request->getUri()
                     ),
                     $statusCode,
                     $response->getHeaders(),
                     (string) $response->getBody()
                 );
             }
             switch($statusCode) {
                 case 200:
                     if ('\Ally\PetStore\Schema\Pet[]' === '\SplFileObject') {
                         $content = $response->getBody(); //stream goes to serializer
                     } else {
                         $content = (string) $response->getBody();
                         if ('\Ally\PetStore\Schema\Pet[]' !== 'string') {
                             $content = json_decode($content);
                         }
                     }
                     return [
                         ObjectSerializer::deserialize($content, '\Ally\PetStore\Schema\Pet[]', []),
                         $response->getStatusCode(),
                         $response->getHeaders()
                     ];
             }
             $returnType = '\Ally\PetStore\Schema\Pet[]';
             if ($returnType === '\SplFileObject') {
                 $content = $response->getBody(); //stream goes to serializer
             } else {
                 $content = (string) $response->getBody();
                 if ($returnType !== 'string') {
                     $content = json_decode($content);
                 }
             }
             return [
                 ObjectSerializer::deserialize($content, $returnType, []),
                 $response->getStatusCode(),
                 $response->getHeaders()
             ];
         } catch (ApiException $e) {
             switch ($e->getCode()) {
                 case 200:
                     $data = ObjectSerializer::deserialize(
                         $e->getResponseBody(),
                         '\Ally\PetStore\Schema\Pet[]',
                         $e->getResponseHeaders()
                     );
                     $e->setResponseObject($data);
                     break;
             }
             throw $e;
         }
     }
findPetsByTags()
Ally\PetStore\Api\PetApi::findPetsByTags ($tags)
Operation findPetsByTags.
Finds Pets by tags
Parameters
string[] $tags Tags to filter by (required)
Exceptions
Definition at line 943 of file PetApi.php.
References Ally\PetStore\Api\PetApi\findPetsByTagsWithHttpInfo().
     {
         list($response) = $this->findPetsByTagsWithHttpInfo($tags);
         return $response;
     }
findPetsByTagsAsync()
Ally\PetStore\Api\PetApi::findPetsByTagsAsync ($tags)
Operation findPetsByTagsAsync.
Finds Pets by tags
Parameters
string[] $tags Tags to filter by (required)
Exceptions
Definition at line 1060 of file PetApi.php.
References Ally\PetStore\Api\PetApi\findPetsByTagsAsyncWithHttpInfo().
     {
         return $this->findPetsByTagsAsyncWithHttpInfo($tags)
             ->then(
                 function ($response) {
                     return $response[0];
                 }
             );
     }
findPetsByTagsAsyncWithHttpInfo()
Ally\PetStore\Api\PetApi::findPetsByTagsAsyncWithHttpInfo ($tags)
Operation findPetsByTagsAsyncWithHttpInfo.
Finds Pets by tags
Parameters
string[] $tags Tags to filter by (required)
Exceptions
Definition at line 1081 of file PetApi.php.
References Ally\PetStore\Api\PetApi\createHttpClientOption(), and Ally\PetStore\Api\PetApi\findPetsByTagsRequest().
Referenced by Ally\PetStore\Api\PetApi\findPetsByTagsAsync().
     {
         $returnType = '\Ally\PetStore\Schema\Pet[]';
         $request = $this->findPetsByTagsRequest($tags);
         return $this->client
             ->sendAsync($request, $this->createHttpClientOption())
             ->then(
                 function ($response) use ($returnType) {
                     if ($returnType === '\SplFileObject') {
                         $content = $response->getBody(); //stream goes to serializer
                     } else {
                         $content = (string) $response->getBody();
                         if ($returnType !== 'string') {
                             $content = json_decode($content);
                         }
                     }
                     return [
                         ObjectSerializer::deserialize($content, $returnType, []),
                         $response->getStatusCode(),
                         $response->getHeaders()
                     ];
                 },
                 function ($exception) {
                     $response = $exception->getResponse();
                     $statusCode = $response->getStatusCode();
                     throw new ApiException(
                         sprintf(
                             '[%d] Error connecting to the API (%s)',
                             $statusCode,
                             $exception->getRequest()->getUri()
                         ),
                         $statusCode,
                         $response->getHeaders(),
                         (string) $response->getBody()
                     );
                 }
             );
     }
findPetsByTagsRequest()
Ally\PetStore\Api\PetApi::findPetsByTagsRequest ($tags)
Create request for operation 'findPetsByTags'.
Parameters
string[] $tags Tags to filter by (required)
Exceptions
Definition at line 1131 of file PetApi.php.
References Ally\PetStore\ObjectSerializer\buildQuery(), and Ally\PetStore\ObjectSerializer\toQueryValue().
Referenced by Ally\PetStore\Api\PetApi\findPetsByTagsAsyncWithHttpInfo(), and Ally\PetStore\Api\PetApi\findPetsByTagsWithHttpInfo().
     {
         // verify the required parameter 'tags' is set
         if ($tags === null || (is_array($tags) && count($tags) === 0)) {
             throw new \InvalidArgumentException(
                 'Missing the required parameter $tags when calling findPetsByTags'
             );
         }
         $resourcePath = '/pet/findByTags';
         $formParams = [];
         $queryParams = [];
         $headerParams = [];
         $httpBody = '';
         $multipart = false;
         // query params
         $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
             $tags,
             'tags', // param base name
             'array', // openApiType
             'form', // style
             false, // explode
             true // required
         ) ?? []);
         if ($multipart) {
             $headers = $this->headerSelector->selectHeadersForMultipart(
                 ['application/xml', 'application/json']
             );
         } else {
             $headers = $this->headerSelector->selectHeaders(
                 ['application/xml', 'application/json'],
                 []
             );
         }
         // for model (json/xml)
         if (count($formParams) > 0) {
             if ($multipart) {
                 $multipartContents = [];
                 foreach ($formParams as $formParamName => $formParamValue) {
                     $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                     foreach ($formParamValueItems as $formParamValueItem) {
                         $multipartContents[] = [
                             'name' => $formParamName,
                             'contents' => $formParamValueItem
                         ];
                     }
                 }
                 // for HTTP post (form)
                 $httpBody = new MultipartStream($multipartContents);
             } elseif ($headers['Content-Type'] === 'application/json') {
                 $httpBody = \GuzzleHttp\json_encode($formParams);
             } else {
                 // for HTTP post (form)
                 $httpBody = ObjectSerializer::buildQuery($formParams);
             }
         }
         // this endpoint requires OAuth (access token)
         if (!empty($this->config->getAccessToken())) {
             $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
         }
         $defaultHeaders = [];
         if ($this->config->getUserAgent()) {
             $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
         }
         $headers = array_merge(
             $defaultHeaders,
             $headerParams,
             $headers
         );
         $operationHost = $this->config->getHost();
         $query = ObjectSerializer::buildQuery($queryParams);
         return new Request(
             'GET',
             $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
             $headers,
             $httpBody
         );
     }
findPetsByTagsWithHttpInfo()
Ally\PetStore\Api\PetApi::findPetsByTagsWithHttpInfo ($tags)
Operation findPetsByTagsWithHttpInfo.
Finds Pets by tags
Parameters
string[] $tags Tags to filter by (required)
Exceptions
Definition at line 961 of file PetApi.php.
References Ally\PetStore\Api\PetApi\createHttpClientOption(), Ally\PetStore\Api\PetApi\findPetsByTagsRequest(), Ally\PetStore\ApiException\getResponseBody(), Ally\PetStore\ApiException\getResponseHeaders(), and Ally\PetStore\ApiException\setResponseObject().
Referenced by Ally\PetStore\Api\PetApi\findPetsByTags().
     {
         $request = $this->findPetsByTagsRequest($tags);
         try {
             $options = $this->createHttpClientOption();
             try {
                 $response = $this->client->send($request, $options);
             } catch (RequestException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                     $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                 );
             } catch (ConnectException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     null,
                     null
                 );
             }
             $statusCode = $response->getStatusCode();
             if ($statusCode < 200 || $statusCode > 299) {
                 throw new ApiException(
                     sprintf(
                         '[%d] Error connecting to the API (%s)',
                         $statusCode,
                         (string) $request->getUri()
                     ),
                     $statusCode,
                     $response->getHeaders(),
                     (string) $response->getBody()
                 );
             }
             switch($statusCode) {
                 case 200:
                     if ('\Ally\PetStore\Schema\Pet[]' === '\SplFileObject') {
                         $content = $response->getBody(); //stream goes to serializer
                     } else {
                         $content = (string) $response->getBody();
                         if ('\Ally\PetStore\Schema\Pet[]' !== 'string') {
                             $content = json_decode($content);
                         }
                     }
                     return [
                         ObjectSerializer::deserialize($content, '\Ally\PetStore\Schema\Pet[]', []),
                         $response->getStatusCode(),
                         $response->getHeaders()
                     ];
             }
             $returnType = '\Ally\PetStore\Schema\Pet[]';
             if ($returnType === '\SplFileObject') {
                 $content = $response->getBody(); //stream goes to serializer
             } else {
                 $content = (string) $response->getBody();
                 if ($returnType !== 'string') {
                     $content = json_decode($content);
                 }
             }
             return [
                 ObjectSerializer::deserialize($content, $returnType, []),
                 $response->getStatusCode(),
                 $response->getHeaders()
             ];
         } catch (ApiException $e) {
             switch ($e->getCode()) {
                 case 200:
                     $data = ObjectSerializer::deserialize(
                         $e->getResponseBody(),
                         '\Ally\PetStore\Schema\Pet[]',
                         $e->getResponseHeaders()
                     );
                     $e->setResponseObject($data);
                     break;
             }
             throw $e;
         }
     }
getConfig()
Ally\PetStore\Api\PetApi::getConfig ()
Returns
Configuration
Definition at line 113 of file PetApi.php.
References Ally\PetStore\Api\PetApi\$config.
     {
         return $this->config;
     }
getHostIndex()
Ally\PetStore\Api\PetApi::getHostIndex ()
Get the host index.
Returns
int Host index
Definition at line 105 of file PetApi.php.
References Ally\PetStore\Api\PetApi\$hostIndex.
     {
         return $this->hostIndex;
     }
getPetById()
Ally\PetStore\Api\PetApi::getPetById ($pet_id)
Operation getPetById.
Find pet by ID
Parameters
int $pet_id ID of pet to return (required)
Exceptions
Definition at line 1234 of file PetApi.php.
References Ally\PetStore\Api\PetApi\getPetByIdWithHttpInfo().
     {
         list($response) = $this->getPetByIdWithHttpInfo($pet_id);
         return $response;
     }
getPetByIdAsync()
Ally\PetStore\Api\PetApi::getPetByIdAsync ($pet_id)
Operation getPetByIdAsync.
Find pet by ID
Parameters
int $pet_id ID of pet to return (required)
Exceptions
Definition at line 1349 of file PetApi.php.
References Ally\PetStore\Api\PetApi\getPetByIdAsyncWithHttpInfo().
     {
         return $this->getPetByIdAsyncWithHttpInfo($pet_id)
             ->then(
                 function ($response) {
                     return $response[0];
                 }
             );
     }
getPetByIdAsyncWithHttpInfo()
Ally\PetStore\Api\PetApi::getPetByIdAsyncWithHttpInfo ($pet_id)
Operation getPetByIdAsyncWithHttpInfo.
Find pet by ID
Parameters
int $pet_id ID of pet to return (required)
Exceptions
Definition at line 1369 of file PetApi.php.
References Ally\PetStore\Api\PetApi\createHttpClientOption(), and Ally\PetStore\Api\PetApi\getPetByIdRequest().
Referenced by Ally\PetStore\Api\PetApi\getPetByIdAsync().
     {
         $returnType = '\Ally\PetStore\Schema\Pet';
         $request = $this->getPetByIdRequest($pet_id);
         return $this->client
             ->sendAsync($request, $this->createHttpClientOption())
             ->then(
                 function ($response) use ($returnType) {
                     if ($returnType === '\SplFileObject') {
                         $content = $response->getBody(); //stream goes to serializer
                     } else {
                         $content = (string) $response->getBody();
                         if ($returnType !== 'string') {
                             $content = json_decode($content);
                         }
                     }
                     return [
                         ObjectSerializer::deserialize($content, $returnType, []),
                         $response->getStatusCode(),
                         $response->getHeaders()
                     ];
                 },
                 function ($exception) {
                     $response = $exception->getResponse();
                     $statusCode = $response->getStatusCode();
                     throw new ApiException(
                         sprintf(
                             '[%d] Error connecting to the API (%s)',
                             $statusCode,
                             $exception->getRequest()->getUri()
                         ),
                         $statusCode,
                         $response->getHeaders(),
                         (string) $response->getBody()
                     );
                 }
             );
     }
getPetByIdRequest()
Ally\PetStore\Api\PetApi::getPetByIdRequest ($pet_id)
Create request for operation 'getPetById'.
Parameters
int $pet_id ID of pet to return (required)
Exceptions
Definition at line 1418 of file PetApi.php.
References Ally\PetStore\ObjectSerializer\buildQuery(), and Ally\PetStore\ObjectSerializer\toPathValue().
Referenced by Ally\PetStore\Api\PetApi\getPetByIdAsyncWithHttpInfo(), and Ally\PetStore\Api\PetApi\getPetByIdWithHttpInfo().
     {
         // verify the required parameter 'pet_id' is set
         if ($pet_id === null || (is_array($pet_id) && count($pet_id) === 0)) {
             throw new \InvalidArgumentException(
                 'Missing the required parameter $pet_id when calling getPetById'
             );
         }
         $resourcePath = '/pet/{petId}';
         $formParams = [];
         $queryParams = [];
         $headerParams = [];
         $httpBody = '';
         $multipart = false;
         // path params
         if ($pet_id !== null) {
             $resourcePath = str_replace(
                 '{' . 'petId' . '}',
                 ObjectSerializer::toPathValue($pet_id),
                 $resourcePath
             );
         }
         if ($multipart) {
             $headers = $this->headerSelector->selectHeadersForMultipart(
                 ['application/xml', 'application/json']
             );
         } else {
             $headers = $this->headerSelector->selectHeaders(
                 ['application/xml', 'application/json'],
                 []
             );
         }
         // for model (json/xml)
         if (count($formParams) > 0) {
             if ($multipart) {
                 $multipartContents = [];
                 foreach ($formParams as $formParamName => $formParamValue) {
                     $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                     foreach ($formParamValueItems as $formParamValueItem) {
                         $multipartContents[] = [
                             'name' => $formParamName,
                             'contents' => $formParamValueItem
                         ];
                     }
                 }
                 // for HTTP post (form)
                 $httpBody = new MultipartStream($multipartContents);
             } elseif ($headers['Content-Type'] === 'application/json') {
                 $httpBody = \GuzzleHttp\json_encode($formParams);
             } else {
                 // for HTTP post (form)
                 $httpBody = ObjectSerializer::buildQuery($formParams);
             }
         }
         // this endpoint requires API key authentication
         $apiKey = $this->config->getApiKeyWithPrefix('api_key');
         if ($apiKey !== null) {
             $headers['api_key'] = $apiKey;
         }
         $defaultHeaders = [];
         if ($this->config->getUserAgent()) {
             $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
         }
         $headers = array_merge(
             $defaultHeaders,
             $headerParams,
             $headers
         );
         $operationHost = $this->config->getHost();
         $query = ObjectSerializer::buildQuery($queryParams);
         return new Request(
             'GET',
             $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
             $headers,
             $httpBody
         );
     }
getPetByIdWithHttpInfo()
Ally\PetStore\Api\PetApi::getPetByIdWithHttpInfo ($pet_id)
Operation getPetByIdWithHttpInfo.
Find pet by ID
Parameters
int $pet_id ID of pet to return (required)
Exceptions
Definition at line 1251 of file PetApi.php.
References Ally\PetStore\Api\PetApi\createHttpClientOption(), Ally\PetStore\Api\PetApi\getPetByIdRequest(), Ally\PetStore\ApiException\getResponseBody(), Ally\PetStore\ApiException\getResponseHeaders(), and Ally\PetStore\ApiException\setResponseObject().
Referenced by Ally\PetStore\Api\PetApi\getPetById().
     {
         $request = $this->getPetByIdRequest($pet_id);
         try {
             $options = $this->createHttpClientOption();
             try {
                 $response = $this->client->send($request, $options);
             } catch (RequestException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                     $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                 );
             } catch (ConnectException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     null,
                     null
                 );
             }
             $statusCode = $response->getStatusCode();
             if ($statusCode < 200 || $statusCode > 299) {
                 throw new ApiException(
                     sprintf(
                         '[%d] Error connecting to the API (%s)',
                         $statusCode,
                         (string) $request->getUri()
                     ),
                     $statusCode,
                     $response->getHeaders(),
                     (string) $response->getBody()
                 );
             }
             switch($statusCode) {
                 case 200:
                     if ('\Ally\PetStore\Schema\Pet' === '\SplFileObject') {
                         $content = $response->getBody(); //stream goes to serializer
                     } else {
                         $content = (string) $response->getBody();
                         if ('\Ally\PetStore\Schema\Pet' !== 'string') {
                             $content = json_decode($content);
                         }
                     }
                     return [
                         ObjectSerializer::deserialize($content, '\Ally\PetStore\Schema\Pet', []),
                         $response->getStatusCode(),
                         $response->getHeaders()
                     ];
             }
             $returnType = '\Ally\PetStore\Schema\Pet';
             if ($returnType === '\SplFileObject') {
                 $content = $response->getBody(); //stream goes to serializer
             } else {
                 $content = (string) $response->getBody();
                 if ($returnType !== 'string') {
                     $content = json_decode($content);
                 }
             }
             return [
                 ObjectSerializer::deserialize($content, $returnType, []),
                 $response->getStatusCode(),
                 $response->getHeaders()
             ];
         } catch (ApiException $e) {
             switch ($e->getCode()) {
                 case 200:
                     $data = ObjectSerializer::deserialize(
                         $e->getResponseBody(),
                         '\Ally\PetStore\Schema\Pet',
                         $e->getResponseHeaders()
                     );
                     $e->setResponseObject($data);
                     break;
             }
             throw $e;
         }
     }
setHostIndex()
Ally\PetStore\Api\PetApi::setHostIndex ($hostIndex)
Set the host index.
Parameters
int $hostIndex Host index (required)
Definition at line 95 of file PetApi.php.
References Ally\PetStore\Api\PetApi\$hostIndex.
                                             : void
     {
         $this->hostIndex = $hostIndex;
     }
updatePet()
Ally\PetStore\Api\PetApi::updatePet ($pet)
Operation updatePet.
Update an existing pet
Parameters
\Ally\PetStore\Schema\Pet $pet Pet object that needs to be added to the store (required)
Exceptions
Definition at line 1521 of file PetApi.php.
References Ally\PetStore\Api\PetApi\updatePetWithHttpInfo().
     {
         list($response) = $this->updatePetWithHttpInfo($pet);
         return $response;
     }
updatePetAsync()
Ally\PetStore\Api\PetApi::updatePetAsync ($pet)
Operation updatePetAsync.
Update an existing pet
Parameters
\Ally\PetStore\Schema\Pet $pet Pet object that needs to be added to the store (required)
Exceptions
Definition at line 1636 of file PetApi.php.
References Ally\PetStore\Api\PetApi\updatePetAsyncWithHttpInfo().
     {
         return $this->updatePetAsyncWithHttpInfo($pet)
             ->then(
                 function ($response) {
                     return $response[0];
                 }
             );
     }
updatePetAsyncWithHttpInfo()
Ally\PetStore\Api\PetApi::updatePetAsyncWithHttpInfo ($pet)
Operation updatePetAsyncWithHttpInfo.
Update an existing pet
Parameters
\Ally\PetStore\Schema\Pet $pet Pet object that needs to be added to the store (required)
Exceptions
Definition at line 1656 of file PetApi.php.
References Ally\PetStore\Api\PetApi\createHttpClientOption(), and Ally\PetStore\Api\PetApi\updatePetRequest().
Referenced by Ally\PetStore\Api\PetApi\updatePetAsync().
     {
         $returnType = '\Ally\PetStore\Schema\Pet';
         $request = $this->updatePetRequest($pet);
         return $this->client
             ->sendAsync($request, $this->createHttpClientOption())
             ->then(
                 function ($response) use ($returnType) {
                     if ($returnType === '\SplFileObject') {
                         $content = $response->getBody(); //stream goes to serializer
                     } else {
                         $content = (string) $response->getBody();
                         if ($returnType !== 'string') {
                             $content = json_decode($content);
                         }
                     }
                     return [
                         ObjectSerializer::deserialize($content, $returnType, []),
                         $response->getStatusCode(),
                         $response->getHeaders()
                     ];
                 },
                 function ($exception) {
                     $response = $exception->getResponse();
                     $statusCode = $response->getStatusCode();
                     throw new ApiException(
                         sprintf(
                             '[%d] Error connecting to the API (%s)',
                             $statusCode,
                             $exception->getRequest()->getUri()
                         ),
                         $statusCode,
                         $response->getHeaders(),
                         (string) $response->getBody()
                     );
                 }
             );
     }
updatePetRequest()
Ally\PetStore\Api\PetApi::updatePetRequest ($pet)
Create request for operation 'updatePet'.
Parameters
\Ally\PetStore\Schema\Pet $pet Pet object that needs to be added to the store (required)
Exceptions
Definition at line 1705 of file PetApi.php.
References Ally\PetStore\ObjectSerializer\buildQuery(), and Ally\PetStore\ObjectSerializer\sanitizeForSerialization().
Referenced by Ally\PetStore\Api\PetApi\updatePetAsyncWithHttpInfo(), and Ally\PetStore\Api\PetApi\updatePetWithHttpInfo().
     {
         // verify the required parameter 'pet' is set
         if ($pet === null || (is_array($pet) && count($pet) === 0)) {
             throw new \InvalidArgumentException(
                 'Missing the required parameter $pet when calling updatePet'
             );
         }
         $resourcePath = '/pet';
         $formParams = [];
         $queryParams = [];
         $headerParams = [];
         $httpBody = '';
         $multipart = false;
         if ($multipart) {
             $headers = $this->headerSelector->selectHeadersForMultipart(
                 ['application/xml', 'application/json']
             );
         } else {
             $headers = $this->headerSelector->selectHeaders(
                 ['application/xml', 'application/json'],
                 ['application/json', 'application/xml']
             );
         }
         // for model (json/xml)
         if (isset($pet)) {
             if ($headers['Content-Type'] === 'application/json') {
                 $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($pet));
             } else {
                 $httpBody = $pet;
             }
         } elseif (count($formParams) > 0) {
             if ($multipart) {
                 $multipartContents = [];
                 foreach ($formParams as $formParamName => $formParamValue) {
                     $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                     foreach ($formParamValueItems as $formParamValueItem) {
                         $multipartContents[] = [
                             'name' => $formParamName,
                             'contents' => $formParamValueItem
                         ];
                     }
                 }
                 // for HTTP post (form)
                 $httpBody = new MultipartStream($multipartContents);
             } elseif ($headers['Content-Type'] === 'application/json') {
                 $httpBody = \GuzzleHttp\json_encode($formParams);
             } else {
                 // for HTTP post (form)
                 $httpBody = ObjectSerializer::buildQuery($formParams);
             }
         }
         // this endpoint requires OAuth (access token)
         if (!empty($this->config->getAccessToken())) {
             $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
         }
         $defaultHeaders = [];
         if ($this->config->getUserAgent()) {
             $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
         }
         $headers = array_merge(
             $defaultHeaders,
             $headerParams,
             $headers
         );
         $operationHost = $this->config->getHost();
         $query = ObjectSerializer::buildQuery($queryParams);
         return new Request(
             'PUT',
             $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
             $headers,
             $httpBody
         );
     }
updatePetWithForm()
Ally\PetStore\Api\PetApi::updatePetWithForm ($pet_id, $name = null, $status = null)
Operation updatePetWithForm.
Updates a pet in the store with form data
Parameters
int $pet_id ID of pet that needs to be updated (required)
string $name Updated name of the pet (optional)
string $status Updated status of the pet (optional)
Exceptions
Definition at line 1807 of file PetApi.php.
References Ally\PetStore\Api\PetApi\updatePetWithFormWithHttpInfo().
     {
         $this->updatePetWithFormWithHttpInfo($pet_id, $name, $status);
     }
updatePetWithFormAsync()
Ally\PetStore\Api\PetApi::updatePetWithFormAsync ($pet_id, $name = null, $status = null)
Operation updatePetWithFormAsync.
Updates a pet in the store with form data
Parameters
int $pet_id ID of pet that needs to be updated (required)
string $name Updated name of the pet (optional)
string $status Updated status of the pet (optional)
Exceptions
Definition at line 1885 of file PetApi.php.
References Ally\PetStore\Api\PetApi\updatePetWithFormAsyncWithHttpInfo().
     {
         return $this->updatePetWithFormAsyncWithHttpInfo($pet_id, $name, $status)
             ->then(
                 function ($response) {
                     return $response[0];
                 }
             );
     }
updatePetWithFormAsyncWithHttpInfo()
Ally\PetStore\Api\PetApi::updatePetWithFormAsyncWithHttpInfo ($pet_id, $name = null, $status = null)
Operation updatePetWithFormAsyncWithHttpInfo.
Updates a pet in the store with form data
Parameters
int $pet_id ID of pet that needs to be updated (required)
string $name Updated name of the pet (optional)
string $status Updated status of the pet (optional)
Exceptions
Definition at line 1907 of file PetApi.php.
References Ally\PetStore\Api\PetApi\createHttpClientOption(), and Ally\PetStore\Api\PetApi\updatePetWithFormRequest().
Referenced by Ally\PetStore\Api\PetApi\updatePetWithFormAsync().
     {
         $returnType = '';
         $request = $this->updatePetWithFormRequest($pet_id, $name, $status);
         return $this->client
             ->sendAsync($request, $this->createHttpClientOption())
             ->then(
                 function ($response) use ($returnType) {
                     return [null, $response->getStatusCode(), $response->getHeaders()];
                 },
                 function ($exception) {
                     $response = $exception->getResponse();
                     $statusCode = $response->getStatusCode();
                     throw new ApiException(
                         sprintf(
                             '[%d] Error connecting to the API (%s)',
                             $statusCode,
                             $exception->getRequest()->getUri()
                         ),
                         $statusCode,
                         $response->getHeaders(),
                         (string) $response->getBody()
                     );
                 }
             );
     }
updatePetWithFormRequest()
Ally\PetStore\Api\PetApi::updatePetWithFormRequest ($pet_id, $name = null, $status = null)
Create request for operation 'updatePetWithForm'.
Parameters
int $pet_id ID of pet that needs to be updated (required)
string $name Updated name of the pet (optional)
string $status Updated status of the pet (optional)
Exceptions
Definition at line 1945 of file PetApi.php.
References Ally\PetStore\ObjectSerializer\buildQuery(), Ally\PetStore\ObjectSerializer\toFormValue(), and Ally\PetStore\ObjectSerializer\toPathValue().
Referenced by Ally\PetStore\Api\PetApi\updatePetWithFormAsyncWithHttpInfo(), and Ally\PetStore\Api\PetApi\updatePetWithFormWithHttpInfo().
     {
         // verify the required parameter 'pet_id' is set
         if ($pet_id === null || (is_array($pet_id) && count($pet_id) === 0)) {
             throw new \InvalidArgumentException(
                 'Missing the required parameter $pet_id when calling updatePetWithForm'
             );
         }
         $resourcePath = '/pet/{petId}';
         $formParams = [];
         $queryParams = [];
         $headerParams = [];
         $httpBody = '';
         $multipart = false;
         // path params
         if ($pet_id !== null) {
             $resourcePath = str_replace(
                 '{' . 'petId' . '}',
                 ObjectSerializer::toPathValue($pet_id),
                 $resourcePath
             );
         }
         // form params
         if ($name !== null) {
             $formParams['name'] = ObjectSerializer::toFormValue($name);
         }
         // form params
         if ($status !== null) {
             $formParams['status'] = ObjectSerializer::toFormValue($status);
         }
         if ($multipart) {
             $headers = $this->headerSelector->selectHeadersForMultipart(
                 []
             );
         } else {
             $headers = $this->headerSelector->selectHeaders(
                 [],
                 ['application/x-www-form-urlencoded']
             );
         }
         // for model (json/xml)
         if (count($formParams) > 0) {
             if ($multipart) {
                 $multipartContents = [];
                 foreach ($formParams as $formParamName => $formParamValue) {
                     $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                     foreach ($formParamValueItems as $formParamValueItem) {
                         $multipartContents[] = [
                             'name' => $formParamName,
                             'contents' => $formParamValueItem
                         ];
                     }
                 }
                 // for HTTP post (form)
                 $httpBody = new MultipartStream($multipartContents);
             } elseif ($headers['Content-Type'] === 'application/json') {
                 $httpBody = \GuzzleHttp\json_encode($formParams);
             } else {
                 // for HTTP post (form)
                 $httpBody = ObjectSerializer::buildQuery($formParams);
             }
         }
         // this endpoint requires OAuth (access token)
         if (!empty($this->config->getAccessToken())) {
             $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
         }
         $defaultHeaders = [];
         if ($this->config->getUserAgent()) {
             $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
         }
         $headers = array_merge(
             $defaultHeaders,
             $headerParams,
             $headers
         );
         $operationHost = $this->config->getHost();
         $query = ObjectSerializer::buildQuery($queryParams);
         return new Request(
             'POST',
             $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
             $headers,
             $httpBody
         );
     }
updatePetWithFormWithHttpInfo()
Ally\PetStore\Api\PetApi::updatePetWithFormWithHttpInfo ($pet_id, $name = null, $status = null)
Operation updatePetWithFormWithHttpInfo.
Updates a pet in the store with form data
Parameters
int $pet_id ID of pet that needs to be updated (required)
string $name Updated name of the pet (optional)
string $status Updated status of the pet (optional)
Exceptions
Definition at line 1825 of file PetApi.php.
References Ally\PetStore\Api\PetApi\createHttpClientOption(), and Ally\PetStore\Api\PetApi\updatePetWithFormRequest().
Referenced by Ally\PetStore\Api\PetApi\updatePetWithForm().
     {
         $request = $this->updatePetWithFormRequest($pet_id, $name, $status);
         try {
             $options = $this->createHttpClientOption();
             try {
                 $response = $this->client->send($request, $options);
             } catch (RequestException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                     $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                 );
             } catch (ConnectException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     null,
                     null
                 );
             }
             $statusCode = $response->getStatusCode();
             if ($statusCode < 200 || $statusCode > 299) {
                 throw new ApiException(
                     sprintf(
                         '[%d] Error connecting to the API (%s)',
                         $statusCode,
                         (string) $request->getUri()
                     ),
                     $statusCode,
                     $response->getHeaders(),
                     (string) $response->getBody()
                 );
             }
             return [null, $statusCode, $response->getHeaders()];
         } catch (ApiException $e) {
             switch ($e->getCode()) {
             }
             throw $e;
         }
     }
updatePetWithHttpInfo()
Ally\PetStore\Api\PetApi::updatePetWithHttpInfo ($pet)
Operation updatePetWithHttpInfo.
Update an existing pet
Parameters
\Ally\PetStore\Schema\Pet $pet Pet object that needs to be added to the store (required)
Exceptions
Definition at line 1538 of file PetApi.php.
References Ally\PetStore\Api\PetApi\createHttpClientOption(), Ally\PetStore\ApiException\getResponseBody(), Ally\PetStore\ApiException\getResponseHeaders(), Ally\PetStore\ApiException\setResponseObject(), and Ally\PetStore\Api\PetApi\updatePetRequest().
Referenced by Ally\PetStore\Api\PetApi\updatePet().
     {
         $request = $this->updatePetRequest($pet);
         try {
             $options = $this->createHttpClientOption();
             try {
                 $response = $this->client->send($request, $options);
             } catch (RequestException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                     $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                 );
             } catch (ConnectException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     null,
                     null
                 );
             }
             $statusCode = $response->getStatusCode();
             if ($statusCode < 200 || $statusCode > 299) {
                 throw new ApiException(
                     sprintf(
                         '[%d] Error connecting to the API (%s)',
                         $statusCode,
                         (string) $request->getUri()
                     ),
                     $statusCode,
                     $response->getHeaders(),
                     (string) $response->getBody()
                 );
             }
             switch($statusCode) {
                 case 200:
                     if ('\Ally\PetStore\Schema\Pet' === '\SplFileObject') {
                         $content = $response->getBody(); //stream goes to serializer
                     } else {
                         $content = (string) $response->getBody();
                         if ('\Ally\PetStore\Schema\Pet' !== 'string') {
                             $content = json_decode($content);
                         }
                     }
                     return [
                         ObjectSerializer::deserialize($content, '\Ally\PetStore\Schema\Pet', []),
                         $response->getStatusCode(),
                         $response->getHeaders()
                     ];
             }
             $returnType = '\Ally\PetStore\Schema\Pet';
             if ($returnType === '\SplFileObject') {
                 $content = $response->getBody(); //stream goes to serializer
             } else {
                 $content = (string) $response->getBody();
                 if ($returnType !== 'string') {
                     $content = json_decode($content);
                 }
             }
             return [
                 ObjectSerializer::deserialize($content, $returnType, []),
                 $response->getStatusCode(),
                 $response->getHeaders()
             ];
         } catch (ApiException $e) {
             switch ($e->getCode()) {
                 case 200:
                     $data = ObjectSerializer::deserialize(
                         $e->getResponseBody(),
                         '\Ally\PetStore\Schema\Pet',
                         $e->getResponseHeaders()
                     );
                     $e->setResponseObject($data);
                     break;
             }
             throw $e;
         }
     }
uploadFile()
Ally\PetStore\Api\PetApi::uploadFile ($pet_id, $additional_metadata = null, $file = null)
Operation uploadFile.
uploads an image
Parameters
int $pet_id ID of pet to update (required)
string $additional_metadata Additional data to pass to server (optional)
\SplFileObject $file file to upload (optional)
Exceptions
Definition at line 2059 of file PetApi.php.
References Ally\PetStore\Api\PetApi\uploadFileWithHttpInfo().
     {
         list($response) = $this->uploadFileWithHttpInfo($pet_id, $additional_metadata, $file);
         return $response;
     }
uploadFileAsync()
Ally\PetStore\Api\PetApi::uploadFileAsync ($pet_id, $additional_metadata = null, $file = null)
Operation uploadFileAsync.
uploads an image
Parameters
int $pet_id ID of pet to update (required)
string $additional_metadata Additional data to pass to server (optional)
\SplFileObject $file file to upload (optional)
Exceptions
Definition at line 2178 of file PetApi.php.
References Ally\PetStore\Api\PetApi\uploadFileAsyncWithHttpInfo().
     {
         return $this->uploadFileAsyncWithHttpInfo($pet_id, $additional_metadata, $file)
             ->then(
                 function ($response) {
                     return $response[0];
                 }
             );
     }
uploadFileAsyncWithHttpInfo()
Ally\PetStore\Api\PetApi::uploadFileAsyncWithHttpInfo ($pet_id, $additional_metadata = null, $file = null)
Operation uploadFileAsyncWithHttpInfo.
uploads an image
Parameters
int $pet_id ID of pet to update (required)
string $additional_metadata Additional data to pass to server (optional)
\SplFileObject $file file to upload (optional)
Exceptions
Definition at line 2200 of file PetApi.php.
References Ally\PetStore\Api\PetApi\createHttpClientOption(), and Ally\PetStore\Api\PetApi\uploadFileRequest().
Referenced by Ally\PetStore\Api\PetApi\uploadFileAsync().
     {
         $returnType = '\Ally\PetStore\Schema\ApiResponse';
         $request = $this->uploadFileRequest($pet_id, $additional_metadata, $file);
         return $this->client
             ->sendAsync($request, $this->createHttpClientOption())
             ->then(
                 function ($response) use ($returnType) {
                     if ($returnType === '\SplFileObject') {
                         $content = $response->getBody(); //stream goes to serializer
                     } else {
                         $content = (string) $response->getBody();
                         if ($returnType !== 'string') {
                             $content = json_decode($content);
                         }
                     }
                     return [
                         ObjectSerializer::deserialize($content, $returnType, []),
                         $response->getStatusCode(),
                         $response->getHeaders()
                     ];
                 },
                 function ($exception) {
                     $response = $exception->getResponse();
                     $statusCode = $response->getStatusCode();
                     throw new ApiException(
                         sprintf(
                             '[%d] Error connecting to the API (%s)',
                             $statusCode,
                             $exception->getRequest()->getUri()
                         ),
                         $statusCode,
                         $response->getHeaders(),
                         (string) $response->getBody()
                     );
                 }
             );
     }
uploadFileRequest()
Ally\PetStore\Api\PetApi::uploadFileRequest ($pet_id, $additional_metadata = null, $file = null)
Create request for operation 'uploadFile'.
Parameters
int $pet_id ID of pet to update (required)
string $additional_metadata Additional data to pass to server (optional)
\SplFileObject $file file to upload (optional)
Exceptions
Definition at line 2251 of file PetApi.php.
References Ally\PetStore\ObjectSerializer\buildQuery(), Ally\PetStore\ObjectSerializer\toFormValue(), and Ally\PetStore\ObjectSerializer\toPathValue().
Referenced by Ally\PetStore\Api\PetApi\uploadFileAsyncWithHttpInfo(), and Ally\PetStore\Api\PetApi\uploadFileWithHttpInfo().
     {
         // verify the required parameter 'pet_id' is set
         if ($pet_id === null || (is_array($pet_id) && count($pet_id) === 0)) {
             throw new \InvalidArgumentException(
                 'Missing the required parameter $pet_id when calling uploadFile'
             );
         }
         $resourcePath = '/pet/{petId}/uploadImage';
         $formParams = [];
         $queryParams = [];
         $headerParams = [];
         $httpBody = '';
         $multipart = false;
         // path params
         if ($pet_id !== null) {
             $resourcePath = str_replace(
                 '{' . 'petId' . '}',
                 ObjectSerializer::toPathValue($pet_id),
                 $resourcePath
             );
         }
         // form params
         if ($additional_metadata !== null) {
             $formParams['additionalMetadata'] = ObjectSerializer::toFormValue($additional_metadata);
         }
         // form params
         if ($file !== null) {
             $multipart = true;
             $formParams['file'] = [];
             $paramFiles = is_array($file) ? $file : [$file];
             foreach ($paramFiles as $paramFile) {
                 $formParams['file'][] = \GuzzleHttp\Psr7\Utils::tryFopen(
                     ObjectSerializer::toFormValue($paramFile),
                     'rb'
                 );
             }
         }
         if ($multipart) {
             $headers = $this->headerSelector->selectHeadersForMultipart(
                 ['application/json']
             );
         } else {
             $headers = $this->headerSelector->selectHeaders(
                 ['application/json'],
                 ['multipart/form-data']
             );
         }
         // for model (json/xml)
         if (count($formParams) > 0) {
             if ($multipart) {
                 $multipartContents = [];
                 foreach ($formParams as $formParamName => $formParamValue) {
                     $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                     foreach ($formParamValueItems as $formParamValueItem) {
                         $multipartContents[] = [
                             'name' => $formParamName,
                             'contents' => $formParamValueItem
                         ];
                     }
                 }
                 // for HTTP post (form)
                 $httpBody = new MultipartStream($multipartContents);
             } elseif ($headers['Content-Type'] === 'application/json') {
                 $httpBody = \GuzzleHttp\json_encode($formParams);
             } else {
                 // for HTTP post (form)
                 $httpBody = ObjectSerializer::buildQuery($formParams);
             }
         }
         // this endpoint requires OAuth (access token)
         if (!empty($this->config->getAccessToken())) {
             $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
         }
         $defaultHeaders = [];
         if ($this->config->getUserAgent()) {
             $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
         }
         $headers = array_merge(
             $defaultHeaders,
             $headerParams,
             $headers
         );
         $operationHost = $this->config->getHost();
         $query = ObjectSerializer::buildQuery($queryParams);
         return new Request(
             'POST',
             $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
             $headers,
             $httpBody
         );
     }
uploadFileWithHttpInfo()
Ally\PetStore\Api\PetApi::uploadFileWithHttpInfo ($pet_id, $additional_metadata = null, $file = null)
Operation uploadFileWithHttpInfo.
uploads an image
Parameters
int $pet_id ID of pet to update (required)
string $additional_metadata Additional data to pass to server (optional)
\SplFileObject $file file to upload (optional)
Exceptions
Definition at line 2078 of file PetApi.php.
References Ally\PetStore\Api\PetApi\createHttpClientOption(), Ally\PetStore\ApiException\getResponseBody(), Ally\PetStore\ApiException\getResponseHeaders(), Ally\PetStore\ApiException\setResponseObject(), and Ally\PetStore\Api\PetApi\uploadFileRequest().
Referenced by Ally\PetStore\Api\PetApi\uploadFile().
     {
         $request = $this->uploadFileRequest($pet_id, $additional_metadata, $file);
         try {
             $options = $this->createHttpClientOption();
             try {
                 $response = $this->client->send($request, $options);
             } catch (RequestException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                     $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                 );
             } catch (ConnectException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     null,
                     null
                 );
             }
             $statusCode = $response->getStatusCode();
             if ($statusCode < 200 || $statusCode > 299) {
                 throw new ApiException(
                     sprintf(
                         '[%d] Error connecting to the API (%s)',
                         $statusCode,
                         (string) $request->getUri()
                     ),
                     $statusCode,
                     $response->getHeaders(),
                     (string) $response->getBody()
                 );
             }
             switch($statusCode) {
                 case 200:
                     if ('\Ally\PetStore\Schema\ApiResponse' === '\SplFileObject') {
                         $content = $response->getBody(); //stream goes to serializer
                     } else {
                         $content = (string) $response->getBody();
                         if ('\Ally\PetStore\Schema\ApiResponse' !== 'string') {
                             $content = json_decode($content);
                         }
                     }
                     return [
                         ObjectSerializer::deserialize($content, '\Ally\PetStore\Schema\ApiResponse', []),
                         $response->getStatusCode(),
                         $response->getHeaders()
                     ];
             }
             $returnType = '\Ally\PetStore\Schema\ApiResponse';
             if ($returnType === '\SplFileObject') {
                 $content = $response->getBody(); //stream goes to serializer
             } else {
                 $content = (string) $response->getBody();
                 if ($returnType !== 'string') {
                     $content = json_decode($content);
                 }
             }
             return [
                 ObjectSerializer::deserialize($content, $returnType, []),
                 $response->getStatusCode(),
                 $response->getHeaders()
             ];
         } catch (ApiException $e) {
             switch ($e->getCode()) {
                 case 200:
                     $data = ObjectSerializer::deserialize(
                         $e->getResponseBody(),
                         '\Ally\PetStore\Schema\ApiResponse',
                         $e->getResponseHeaders()
                     );
                     $e->setResponseObject($data);
                     break;
             }
             throw $e;
         }
     }
Member Data Documentation
$client
Ally\PetStore\Api\PetApi::$client protected
Definition at line 55 of file PetApi.php.
Referenced by Ally\PetStore\Api\PetApi\__construct().
$config
Ally\PetStore\Api\PetApi::$config protected
Definition at line 60 of file PetApi.php.
Referenced by Ally\PetStore\Api\PetApi\__construct(), and Ally\PetStore\Api\PetApi\getConfig().
$headerSelector
Ally\PetStore\Api\PetApi::$headerSelector protected
Definition at line 65 of file PetApi.php.
$hostIndex
Ally\PetStore\Api\PetApi::$hostIndex protected
Definition at line 70 of file PetApi.php.
Referenced by Ally\PetStore\Api\PetApi\__construct(), Ally\PetStore\Api\PetApi\getHostIndex(), and Ally\PetStore\Api\PetApi\setHostIndex().
The documentation for this class was generated from the following file:
src/Api/PetApi.php