Ally'sPetStoreAPI: Ally\PetStore\Api\UserApi Class Reference
Ally\PetStore\Api\UserApi Class Reference
Public Member Functions
__construct (ClientInterface $client=null, Configuration $config=null, HeaderSelector $selector=null, $hostIndex=0)
setHostIndex ($hostIndex)
Set the host index.
getHostIndex ()
Get the host index.
getConfig ()
createUser ($user)
Operation createUser.
createUserWithHttpInfo ($user)
Operation createUserWithHttpInfo.
createUserAsync ($user)
Operation createUserAsync.
createUserAsyncWithHttpInfo ($user)
Operation createUserAsyncWithHttpInfo.
createUserRequest ($user)
Create request for operation 'createUser'.
createUsersWithArrayInput ($user)
Operation createUsersWithArrayInput.
createUsersWithArrayInputWithHttpInfo ($user)
Operation createUsersWithArrayInputWithHttpInfo.
createUsersWithArrayInputAsync ($user)
Operation createUsersWithArrayInputAsync.
createUsersWithArrayInputAsyncWithHttpInfo ($user)
Operation createUsersWithArrayInputAsyncWithHttpInfo.
createUsersWithArrayInputRequest ($user)
Create request for operation 'createUsersWithArrayInput'.
createUsersWithListInput ($user)
Operation createUsersWithListInput.
createUsersWithListInputWithHttpInfo ($user)
Operation createUsersWithListInputWithHttpInfo.
createUsersWithListInputAsync ($user)
Operation createUsersWithListInputAsync.
createUsersWithListInputAsyncWithHttpInfo ($user)
Operation createUsersWithListInputAsyncWithHttpInfo.
createUsersWithListInputRequest ($user)
Create request for operation 'createUsersWithListInput'.
deleteUser ($username)
Operation deleteUser.
deleteUserWithHttpInfo ($username)
Operation deleteUserWithHttpInfo.
deleteUserAsync ($username)
Operation deleteUserAsync.
deleteUserAsyncWithHttpInfo ($username)
Operation deleteUserAsyncWithHttpInfo.
deleteUserRequest ($username)
Create request for operation 'deleteUser'.
getUserByName ($username)
Operation getUserByName.
getUserByNameWithHttpInfo ($username)
Operation getUserByNameWithHttpInfo.
getUserByNameAsync ($username)
Operation getUserByNameAsync.
getUserByNameAsyncWithHttpInfo ($username)
Operation getUserByNameAsyncWithHttpInfo.
getUserByNameRequest ($username)
Create request for operation 'getUserByName'.
loginUser ($username, $password)
Operation loginUser.
loginUserWithHttpInfo ($username, $password)
Operation loginUserWithHttpInfo.
loginUserAsync ($username, $password)
Operation loginUserAsync.
loginUserAsyncWithHttpInfo ($username, $password)
Operation loginUserAsyncWithHttpInfo.
loginUserRequest ($username, $password)
Create request for operation 'loginUser'.
logoutUser ()
Operation logoutUser.
logoutUserWithHttpInfo ()
Operation logoutUserWithHttpInfo.
logoutUserAsync ()
Operation logoutUserAsync.
logoutUserAsyncWithHttpInfo ()
Operation logoutUserAsyncWithHttpInfo.
logoutUserRequest ()
Create request for operation 'logoutUser'.
updateUser ($username, $user)
Operation updateUser.
updateUserWithHttpInfo ($username, $user)
Operation updateUserWithHttpInfo.
updateUserAsync ($username, $user)
Operation updateUserAsync.
updateUserAsyncWithHttpInfo ($username, $user)
Operation updateUserAsyncWithHttpInfo.
updateUserRequest ($username, $user)
Create request for operation 'updateUser'.
Protected Member Functions
createHttpClientOption ()
Create http client option.
Protected Attributes
$client
$config
$headerSelector
$hostIndex
Detailed Description
Definition at line 50 of file UserApi.php.
Constructor & Destructor Documentation
__construct()
Ally\PetStore\Api\UserApi::__construct (ClientInterface $client = null, Configuration $config = null, HeaderSelector $selector = null, $hostIndex = 0)
Parameters
ClientInterface $client
Configuration $config
HeaderSelector $selector
int $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
Definition at line 78 of file UserApi.php.
References Ally\PetStore\Api\UserApi\$client, Ally\PetStore\Api\UserApi\$config, and Ally\PetStore\Api\UserApi\$hostIndex.
       {
         $this->client = $client ?: new Client();
         $this->config = $config ?: new Configuration();
         $this->headerSelector = $selector ?: new HeaderSelector();
         $this->hostIndex = $hostIndex;
     }
Member Function Documentation
createHttpClientOption()
Ally\PetStore\Api\UserApi::createHttpClientOption () protected
Create http client option.
Exceptions
Definition at line 2104 of file UserApi.php.
Referenced by Ally\PetStore\Api\UserApi\createUserAsyncWithHttpInfo(), Ally\PetStore\Api\UserApi\createUsersWithArrayInputAsyncWithHttpInfo(), Ally\PetStore\Api\UserApi\createUsersWithArrayInputWithHttpInfo(), Ally\PetStore\Api\UserApi\createUsersWithListInputAsyncWithHttpInfo(), Ally\PetStore\Api\UserApi\createUsersWithListInputWithHttpInfo(), Ally\PetStore\Api\UserApi\createUserWithHttpInfo(), Ally\PetStore\Api\UserApi\deleteUserAsyncWithHttpInfo(), Ally\PetStore\Api\UserApi\deleteUserWithHttpInfo(), Ally\PetStore\Api\UserApi\getUserByNameAsyncWithHttpInfo(), Ally\PetStore\Api\UserApi\getUserByNameWithHttpInfo(), Ally\PetStore\Api\UserApi\loginUserAsyncWithHttpInfo(), Ally\PetStore\Api\UserApi\loginUserWithHttpInfo(), Ally\PetStore\Api\UserApi\logoutUserAsyncWithHttpInfo(), Ally\PetStore\Api\UserApi\logoutUserWithHttpInfo(), Ally\PetStore\Api\UserApi\updateUserAsyncWithHttpInfo(), and Ally\PetStore\Api\UserApi\updateUserWithHttpInfo().
     {
         $options = [];
         if ($this->config->getDebug()) {
             $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
             if (!$options[RequestOptions::DEBUG]) {
                 throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
             }
         }
         return $options;
     }
createUser()
Ally\PetStore\Api\UserApi::createUser ($user)
Operation createUser.
Create user
Parameters
\Ally\PetStore\Schema\User $user Created user object (required)
Exceptions
Definition at line 129 of file UserApi.php.
References Ally\PetStore\Api\UserApi\createUserWithHttpInfo().
     {
         $this->createUserWithHttpInfo($user);
     }
createUserAsync()
Ally\PetStore\Api\UserApi::createUserAsync ($user)
Operation createUserAsync.
Create user
Parameters
\Ally\PetStore\Schema\User $user Created user object (required)
Exceptions
Definition at line 203 of file UserApi.php.
References Ally\PetStore\Api\UserApi\createUserAsyncWithHttpInfo().
     {
         return $this->createUserAsyncWithHttpInfo($user)
             ->then(
                 function ($response) {
                     return $response[0];
                 }
             );
     }
createUserAsyncWithHttpInfo()
Ally\PetStore\Api\UserApi::createUserAsyncWithHttpInfo ($user)
Operation createUserAsyncWithHttpInfo.
Create user
Parameters
\Ally\PetStore\Schema\User $user Created user object (required)
Exceptions
Definition at line 223 of file UserApi.php.
References Ally\PetStore\Api\UserApi\createHttpClientOption(), and Ally\PetStore\Api\UserApi\createUserRequest().
Referenced by Ally\PetStore\Api\UserApi\createUserAsync().
     {
         $returnType = '';
         $request = $this->createUserRequest($user);
         return $this->client
             ->sendAsync($request, $this->createHttpClientOption())
             ->then(
                 function ($response) use ($returnType) {
                     return [null, $response->getStatusCode(), $response->getHeaders()];
                 },
                 function ($exception) {
                     $response = $exception->getResponse();
                     $statusCode = $response->getStatusCode();
                     throw new ApiException(
                         sprintf(
                             '[%d] Error connecting to the API (%s)',
                             $statusCode,
                             $exception->getRequest()->getUri()
                         ),
                         $statusCode,
                         $response->getHeaders(),
                         (string) $response->getBody()
                     );
                 }
             );
     }
createUserRequest()
Ally\PetStore\Api\UserApi::createUserRequest ($user)
Create request for operation 'createUser'.
Parameters
\Ally\PetStore\Schema\User $user Created user object (required)
Exceptions
Definition at line 259 of file UserApi.php.
References Ally\PetStore\ObjectSerializer\buildQuery(), and Ally\PetStore\ObjectSerializer\sanitizeForSerialization().
Referenced by Ally\PetStore\Api\UserApi\createUserAsyncWithHttpInfo(), and Ally\PetStore\Api\UserApi\createUserWithHttpInfo().
     {
         // verify the required parameter 'user' is set
         if ($user === null || (is_array($user) && count($user) === 0)) {
             throw new \InvalidArgumentException(
                 'Missing the required parameter $user when calling createUser'
             );
         }
         $resourcePath = '/user';
         $formParams = [];
         $queryParams = [];
         $headerParams = [];
         $httpBody = '';
         $multipart = false;
         if ($multipart) {
             $headers = $this->headerSelector->selectHeadersForMultipart(
                 []
             );
         } else {
             $headers = $this->headerSelector->selectHeaders(
                 [],
                 ['application/json']
             );
         }
         // for model (json/xml)
         if (isset($user)) {
             if ($headers['Content-Type'] === 'application/json') {
                 $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($user));
             } else {
                 $httpBody = $user;
             }
         } elseif (count($formParams) > 0) {
             if ($multipart) {
                 $multipartContents = [];
                 foreach ($formParams as $formParamName => $formParamValue) {
                     $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                     foreach ($formParamValueItems as $formParamValueItem) {
                         $multipartContents[] = [
                             'name' => $formParamName,
                             'contents' => $formParamValueItem
                         ];
                     }
                 }
                 // for HTTP post (form)
                 $httpBody = new MultipartStream($multipartContents);
             } elseif ($headers['Content-Type'] === 'application/json') {
                 $httpBody = \GuzzleHttp\json_encode($formParams);
             } else {
                 // for HTTP post (form)
                 $httpBody = ObjectSerializer::buildQuery($formParams);
             }
         }
         // this endpoint requires API key authentication
         $apiKey = $this->config->getApiKeyWithPrefix('api_key');
         if ($apiKey !== null) {
             $headers['api_key'] = $apiKey;
         }
         $defaultHeaders = [];
         if ($this->config->getUserAgent()) {
             $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
         }
         $headers = array_merge(
             $defaultHeaders,
             $headerParams,
             $headers
         );
         $operationHost = $this->config->getHost();
         $query = ObjectSerializer::buildQuery($queryParams);
         return new Request(
             'POST',
             $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
             $headers,
             $httpBody
         );
     }
createUsersWithArrayInput()
Ally\PetStore\Api\UserApi::createUsersWithArrayInput ($user)
Operation createUsersWithArrayInput.
Creates list of users with given input array
Parameters
Definition at line 360 of file UserApi.php.
References Ally\PetStore\Api\UserApi\createUsersWithArrayInputWithHttpInfo().
     {
         $this->createUsersWithArrayInputWithHttpInfo($user);
     }
createUsersWithArrayInputAsync()
Ally\PetStore\Api\UserApi::createUsersWithArrayInputAsync ($user)
Operation createUsersWithArrayInputAsync.
Creates list of users with given input array
Parameters
Definition at line 434 of file UserApi.php.
References Ally\PetStore\Api\UserApi\createUsersWithArrayInputAsyncWithHttpInfo().
     {
         return $this->createUsersWithArrayInputAsyncWithHttpInfo($user)
             ->then(
                 function ($response) {
                     return $response[0];
                 }
             );
     }
createUsersWithArrayInputAsyncWithHttpInfo()
Ally\PetStore\Api\UserApi::createUsersWithArrayInputAsyncWithHttpInfo ($user)
Operation createUsersWithArrayInputAsyncWithHttpInfo.
Creates list of users with given input array
Parameters
Definition at line 454 of file UserApi.php.
References Ally\PetStore\Api\UserApi\createHttpClientOption(), and Ally\PetStore\Api\UserApi\createUsersWithArrayInputRequest().
Referenced by Ally\PetStore\Api\UserApi\createUsersWithArrayInputAsync().
     {
         $returnType = '';
         $request = $this->createUsersWithArrayInputRequest($user);
         return $this->client
             ->sendAsync($request, $this->createHttpClientOption())
             ->then(
                 function ($response) use ($returnType) {
                     return [null, $response->getStatusCode(), $response->getHeaders()];
                 },
                 function ($exception) {
                     $response = $exception->getResponse();
                     $statusCode = $response->getStatusCode();
                     throw new ApiException(
                         sprintf(
                             '[%d] Error connecting to the API (%s)',
                             $statusCode,
                             $exception->getRequest()->getUri()
                         ),
                         $statusCode,
                         $response->getHeaders(),
                         (string) $response->getBody()
                     );
                 }
             );
     }
createUsersWithArrayInputRequest()
Ally\PetStore\Api\UserApi::createUsersWithArrayInputRequest ($user)
Create request for operation 'createUsersWithArrayInput'.
Parameters
Definition at line 490 of file UserApi.php.
References Ally\PetStore\ObjectSerializer\buildQuery(), and Ally\PetStore\ObjectSerializer\sanitizeForSerialization().
Referenced by Ally\PetStore\Api\UserApi\createUsersWithArrayInputAsyncWithHttpInfo(), and Ally\PetStore\Api\UserApi\createUsersWithArrayInputWithHttpInfo().
     {
         // verify the required parameter 'user' is set
         if ($user === null || (is_array($user) && count($user) === 0)) {
             throw new \InvalidArgumentException(
                 'Missing the required parameter $user when calling createUsersWithArrayInput'
             );
         }
         $resourcePath = '/user/createWithArray';
         $formParams = [];
         $queryParams = [];
         $headerParams = [];
         $httpBody = '';
         $multipart = false;
         if ($multipart) {
             $headers = $this->headerSelector->selectHeadersForMultipart(
                 []
             );
         } else {
             $headers = $this->headerSelector->selectHeaders(
                 [],
                 ['application/json']
             );
         }
         // for model (json/xml)
         if (isset($user)) {
             if ($headers['Content-Type'] === 'application/json') {
                 $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($user));
             } else {
                 $httpBody = $user;
             }
         } elseif (count($formParams) > 0) {
             if ($multipart) {
                 $multipartContents = [];
                 foreach ($formParams as $formParamName => $formParamValue) {
                     $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                     foreach ($formParamValueItems as $formParamValueItem) {
                         $multipartContents[] = [
                             'name' => $formParamName,
                             'contents' => $formParamValueItem
                         ];
                     }
                 }
                 // for HTTP post (form)
                 $httpBody = new MultipartStream($multipartContents);
             } elseif ($headers['Content-Type'] === 'application/json') {
                 $httpBody = \GuzzleHttp\json_encode($formParams);
             } else {
                 // for HTTP post (form)
                 $httpBody = ObjectSerializer::buildQuery($formParams);
             }
         }
         // this endpoint requires API key authentication
         $apiKey = $this->config->getApiKeyWithPrefix('api_key');
         if ($apiKey !== null) {
             $headers['api_key'] = $apiKey;
         }
         $defaultHeaders = [];
         if ($this->config->getUserAgent()) {
             $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
         }
         $headers = array_merge(
             $defaultHeaders,
             $headerParams,
             $headers
         );
         $operationHost = $this->config->getHost();
         $query = ObjectSerializer::buildQuery($queryParams);
         return new Request(
             'POST',
             $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
             $headers,
             $httpBody
         );
     }
createUsersWithArrayInputWithHttpInfo()
Ally\PetStore\Api\UserApi::createUsersWithArrayInputWithHttpInfo ($user)
Operation createUsersWithArrayInputWithHttpInfo.
Creates list of users with given input array
Parameters
Definition at line 376 of file UserApi.php.
References Ally\PetStore\Api\UserApi\createHttpClientOption(), and Ally\PetStore\Api\UserApi\createUsersWithArrayInputRequest().
Referenced by Ally\PetStore\Api\UserApi\createUsersWithArrayInput().
     {
         $request = $this->createUsersWithArrayInputRequest($user);
         try {
             $options = $this->createHttpClientOption();
             try {
                 $response = $this->client->send($request, $options);
             } catch (RequestException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                     $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                 );
             } catch (ConnectException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     null,
                     null
                 );
             }
             $statusCode = $response->getStatusCode();
             if ($statusCode < 200 || $statusCode > 299) {
                 throw new ApiException(
                     sprintf(
                         '[%d] Error connecting to the API (%s)',
                         $statusCode,
                         (string) $request->getUri()
                     ),
                     $statusCode,
                     $response->getHeaders(),
                     (string) $response->getBody()
                 );
             }
             return [null, $statusCode, $response->getHeaders()];
         } catch (ApiException $e) {
             switch ($e->getCode()) {
             }
             throw $e;
         }
     }
createUsersWithListInput()
Ally\PetStore\Api\UserApi::createUsersWithListInput ($user)
Operation createUsersWithListInput.
Creates list of users with given input array
Parameters
Definition at line 591 of file UserApi.php.
References Ally\PetStore\Api\UserApi\createUsersWithListInputWithHttpInfo().
     {
         $this->createUsersWithListInputWithHttpInfo($user);
     }
createUsersWithListInputAsync()
Ally\PetStore\Api\UserApi::createUsersWithListInputAsync ($user)
Operation createUsersWithListInputAsync.
Creates list of users with given input array
Parameters
Definition at line 665 of file UserApi.php.
References Ally\PetStore\Api\UserApi\createUsersWithListInputAsyncWithHttpInfo().
     {
         return $this->createUsersWithListInputAsyncWithHttpInfo($user)
             ->then(
                 function ($response) {
                     return $response[0];
                 }
             );
     }
createUsersWithListInputAsyncWithHttpInfo()
Ally\PetStore\Api\UserApi::createUsersWithListInputAsyncWithHttpInfo ($user)
Operation createUsersWithListInputAsyncWithHttpInfo.
Creates list of users with given input array
Parameters
Definition at line 685 of file UserApi.php.
References Ally\PetStore\Api\UserApi\createHttpClientOption(), and Ally\PetStore\Api\UserApi\createUsersWithListInputRequest().
Referenced by Ally\PetStore\Api\UserApi\createUsersWithListInputAsync().
     {
         $returnType = '';
         $request = $this->createUsersWithListInputRequest($user);
         return $this->client
             ->sendAsync($request, $this->createHttpClientOption())
             ->then(
                 function ($response) use ($returnType) {
                     return [null, $response->getStatusCode(), $response->getHeaders()];
                 },
                 function ($exception) {
                     $response = $exception->getResponse();
                     $statusCode = $response->getStatusCode();
                     throw new ApiException(
                         sprintf(
                             '[%d] Error connecting to the API (%s)',
                             $statusCode,
                             $exception->getRequest()->getUri()
                         ),
                         $statusCode,
                         $response->getHeaders(),
                         (string) $response->getBody()
                     );
                 }
             );
     }
createUsersWithListInputRequest()
Ally\PetStore\Api\UserApi::createUsersWithListInputRequest ($user)
Create request for operation 'createUsersWithListInput'.
Parameters
Definition at line 721 of file UserApi.php.
References Ally\PetStore\ObjectSerializer\buildQuery(), and Ally\PetStore\ObjectSerializer\sanitizeForSerialization().
Referenced by Ally\PetStore\Api\UserApi\createUsersWithListInputAsyncWithHttpInfo(), and Ally\PetStore\Api\UserApi\createUsersWithListInputWithHttpInfo().
     {
         // verify the required parameter 'user' is set
         if ($user === null || (is_array($user) && count($user) === 0)) {
             throw new \InvalidArgumentException(
                 'Missing the required parameter $user when calling createUsersWithListInput'
             );
         }
         $resourcePath = '/user/createWithList';
         $formParams = [];
         $queryParams = [];
         $headerParams = [];
         $httpBody = '';
         $multipart = false;
         if ($multipart) {
             $headers = $this->headerSelector->selectHeadersForMultipart(
                 []
             );
         } else {
             $headers = $this->headerSelector->selectHeaders(
                 [],
                 ['application/json']
             );
         }
         // for model (json/xml)
         if (isset($user)) {
             if ($headers['Content-Type'] === 'application/json') {
                 $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($user));
             } else {
                 $httpBody = $user;
             }
         } elseif (count($formParams) > 0) {
             if ($multipart) {
                 $multipartContents = [];
                 foreach ($formParams as $formParamName => $formParamValue) {
                     $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                     foreach ($formParamValueItems as $formParamValueItem) {
                         $multipartContents[] = [
                             'name' => $formParamName,
                             'contents' => $formParamValueItem
                         ];
                     }
                 }
                 // for HTTP post (form)
                 $httpBody = new MultipartStream($multipartContents);
             } elseif ($headers['Content-Type'] === 'application/json') {
                 $httpBody = \GuzzleHttp\json_encode($formParams);
             } else {
                 // for HTTP post (form)
                 $httpBody = ObjectSerializer::buildQuery($formParams);
             }
         }
         // this endpoint requires API key authentication
         $apiKey = $this->config->getApiKeyWithPrefix('api_key');
         if ($apiKey !== null) {
             $headers['api_key'] = $apiKey;
         }
         $defaultHeaders = [];
         if ($this->config->getUserAgent()) {
             $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
         }
         $headers = array_merge(
             $defaultHeaders,
             $headerParams,
             $headers
         );
         $operationHost = $this->config->getHost();
         $query = ObjectSerializer::buildQuery($queryParams);
         return new Request(
             'POST',
             $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
             $headers,
             $httpBody
         );
     }
createUsersWithListInputWithHttpInfo()
Ally\PetStore\Api\UserApi::createUsersWithListInputWithHttpInfo ($user)
Operation createUsersWithListInputWithHttpInfo.
Creates list of users with given input array
Parameters
Definition at line 607 of file UserApi.php.
References Ally\PetStore\Api\UserApi\createHttpClientOption(), and Ally\PetStore\Api\UserApi\createUsersWithListInputRequest().
Referenced by Ally\PetStore\Api\UserApi\createUsersWithListInput().
     {
         $request = $this->createUsersWithListInputRequest($user);
         try {
             $options = $this->createHttpClientOption();
             try {
                 $response = $this->client->send($request, $options);
             } catch (RequestException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                     $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                 );
             } catch (ConnectException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     null,
                     null
                 );
             }
             $statusCode = $response->getStatusCode();
             if ($statusCode < 200 || $statusCode > 299) {
                 throw new ApiException(
                     sprintf(
                         '[%d] Error connecting to the API (%s)',
                         $statusCode,
                         (string) $request->getUri()
                     ),
                     $statusCode,
                     $response->getHeaders(),
                     (string) $response->getBody()
                 );
             }
             return [null, $statusCode, $response->getHeaders()];
         } catch (ApiException $e) {
             switch ($e->getCode()) {
             }
             throw $e;
         }
     }
createUserWithHttpInfo()
Ally\PetStore\Api\UserApi::createUserWithHttpInfo ($user)
Operation createUserWithHttpInfo.
Create user
Parameters
\Ally\PetStore\Schema\User $user Created user object (required)
Exceptions
Definition at line 145 of file UserApi.php.
References Ally\PetStore\Api\UserApi\createHttpClientOption(), and Ally\PetStore\Api\UserApi\createUserRequest().
Referenced by Ally\PetStore\Api\UserApi\createUser().
     {
         $request = $this->createUserRequest($user);
         try {
             $options = $this->createHttpClientOption();
             try {
                 $response = $this->client->send($request, $options);
             } catch (RequestException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                     $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                 );
             } catch (ConnectException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     null,
                     null
                 );
             }
             $statusCode = $response->getStatusCode();
             if ($statusCode < 200 || $statusCode > 299) {
                 throw new ApiException(
                     sprintf(
                         '[%d] Error connecting to the API (%s)',
                         $statusCode,
                         (string) $request->getUri()
                     ),
                     $statusCode,
                     $response->getHeaders(),
                     (string) $response->getBody()
                 );
             }
             return [null, $statusCode, $response->getHeaders()];
         } catch (ApiException $e) {
             switch ($e->getCode()) {
             }
             throw $e;
         }
     }
deleteUser()
Ally\PetStore\Api\UserApi::deleteUser ($username)
Operation deleteUser.
Delete user
Parameters
string $username The name that needs to be deleted (required)
Exceptions
Definition at line 822 of file UserApi.php.
References Ally\PetStore\Api\UserApi\deleteUserWithHttpInfo().
     {
         $this->deleteUserWithHttpInfo($username);
     }
deleteUserAsync()
Ally\PetStore\Api\UserApi::deleteUserAsync ($username)
Operation deleteUserAsync.
Delete user
Parameters
string $username The name that needs to be deleted (required)
Exceptions
Definition at line 896 of file UserApi.php.
References Ally\PetStore\Api\UserApi\deleteUserAsyncWithHttpInfo().
     {
         return $this->deleteUserAsyncWithHttpInfo($username)
             ->then(
                 function ($response) {
                     return $response[0];
                 }
             );
     }
deleteUserAsyncWithHttpInfo()
Ally\PetStore\Api\UserApi::deleteUserAsyncWithHttpInfo ($username)
Operation deleteUserAsyncWithHttpInfo.
Delete user
Parameters
string $username The name that needs to be deleted (required)
Exceptions
Definition at line 916 of file UserApi.php.
References Ally\PetStore\Api\UserApi\createHttpClientOption(), and Ally\PetStore\Api\UserApi\deleteUserRequest().
Referenced by Ally\PetStore\Api\UserApi\deleteUserAsync().
     {
         $returnType = '';
         $request = $this->deleteUserRequest($username);
         return $this->client
             ->sendAsync($request, $this->createHttpClientOption())
             ->then(
                 function ($response) use ($returnType) {
                     return [null, $response->getStatusCode(), $response->getHeaders()];
                 },
                 function ($exception) {
                     $response = $exception->getResponse();
                     $statusCode = $response->getStatusCode();
                     throw new ApiException(
                         sprintf(
                             '[%d] Error connecting to the API (%s)',
                             $statusCode,
                             $exception->getRequest()->getUri()
                         ),
                         $statusCode,
                         $response->getHeaders(),
                         (string) $response->getBody()
                     );
                 }
             );
     }
deleteUserRequest()
Ally\PetStore\Api\UserApi::deleteUserRequest ($username)
Create request for operation 'deleteUser'.
Parameters
string $username The name that needs to be deleted (required)
Exceptions
Definition at line 952 of file UserApi.php.
References Ally\PetStore\ObjectSerializer\buildQuery(), and Ally\PetStore\ObjectSerializer\toPathValue().
Referenced by Ally\PetStore\Api\UserApi\deleteUserAsyncWithHttpInfo(), and Ally\PetStore\Api\UserApi\deleteUserWithHttpInfo().
     {
         // verify the required parameter 'username' is set
         if ($username === null || (is_array($username) && count($username) === 0)) {
             throw new \InvalidArgumentException(
                 'Missing the required parameter $username when calling deleteUser'
             );
         }
         $resourcePath = '/user/{username}';
         $formParams = [];
         $queryParams = [];
         $headerParams = [];
         $httpBody = '';
         $multipart = false;
         // path params
         if ($username !== null) {
             $resourcePath = str_replace(
                 '{' . 'username' . '}',
                 ObjectSerializer::toPathValue($username),
                 $resourcePath
             );
         }
         if ($multipart) {
             $headers = $this->headerSelector->selectHeadersForMultipart(
                 []
             );
         } else {
             $headers = $this->headerSelector->selectHeaders(
                 [],
                 []
             );
         }
         // for model (json/xml)
         if (count($formParams) > 0) {
             if ($multipart) {
                 $multipartContents = [];
                 foreach ($formParams as $formParamName => $formParamValue) {
                     $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                     foreach ($formParamValueItems as $formParamValueItem) {
                         $multipartContents[] = [
                             'name' => $formParamName,
                             'contents' => $formParamValueItem
                         ];
                     }
                 }
                 // for HTTP post (form)
                 $httpBody = new MultipartStream($multipartContents);
             } elseif ($headers['Content-Type'] === 'application/json') {
                 $httpBody = \GuzzleHttp\json_encode($formParams);
             } else {
                 // for HTTP post (form)
                 $httpBody = ObjectSerializer::buildQuery($formParams);
             }
         }
         // this endpoint requires API key authentication
         $apiKey = $this->config->getApiKeyWithPrefix('api_key');
         if ($apiKey !== null) {
             $headers['api_key'] = $apiKey;
         }
         $defaultHeaders = [];
         if ($this->config->getUserAgent()) {
             $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
         }
         $headers = array_merge(
             $defaultHeaders,
             $headerParams,
             $headers
         );
         $operationHost = $this->config->getHost();
         $query = ObjectSerializer::buildQuery($queryParams);
         return new Request(
             'DELETE',
             $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
             $headers,
             $httpBody
         );
     }
deleteUserWithHttpInfo()
Ally\PetStore\Api\UserApi::deleteUserWithHttpInfo ($username)
Operation deleteUserWithHttpInfo.
Delete user
Parameters
string $username The name that needs to be deleted (required)
Exceptions
Definition at line 838 of file UserApi.php.
References Ally\PetStore\Api\UserApi\createHttpClientOption(), and Ally\PetStore\Api\UserApi\deleteUserRequest().
Referenced by Ally\PetStore\Api\UserApi\deleteUser().
     {
         $request = $this->deleteUserRequest($username);
         try {
             $options = $this->createHttpClientOption();
             try {
                 $response = $this->client->send($request, $options);
             } catch (RequestException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                     $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                 );
             } catch (ConnectException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     null,
                     null
                 );
             }
             $statusCode = $response->getStatusCode();
             if ($statusCode < 200 || $statusCode > 299) {
                 throw new ApiException(
                     sprintf(
                         '[%d] Error connecting to the API (%s)',
                         $statusCode,
                         (string) $request->getUri()
                     ),
                     $statusCode,
                     $response->getHeaders(),
                     (string) $response->getBody()
                 );
             }
             return [null, $statusCode, $response->getHeaders()];
         } catch (ApiException $e) {
             switch ($e->getCode()) {
             }
             throw $e;
         }
     }
getConfig()
Ally\PetStore\Api\UserApi::getConfig ()
Returns
Configuration
Definition at line 113 of file UserApi.php.
References Ally\PetStore\Api\UserApi\$config.
     {
         return $this->config;
     }
getHostIndex()
Ally\PetStore\Api\UserApi::getHostIndex ()
Get the host index.
Returns
int Host index
Definition at line 105 of file UserApi.php.
References Ally\PetStore\Api\UserApi\$hostIndex.
     {
         return $this->hostIndex;
     }
getUserByName()
Ally\PetStore\Api\UserApi::getUserByName ($username)
Operation getUserByName.
Get user by user name
Parameters
string $username The name that needs to be fetched. Use user1 for testing. (required)
Exceptions
Definition at line 1055 of file UserApi.php.
References Ally\PetStore\Api\UserApi\getUserByNameWithHttpInfo().
     {
         list($response) = $this->getUserByNameWithHttpInfo($username);
         return $response;
     }
getUserByNameAsync()
Ally\PetStore\Api\UserApi::getUserByNameAsync ($username)
Operation getUserByNameAsync.
Get user by user name
Parameters
string $username The name that needs to be fetched. Use user1 for testing. (required)
Exceptions
Definition at line 1170 of file UserApi.php.
References Ally\PetStore\Api\UserApi\getUserByNameAsyncWithHttpInfo().
     {
         return $this->getUserByNameAsyncWithHttpInfo($username)
             ->then(
                 function ($response) {
                     return $response[0];
                 }
             );
     }
getUserByNameAsyncWithHttpInfo()
Ally\PetStore\Api\UserApi::getUserByNameAsyncWithHttpInfo ($username)
Operation getUserByNameAsyncWithHttpInfo.
Get user by user name
Parameters
string $username The name that needs to be fetched. Use user1 for testing. (required)
Exceptions
Definition at line 1190 of file UserApi.php.
References Ally\PetStore\Api\UserApi\createHttpClientOption(), and Ally\PetStore\Api\UserApi\getUserByNameRequest().
Referenced by Ally\PetStore\Api\UserApi\getUserByNameAsync().
     {
         $returnType = '\Ally\PetStore\Schema\User';
         $request = $this->getUserByNameRequest($username);
         return $this->client
             ->sendAsync($request, $this->createHttpClientOption())
             ->then(
                 function ($response) use ($returnType) {
                     if ($returnType === '\SplFileObject') {
                         $content = $response->getBody(); //stream goes to serializer
                     } else {
                         $content = (string) $response->getBody();
                         if ($returnType !== 'string') {
                             $content = json_decode($content);
                         }
                     }
                     return [
                         ObjectSerializer::deserialize($content, $returnType, []),
                         $response->getStatusCode(),
                         $response->getHeaders()
                     ];
                 },
                 function ($exception) {
                     $response = $exception->getResponse();
                     $statusCode = $response->getStatusCode();
                     throw new ApiException(
                         sprintf(
                             '[%d] Error connecting to the API (%s)',
                             $statusCode,
                             $exception->getRequest()->getUri()
                         ),
                         $statusCode,
                         $response->getHeaders(),
                         (string) $response->getBody()
                     );
                 }
             );
     }
getUserByNameRequest()
Ally\PetStore\Api\UserApi::getUserByNameRequest ($username)
Create request for operation 'getUserByName'.
Parameters
string $username The name that needs to be fetched. Use user1 for testing. (required)
Exceptions
Definition at line 1239 of file UserApi.php.
References Ally\PetStore\ObjectSerializer\buildQuery(), and Ally\PetStore\ObjectSerializer\toPathValue().
Referenced by Ally\PetStore\Api\UserApi\getUserByNameAsyncWithHttpInfo(), and Ally\PetStore\Api\UserApi\getUserByNameWithHttpInfo().
     {
         // verify the required parameter 'username' is set
         if ($username === null || (is_array($username) && count($username) === 0)) {
             throw new \InvalidArgumentException(
                 'Missing the required parameter $username when calling getUserByName'
             );
         }
         $resourcePath = '/user/{username}';
         $formParams = [];
         $queryParams = [];
         $headerParams = [];
         $httpBody = '';
         $multipart = false;
         // path params
         if ($username !== null) {
             $resourcePath = str_replace(
                 '{' . 'username' . '}',
                 ObjectSerializer::toPathValue($username),
                 $resourcePath
             );
         }
         if ($multipart) {
             $headers = $this->headerSelector->selectHeadersForMultipart(
                 ['application/xml', 'application/json']
             );
         } else {
             $headers = $this->headerSelector->selectHeaders(
                 ['application/xml', 'application/json'],
                 []
             );
         }
         // for model (json/xml)
         if (count($formParams) > 0) {
             if ($multipart) {
                 $multipartContents = [];
                 foreach ($formParams as $formParamName => $formParamValue) {
                     $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                     foreach ($formParamValueItems as $formParamValueItem) {
                         $multipartContents[] = [
                             'name' => $formParamName,
                             'contents' => $formParamValueItem
                         ];
                     }
                 }
                 // for HTTP post (form)
                 $httpBody = new MultipartStream($multipartContents);
             } elseif ($headers['Content-Type'] === 'application/json') {
                 $httpBody = \GuzzleHttp\json_encode($formParams);
             } else {
                 // for HTTP post (form)
                 $httpBody = ObjectSerializer::buildQuery($formParams);
             }
         }
         $defaultHeaders = [];
         if ($this->config->getUserAgent()) {
             $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
         }
         $headers = array_merge(
             $defaultHeaders,
             $headerParams,
             $headers
         );
         $operationHost = $this->config->getHost();
         $query = ObjectSerializer::buildQuery($queryParams);
         return new Request(
             'GET',
             $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
             $headers,
             $httpBody
         );
     }
getUserByNameWithHttpInfo()
Ally\PetStore\Api\UserApi::getUserByNameWithHttpInfo ($username)
Operation getUserByNameWithHttpInfo.
Get user by user name
Parameters
string $username The name that needs to be fetched. Use user1 for testing. (required)
Exceptions
Definition at line 1072 of file UserApi.php.
References Ally\PetStore\Api\UserApi\createHttpClientOption(), Ally\PetStore\ApiException\getResponseBody(), Ally\PetStore\ApiException\getResponseHeaders(), Ally\PetStore\Api\UserApi\getUserByNameRequest(), and Ally\PetStore\ApiException\setResponseObject().
Referenced by Ally\PetStore\Api\UserApi\getUserByName().
     {
         $request = $this->getUserByNameRequest($username);
         try {
             $options = $this->createHttpClientOption();
             try {
                 $response = $this->client->send($request, $options);
             } catch (RequestException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                     $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                 );
             } catch (ConnectException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     null,
                     null
                 );
             }
             $statusCode = $response->getStatusCode();
             if ($statusCode < 200 || $statusCode > 299) {
                 throw new ApiException(
                     sprintf(
                         '[%d] Error connecting to the API (%s)',
                         $statusCode,
                         (string) $request->getUri()
                     ),
                     $statusCode,
                     $response->getHeaders(),
                     (string) $response->getBody()
                 );
             }
             switch($statusCode) {
                 case 200:
                     if ('\Ally\PetStore\Schema\User' === '\SplFileObject') {
                         $content = $response->getBody(); //stream goes to serializer
                     } else {
                         $content = (string) $response->getBody();
                         if ('\Ally\PetStore\Schema\User' !== 'string') {
                             $content = json_decode($content);
                         }
                     }
                     return [
                         ObjectSerializer::deserialize($content, '\Ally\PetStore\Schema\User', []),
                         $response->getStatusCode(),
                         $response->getHeaders()
                     ];
             }
             $returnType = '\Ally\PetStore\Schema\User';
             if ($returnType === '\SplFileObject') {
                 $content = $response->getBody(); //stream goes to serializer
             } else {
                 $content = (string) $response->getBody();
                 if ($returnType !== 'string') {
                     $content = json_decode($content);
                 }
             }
             return [
                 ObjectSerializer::deserialize($content, $returnType, []),
                 $response->getStatusCode(),
                 $response->getHeaders()
             ];
         } catch (ApiException $e) {
             switch ($e->getCode()) {
                 case 200:
                     $data = ObjectSerializer::deserialize(
                         $e->getResponseBody(),
                         '\Ally\PetStore\Schema\User',
                         $e->getResponseHeaders()
                     );
                     $e->setResponseObject($data);
                     break;
             }
             throw $e;
         }
     }
loginUser()
Ally\PetStore\Api\UserApi::loginUser ($username, $password)
Operation loginUser.
Logs user into the system
Parameters
string $username The user name for login (required)
string $password The password for login in clear text (required)
Exceptions
Definition at line 1338 of file UserApi.php.
References Ally\PetStore\Api\UserApi\loginUserWithHttpInfo().
     {
         list($response) = $this->loginUserWithHttpInfo($username, $password);
         return $response;
     }
loginUserAsync()
Ally\PetStore\Api\UserApi::loginUserAsync ($username, $password)
Operation loginUserAsync.
Logs user into the system
Parameters
string $username The user name for login (required)
string $password The password for login in clear text (required)
Exceptions
Definition at line 1455 of file UserApi.php.
References Ally\PetStore\Api\UserApi\loginUserAsyncWithHttpInfo().
     {
         return $this->loginUserAsyncWithHttpInfo($username, $password)
             ->then(
                 function ($response) {
                     return $response[0];
                 }
             );
     }
loginUserAsyncWithHttpInfo()
Ally\PetStore\Api\UserApi::loginUserAsyncWithHttpInfo ($username, $password)
Operation loginUserAsyncWithHttpInfo.
Logs user into the system
Parameters
string $username The user name for login (required)
string $password The password for login in clear text (required)
Exceptions
Definition at line 1476 of file UserApi.php.
References Ally\PetStore\Api\UserApi\createHttpClientOption(), and Ally\PetStore\Api\UserApi\loginUserRequest().
Referenced by Ally\PetStore\Api\UserApi\loginUserAsync().
     {
         $returnType = 'string';
         $request = $this->loginUserRequest($username, $password);
         return $this->client
             ->sendAsync($request, $this->createHttpClientOption())
             ->then(
                 function ($response) use ($returnType) {
                     if ($returnType === '\SplFileObject') {
                         $content = $response->getBody(); //stream goes to serializer
                     } else {
                         $content = (string) $response->getBody();
                         if ($returnType !== 'string') {
                             $content = json_decode($content);
                         }
                     }
                     return [
                         ObjectSerializer::deserialize($content, $returnType, []),
                         $response->getStatusCode(),
                         $response->getHeaders()
                     ];
                 },
                 function ($exception) {
                     $response = $exception->getResponse();
                     $statusCode = $response->getStatusCode();
                     throw new ApiException(
                         sprintf(
                             '[%d] Error connecting to the API (%s)',
                             $statusCode,
                             $exception->getRequest()->getUri()
                         ),
                         $statusCode,
                         $response->getHeaders(),
                         (string) $response->getBody()
                     );
                 }
             );
     }
loginUserRequest()
Ally\PetStore\Api\UserApi::loginUserRequest ($username, $password)
Create request for operation 'loginUser'.
Parameters
string $username The user name for login (required)
string $password The password for login in clear text (required)
Exceptions
Definition at line 1526 of file UserApi.php.
References Ally\PetStore\ObjectSerializer\buildQuery(), and Ally\PetStore\ObjectSerializer\toQueryValue().
Referenced by Ally\PetStore\Api\UserApi\loginUserAsyncWithHttpInfo(), and Ally\PetStore\Api\UserApi\loginUserWithHttpInfo().
     {
         // verify the required parameter 'username' is set
         if ($username === null || (is_array($username) && count($username) === 0)) {
             throw new \InvalidArgumentException(
                 'Missing the required parameter $username when calling loginUser'
             );
         }
         if (!preg_match("/^[a-zA-Z0-9]+[a-zA-Z0-9\\.\\-_]*[a-zA-Z0-9]+$/", $username)) {
             throw new \InvalidArgumentException("invalid value for \"username\" when calling UserApi.loginUser, must conform to the pattern /^[a-zA-Z0-9]+[a-zA-Z0-9\\.\\-_]*[a-zA-Z0-9]+$/.");
         }
         // verify the required parameter 'password' is set
         if ($password === null || (is_array($password) && count($password) === 0)) {
             throw new \InvalidArgumentException(
                 'Missing the required parameter $password when calling loginUser'
             );
         }
         $resourcePath = '/user/login';
         $formParams = [];
         $queryParams = [];
         $headerParams = [];
         $httpBody = '';
         $multipart = false;
         // query params
         $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
             $username,
             'username', // param base name
             'string', // openApiType
             'form', // style
             true, // explode
             true // required
         ) ?? []);
         // query params
         $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
             $password,
             'password', // param base name
             'string', // openApiType
             'form', // style
             true, // explode
             true // required
         ) ?? []);
         if ($multipart) {
             $headers = $this->headerSelector->selectHeadersForMultipart(
                 ['application/xml', 'application/json']
             );
         } else {
             $headers = $this->headerSelector->selectHeaders(
                 ['application/xml', 'application/json'],
                 []
             );
         }
         // for model (json/xml)
         if (count($formParams) > 0) {
             if ($multipart) {
                 $multipartContents = [];
                 foreach ($formParams as $formParamName => $formParamValue) {
                     $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                     foreach ($formParamValueItems as $formParamValueItem) {
                         $multipartContents[] = [
                             'name' => $formParamName,
                             'contents' => $formParamValueItem
                         ];
                     }
                 }
                 // for HTTP post (form)
                 $httpBody = new MultipartStream($multipartContents);
             } elseif ($headers['Content-Type'] === 'application/json') {
                 $httpBody = \GuzzleHttp\json_encode($formParams);
             } else {
                 // for HTTP post (form)
                 $httpBody = ObjectSerializer::buildQuery($formParams);
             }
         }
         $defaultHeaders = [];
         if ($this->config->getUserAgent()) {
             $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
         }
         $headers = array_merge(
             $defaultHeaders,
             $headerParams,
             $headers
         );
         $operationHost = $this->config->getHost();
         $query = ObjectSerializer::buildQuery($queryParams);
         return new Request(
             'GET',
             $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
             $headers,
             $httpBody
         );
     }
loginUserWithHttpInfo()
Ally\PetStore\Api\UserApi::loginUserWithHttpInfo ($username, $password)
Operation loginUserWithHttpInfo.
Logs user into the system
Parameters
string $username The user name for login (required)
string $password The password for login in clear text (required)
Exceptions
Definition at line 1356 of file UserApi.php.
References Ally\PetStore\Api\UserApi\createHttpClientOption(), Ally\PetStore\ApiException\getResponseBody(), Ally\PetStore\ApiException\getResponseHeaders(), Ally\PetStore\Api\UserApi\loginUserRequest(), and Ally\PetStore\ApiException\setResponseObject().
Referenced by Ally\PetStore\Api\UserApi\loginUser().
     {
         $request = $this->loginUserRequest($username, $password);
         try {
             $options = $this->createHttpClientOption();
             try {
                 $response = $this->client->send($request, $options);
             } catch (RequestException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                     $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                 );
             } catch (ConnectException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     null,
                     null
                 );
             }
             $statusCode = $response->getStatusCode();
             if ($statusCode < 200 || $statusCode > 299) {
                 throw new ApiException(
                     sprintf(
                         '[%d] Error connecting to the API (%s)',
                         $statusCode,
                         (string) $request->getUri()
                     ),
                     $statusCode,
                     $response->getHeaders(),
                     (string) $response->getBody()
                 );
             }
             switch($statusCode) {
                 case 200:
                     if ('string' === '\SplFileObject') {
                         $content = $response->getBody(); //stream goes to serializer
                     } else {
                         $content = (string) $response->getBody();
                         if ('string' !== 'string') {
                             $content = json_decode($content);
                         }
                     }
                     return [
                         ObjectSerializer::deserialize($content, 'string', []),
                         $response->getStatusCode(),
                         $response->getHeaders()
                     ];
             }
             $returnType = 'string';
             if ($returnType === '\SplFileObject') {
                 $content = $response->getBody(); //stream goes to serializer
             } else {
                 $content = (string) $response->getBody();
                 if ($returnType !== 'string') {
                     $content = json_decode($content);
                 }
             }
             return [
                 ObjectSerializer::deserialize($content, $returnType, []),
                 $response->getStatusCode(),
                 $response->getHeaders()
             ];
         } catch (ApiException $e) {
             switch ($e->getCode()) {
                 case 200:
                     $data = ObjectSerializer::deserialize(
                         $e->getResponseBody(),
                         'string',
                         $e->getResponseHeaders()
                     );
                     $e->setResponseObject($data);
                     break;
             }
             throw $e;
         }
     }
logoutUser()
Ally\PetStore\Api\UserApi::logoutUser ()
Operation logoutUser.
Logs out current logged in user session
Exceptions
Definition at line 1644 of file UserApi.php.
References Ally\PetStore\Api\UserApi\logoutUserWithHttpInfo().
     {
         $this->logoutUserWithHttpInfo();
     }
logoutUserAsync()
Ally\PetStore\Api\UserApi::logoutUserAsync ()
Operation logoutUserAsync.
Logs out current logged in user session
Exceptions
Definition at line 1716 of file UserApi.php.
References Ally\PetStore\Api\UserApi\logoutUserAsyncWithHttpInfo().
     {
         return $this->logoutUserAsyncWithHttpInfo()
             ->then(
                 function ($response) {
                     return $response[0];
                 }
             );
     }
logoutUserAsyncWithHttpInfo()
Ally\PetStore\Api\UserApi::logoutUserAsyncWithHttpInfo ()
Operation logoutUserAsyncWithHttpInfo.
Logs out current logged in user session
Exceptions
Definition at line 1735 of file UserApi.php.
References Ally\PetStore\Api\UserApi\createHttpClientOption(), and Ally\PetStore\Api\UserApi\logoutUserRequest().
Referenced by Ally\PetStore\Api\UserApi\logoutUserAsync().
     {
         $returnType = '';
         $request = $this->logoutUserRequest();
         return $this->client
             ->sendAsync($request, $this->createHttpClientOption())
             ->then(
                 function ($response) use ($returnType) {
                     return [null, $response->getStatusCode(), $response->getHeaders()];
                 },
                 function ($exception) {
                     $response = $exception->getResponse();
                     $statusCode = $response->getStatusCode();
                     throw new ApiException(
                         sprintf(
                             '[%d] Error connecting to the API (%s)',
                             $statusCode,
                             $exception->getRequest()->getUri()
                         ),
                         $statusCode,
                         $response->getHeaders(),
                         (string) $response->getBody()
                     );
                 }
             );
     }
logoutUserRequest()
Ally\PetStore\Api\UserApi::logoutUserRequest ()
Create request for operation 'logoutUser'.
Exceptions
Definition at line 1770 of file UserApi.php.
References Ally\PetStore\ObjectSerializer\buildQuery().
Referenced by Ally\PetStore\Api\UserApi\logoutUserAsyncWithHttpInfo(), and Ally\PetStore\Api\UserApi\logoutUserWithHttpInfo().
     {
         $resourcePath = '/user/logout';
         $formParams = [];
         $queryParams = [];
         $headerParams = [];
         $httpBody = '';
         $multipart = false;
         if ($multipart) {
             $headers = $this->headerSelector->selectHeadersForMultipart(
                 []
             );
         } else {
             $headers = $this->headerSelector->selectHeaders(
                 [],
                 []
             );
         }
         // for model (json/xml)
         if (count($formParams) > 0) {
             if ($multipart) {
                 $multipartContents = [];
                 foreach ($formParams as $formParamName => $formParamValue) {
                     $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                     foreach ($formParamValueItems as $formParamValueItem) {
                         $multipartContents[] = [
                             'name' => $formParamName,
                             'contents' => $formParamValueItem
                         ];
                     }
                 }
                 // for HTTP post (form)
                 $httpBody = new MultipartStream($multipartContents);
             } elseif ($headers['Content-Type'] === 'application/json') {
                 $httpBody = \GuzzleHttp\json_encode($formParams);
             } else {
                 // for HTTP post (form)
                 $httpBody = ObjectSerializer::buildQuery($formParams);
             }
         }
         // this endpoint requires API key authentication
         $apiKey = $this->config->getApiKeyWithPrefix('api_key');
         if ($apiKey !== null) {
             $headers['api_key'] = $apiKey;
         }
         $defaultHeaders = [];
         if ($this->config->getUserAgent()) {
             $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
         }
         $headers = array_merge(
             $defaultHeaders,
             $headerParams,
             $headers
         );
         $operationHost = $this->config->getHost();
         $query = ObjectSerializer::buildQuery($queryParams);
         return new Request(
             'GET',
             $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
             $headers,
             $httpBody
         );
     }
logoutUserWithHttpInfo()
Ally\PetStore\Api\UserApi::logoutUserWithHttpInfo ()
Operation logoutUserWithHttpInfo.
Logs out current logged in user session
Exceptions
Definition at line 1659 of file UserApi.php.
References Ally\PetStore\Api\UserApi\createHttpClientOption(), and Ally\PetStore\Api\UserApi\logoutUserRequest().
Referenced by Ally\PetStore\Api\UserApi\logoutUser().
     {
         $request = $this->logoutUserRequest();
         try {
             $options = $this->createHttpClientOption();
             try {
                 $response = $this->client->send($request, $options);
             } catch (RequestException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                     $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                 );
             } catch (ConnectException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     null,
                     null
                 );
             }
             $statusCode = $response->getStatusCode();
             if ($statusCode < 200 || $statusCode > 299) {
                 throw new ApiException(
                     sprintf(
                         '[%d] Error connecting to the API (%s)',
                         $statusCode,
                         (string) $request->getUri()
                     ),
                     $statusCode,
                     $response->getHeaders(),
                     (string) $response->getBody()
                 );
             }
             return [null, $statusCode, $response->getHeaders()];
         } catch (ApiException $e) {
             switch ($e->getCode()) {
             }
             throw $e;
         }
     }
setHostIndex()
Ally\PetStore\Api\UserApi::setHostIndex ($hostIndex)
Set the host index.
Parameters
int $hostIndex Host index (required)
Definition at line 95 of file UserApi.php.
References Ally\PetStore\Api\UserApi\$hostIndex.
                                             : void
     {
         $this->hostIndex = $hostIndex;
     }
updateUser()
Ally\PetStore\Api\UserApi::updateUser ($username, $user)
Operation updateUser.
Updated user
Parameters
string $username name that need to be deleted (required)
\Ally\PetStore\Schema\User $user Updated user object (required)
Exceptions
Definition at line 1859 of file UserApi.php.
References Ally\PetStore\Api\UserApi\updateUserWithHttpInfo().
     {
         $this->updateUserWithHttpInfo($username, $user);
     }
updateUserAsync()
Ally\PetStore\Api\UserApi::updateUserAsync ($username, $user)
Operation updateUserAsync.
Updated user
Parameters
string $username name that need to be deleted (required)
\Ally\PetStore\Schema\User $user Updated user object (required)
Exceptions
Definition at line 1935 of file UserApi.php.
References Ally\PetStore\Api\UserApi\updateUserAsyncWithHttpInfo().
     {
         return $this->updateUserAsyncWithHttpInfo($username, $user)
             ->then(
                 function ($response) {
                     return $response[0];
                 }
             );
     }
updateUserAsyncWithHttpInfo()
Ally\PetStore\Api\UserApi::updateUserAsyncWithHttpInfo ($username, $user)
Operation updateUserAsyncWithHttpInfo.
Updated user
Parameters
string $username name that need to be deleted (required)
\Ally\PetStore\Schema\User $user Updated user object (required)
Exceptions
Definition at line 1956 of file UserApi.php.
References Ally\PetStore\Api\UserApi\createHttpClientOption(), and Ally\PetStore\Api\UserApi\updateUserRequest().
Referenced by Ally\PetStore\Api\UserApi\updateUserAsync().
     {
         $returnType = '';
         $request = $this->updateUserRequest($username, $user);
         return $this->client
             ->sendAsync($request, $this->createHttpClientOption())
             ->then(
                 function ($response) use ($returnType) {
                     return [null, $response->getStatusCode(), $response->getHeaders()];
                 },
                 function ($exception) {
                     $response = $exception->getResponse();
                     $statusCode = $response->getStatusCode();
                     throw new ApiException(
                         sprintf(
                             '[%d] Error connecting to the API (%s)',
                             $statusCode,
                             $exception->getRequest()->getUri()
                         ),
                         $statusCode,
                         $response->getHeaders(),
                         (string) $response->getBody()
                     );
                 }
             );
     }
updateUserRequest()
Ally\PetStore\Api\UserApi::updateUserRequest ($username, $user)
Create request for operation 'updateUser'.
Parameters
string $username name that need to be deleted (required)
\Ally\PetStore\Schema\User $user Updated user object (required)
Exceptions
Definition at line 1993 of file UserApi.php.
References Ally\PetStore\ObjectSerializer\buildQuery(), Ally\PetStore\ObjectSerializer\sanitizeForSerialization(), and Ally\PetStore\ObjectSerializer\toPathValue().
Referenced by Ally\PetStore\Api\UserApi\updateUserAsyncWithHttpInfo(), and Ally\PetStore\Api\UserApi\updateUserWithHttpInfo().
     {
         // verify the required parameter 'username' is set
         if ($username === null || (is_array($username) && count($username) === 0)) {
             throw new \InvalidArgumentException(
                 'Missing the required parameter $username when calling updateUser'
             );
         }
         // verify the required parameter 'user' is set
         if ($user === null || (is_array($user) && count($user) === 0)) {
             throw new \InvalidArgumentException(
                 'Missing the required parameter $user when calling updateUser'
             );
         }
         $resourcePath = '/user/{username}';
         $formParams = [];
         $queryParams = [];
         $headerParams = [];
         $httpBody = '';
         $multipart = false;
         // path params
         if ($username !== null) {
             $resourcePath = str_replace(
                 '{' . 'username' . '}',
                 ObjectSerializer::toPathValue($username),
                 $resourcePath
             );
         }
         if ($multipart) {
             $headers = $this->headerSelector->selectHeadersForMultipart(
                 []
             );
         } else {
             $headers = $this->headerSelector->selectHeaders(
                 [],
                 ['application/json']
             );
         }
         // for model (json/xml)
         if (isset($user)) {
             if ($headers['Content-Type'] === 'application/json') {
                 $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($user));
             } else {
                 $httpBody = $user;
             }
         } elseif (count($formParams) > 0) {
             if ($multipart) {
                 $multipartContents = [];
                 foreach ($formParams as $formParamName => $formParamValue) {
                     $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                     foreach ($formParamValueItems as $formParamValueItem) {
                         $multipartContents[] = [
                             'name' => $formParamName,
                             'contents' => $formParamValueItem
                         ];
                     }
                 }
                 // for HTTP post (form)
                 $httpBody = new MultipartStream($multipartContents);
             } elseif ($headers['Content-Type'] === 'application/json') {
                 $httpBody = \GuzzleHttp\json_encode($formParams);
             } else {
                 // for HTTP post (form)
                 $httpBody = ObjectSerializer::buildQuery($formParams);
             }
         }
         // this endpoint requires API key authentication
         $apiKey = $this->config->getApiKeyWithPrefix('api_key');
         if ($apiKey !== null) {
             $headers['api_key'] = $apiKey;
         }
         $defaultHeaders = [];
         if ($this->config->getUserAgent()) {
             $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
         }
         $headers = array_merge(
             $defaultHeaders,
             $headerParams,
             $headers
         );
         $operationHost = $this->config->getHost();
         $query = ObjectSerializer::buildQuery($queryParams);
         return new Request(
             'PUT',
             $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
             $headers,
             $httpBody
         );
     }
updateUserWithHttpInfo()
Ally\PetStore\Api\UserApi::updateUserWithHttpInfo ($username, $user)
Operation updateUserWithHttpInfo.
Updated user
Parameters
string $username name that need to be deleted (required)
\Ally\PetStore\Schema\User $user Updated user object (required)
Exceptions
Definition at line 1876 of file UserApi.php.
References Ally\PetStore\Api\UserApi\createHttpClientOption(), and Ally\PetStore\Api\UserApi\updateUserRequest().
Referenced by Ally\PetStore\Api\UserApi\updateUser().
     {
         $request = $this->updateUserRequest($username, $user);
         try {
             $options = $this->createHttpClientOption();
             try {
                 $response = $this->client->send($request, $options);
             } catch (RequestException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                     $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                 );
             } catch (ConnectException $e) {
                 throw new ApiException(
                     "[{$e->getCode()}] {$e->getMessage()}",
                     (int) $e->getCode(),
                     null,
                     null
                 );
             }
             $statusCode = $response->getStatusCode();
             if ($statusCode < 200 || $statusCode > 299) {
                 throw new ApiException(
                     sprintf(
                         '[%d] Error connecting to the API (%s)',
                         $statusCode,
                         (string) $request->getUri()
                     ),
                     $statusCode,
                     $response->getHeaders(),
                     (string) $response->getBody()
                 );
             }
             return [null, $statusCode, $response->getHeaders()];
         } catch (ApiException $e) {
             switch ($e->getCode()) {
             }
             throw $e;
         }
     }
Member Data Documentation
$client
Ally\PetStore\Api\UserApi::$client protected
Definition at line 55 of file UserApi.php.
Referenced by Ally\PetStore\Api\UserApi\__construct().
$config
Ally\PetStore\Api\UserApi::$config protected
Definition at line 60 of file UserApi.php.
Referenced by Ally\PetStore\Api\UserApi\__construct(), and Ally\PetStore\Api\UserApi\getConfig().
$headerSelector
Ally\PetStore\Api\UserApi::$headerSelector protected
Definition at line 65 of file UserApi.php.
$hostIndex
Ally\PetStore\Api\UserApi::$hostIndex protected
Definition at line 70 of file UserApi.php.
Referenced by Ally\PetStore\Api\UserApi\__construct(), Ally\PetStore\Api\UserApi\getHostIndex(), and Ally\PetStore\Api\UserApi\setHostIndex().
The documentation for this class was generated from the following file:
src/Api/UserApi.php