Ally'sPetStoreAPI: Ally\PetStore\ApiException Class Reference
Ally\PetStore\ApiException Class Reference
Public Member Functions
__construct ($message="", $code=0, $responseHeaders=[], $responseBody=null)
Constructor.
getResponseHeaders ()
Gets the HTTP response header.
getResponseBody ()
Gets the HTTP body of the server response either as Json or string.
setResponseObject ($obj)
Sets the deserialized response object (during deserialization)
getResponseObject ()
Gets the deserialized response object (during deserialization)
Protected Attributes
$responseBody
$responseHeaders
$responseObject
Detailed Description
Definition at line 40 of file ApiException.php.
Constructor & Destructor Documentation
__construct()
Ally\PetStore\ApiException::__construct ($message = "", $code = 0, $responseHeaders = [], $responseBody = null)
Constructor.
Parameters
string $message Error message
int $code HTTP status code
string[]|null $responseHeaders HTTP response header
\stdClass | string | null $responseBody HTTP decoded body of the server response either as or string
Definition at line 71 of file ApiException.php.
References Ally\PetStore\ApiException\$responseBody, and Ally\PetStore\ApiException\$responseHeaders.
     {
         parent::__construct($message, $code);
         $this->responseHeaders = $responseHeaders;
         $this->responseBody = $responseBody;
     }
Member Function Documentation
getResponseBody()
Ally\PetStore\ApiException::getResponseBody ()
Gets the HTTP body of the server response either as Json or string.
Returns
|string|null HTTP body of the server response either as or string
Definition at line 93 of file ApiException.php.
References Ally\PetStore\ApiException\$responseBody.
Referenced by Ally\PetStore\Api\PetApi\addPetWithHttpInfo(), Ally\PetStore\Api\PetApi\findPetsByStatusWithHttpInfo(), Ally\PetStore\Api\PetApi\findPetsByTagsWithHttpInfo(), Ally\PetStore\Api\StoreApi\getInventoryWithHttpInfo(), Ally\PetStore\Api\StoreApi\getOrderByIdWithHttpInfo(), Ally\PetStore\Api\PetApi\getPetByIdWithHttpInfo(), Ally\PetStore\Api\UserApi\getUserByNameWithHttpInfo(), Ally\PetStore\Api\UserApi\loginUserWithHttpInfo(), Ally\PetStore\Api\StoreApi\placeOrderWithHttpInfo(), Ally\PetStore\Api\PetApi\updatePetWithHttpInfo(), and Ally\PetStore\Api\PetApi\uploadFileWithHttpInfo().
     {
         return $this->responseBody;
     }
getResponseHeaders()
Ally\PetStore\ApiException::getResponseHeaders ()
Gets the HTTP response header.
Returns
string[]|null HTTP response header
Definition at line 83 of file ApiException.php.
References Ally\PetStore\ApiException\$responseHeaders.
Referenced by Ally\PetStore\Api\PetApi\addPetWithHttpInfo(), Ally\PetStore\Api\PetApi\findPetsByStatusWithHttpInfo(), Ally\PetStore\Api\PetApi\findPetsByTagsWithHttpInfo(), Ally\PetStore\Api\StoreApi\getInventoryWithHttpInfo(), Ally\PetStore\Api\StoreApi\getOrderByIdWithHttpInfo(), Ally\PetStore\Api\PetApi\getPetByIdWithHttpInfo(), Ally\PetStore\Api\UserApi\getUserByNameWithHttpInfo(), Ally\PetStore\Api\UserApi\loginUserWithHttpInfo(), Ally\PetStore\Api\StoreApi\placeOrderWithHttpInfo(), Ally\PetStore\Api\PetApi\updatePetWithHttpInfo(), and Ally\PetStore\Api\PetApi\uploadFileWithHttpInfo().
     {
         return $this->responseHeaders;
     }
getResponseObject()
Ally\PetStore\ApiException::getResponseObject ()
Gets the deserialized response object (during deserialization)
Returns
mixed the deserialized response object
Definition at line 115 of file ApiException.php.
References Ally\PetStore\ApiException\$responseObject.
     {
         return $this->responseObject;
     }
setResponseObject()
Ally\PetStore\ApiException::setResponseObject ($obj)
Sets the deserialized response object (during deserialization)
Parameters
mixed $obj Deserialized response object
Returns
void
Definition at line 105 of file ApiException.php.
Referenced by Ally\PetStore\Api\PetApi\addPetWithHttpInfo(), Ally\PetStore\Api\PetApi\findPetsByStatusWithHttpInfo(), Ally\PetStore\Api\PetApi\findPetsByTagsWithHttpInfo(), Ally\PetStore\Api\StoreApi\getInventoryWithHttpInfo(), Ally\PetStore\Api\StoreApi\getOrderByIdWithHttpInfo(), Ally\PetStore\Api\PetApi\getPetByIdWithHttpInfo(), Ally\PetStore\Api\UserApi\getUserByNameWithHttpInfo(), Ally\PetStore\Api\UserApi\loginUserWithHttpInfo(), Ally\PetStore\Api\StoreApi\placeOrderWithHttpInfo(), Ally\PetStore\Api\PetApi\updatePetWithHttpInfo(), and Ally\PetStore\Api\PetApi\uploadFileWithHttpInfo().
     {
         $this->responseObject = $obj;
     }
Member Data Documentation
$responseBody
Ally\PetStore\ApiException::$responseBody protected
Definition at line 47 of file ApiException.php.
Referenced by Ally\PetStore\ApiException\__construct(), and Ally\PetStore\ApiException\getResponseBody().
$responseHeaders
Ally\PetStore\ApiException::$responseHeaders protected
Definition at line 54 of file ApiException.php.
Referenced by Ally\PetStore\ApiException\__construct(), and Ally\PetStore\ApiException\getResponseHeaders().
$responseObject
Ally\PetStore\ApiException::$responseObject protected
Definition at line 61 of file ApiException.php.
Referenced by Ally\PetStore\ApiException\getResponseObject().
The documentation for this class was generated from the following file:
src/ApiException.php