Ally'sPetStoreAPI: Ally\PetStore\Schema\Pet Class Reference
Ally\PetStore\Schema\Pet Class Reference
Public Member Functions
isNullableSetToNull (string $property)
Checks if a nullable property is set to null.
getModelName ()
The original name of the model.
getStatusAllowableValues ()
Gets allowable values of the enum.
__construct (array $data=null)
Constructor.
listInvalidProperties ()
Show all the invalid properties with reasons.
valid ()
Validate all the properties in the model return true if all passed.
getId ()
Gets id.
setId ($id)
Sets id.
getCategory ()
Gets category.
setCategory ($category)
Sets category.
getName ()
Gets name.
setName ($name)
Sets name.
getPhotoUrls ()
Gets photo_urls.
setPhotoUrls ($photo_urls)
Sets photo_urls.
getTags ()
Gets tags.
setTags ($tags)
Sets tags.
getStatus ()
Gets status.
setStatus ($status)
Sets status.
offsetExists ($offset)
Returns true if offset exists.
offsetGet ($offset)
Gets offset.
offsetSet ($offset, $value)
Sets value based on offset.
offsetUnset ($offset)
Unsets offset.
jsonSerialize ()
Serializes the object to a value that can be serialized natively by json_encode().
__toString ()
Gets the string presentation of the object.
toHeaderValue ()
Gets a header-safe presentation of the object.
Static Public Member Functions
static openAPITypes ()
Array of property to type mappings.
static openAPIFormats ()
Array of property to format mappings.
static isNullable (string $property)
Checks if a property is nullable.
static static attributeMap ()
Array of attributes where the key is the local name, and the value is the original name.
static setters ()
Array of attributes to setter functions (for deserialization of responses)
static getters ()
Array of attributes to getter functions (for serialization of requests)
Public Attributes
const DISCRIMINATOR = null
const STATUS_AVAILABLE = 'available'
const STATUS_PENDING = 'pending'
const STATUS_SOLD = 'sold'
Static Protected Member Functions
static openAPINullables ()
Array of nullable properties.
Protected Attributes
array $openAPINullablesSetToNull = []
$container = []
Static Protected Attributes
static $openAPIModelName = 'Pet'
static $openAPITypes
static $openAPIFormats
static array $openAPINullables
static $attributeMap
static $setters
static $getters
Private Member Functions
getOpenAPINullablesSetToNull ()
Array of nullable field names deliberately set to null.
setIfExists (string $variableName, array $fields, $defaultValue)
Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the $this->openAPINullablesSetToNull array.
Detailed Description
Definition at line 44 of file Pet.php.
Constructor & Destructor Documentation
__construct()
Ally\PetStore\Schema\Pet::__construct (array $data = null)
Constructor.
Parameters
mixed[] $data Associated array of property values initializing the model
Definition at line 283 of file Pet.php.
References Ally\PetStore\Schema\Pet\setIfExists().
     {
         $this->setIfExists('id', $data ?? [], null);
         $this->setIfExists('category', $data ?? [], null);
         $this->setIfExists('name', $data ?? [], null);
         $this->setIfExists('photo_urls', $data ?? [], null);
         $this->setIfExists('tags', $data ?? [], null);
         $this->setIfExists('status', $data ?? [], null);
     }
Member Function Documentation
__toString()
Ally\PetStore\Schema\Pet::__toString ()
Gets the string presentation of the object.
Returns
string
Definition at line 607 of file Pet.php.
References Ally\PetStore\ObjectSerializer\sanitizeForSerialization().
     {
         return json_encode(
             ObjectSerializer::sanitizeForSerialization($this),
             JSON_PRETTY_PRINT
         );
     }
attributeMap()
static static Ally\PetStore\Schema\Pet::attributeMap () static
Array of attributes where the key is the local name, and the value is the original name.
Returns
array
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 217 of file Pet.php.
     {
         return self::$attributeMap;
     }
getCategory()
Ally\PetStore\Schema\Pet::getCategory ()
Gets category.
Returns
|null
Definition at line 384 of file Pet.php.
     {
         return $this->container['category'];
     }
getId()
Ally\PetStore\Schema\Pet::getId ()
Gets id.
Returns
int|null
Definition at line 355 of file Pet.php.
     {
         return $this->container['id'];
     }
getModelName()
Ally\PetStore\Schema\Pet::getModelName ()
The original name of the model.
Returns
string
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 247 of file Pet.php.
     {
         return self::$openAPIModelName;
     }
getName()
Ally\PetStore\Schema\Pet::getName ()
Gets name.
Returns
string
Definition at line 413 of file Pet.php.
     {
         return $this->container['name'];
     }
getOpenAPINullablesSetToNull()
Ally\PetStore\Schema\Pet::getOpenAPINullablesSetToNull () private
Array of nullable field names deliberately set to null.
Returns
boolean[]
Definition at line 141 of file Pet.php.
References Ally\PetStore\Schema\Pet\$openAPINullablesSetToNull.
Referenced by Ally\PetStore\Schema\Pet\isNullableSetToNull().
                                                    : array
     {
         return $this->openAPINullablesSetToNull;
     }
getPhotoUrls()
Ally\PetStore\Schema\Pet::getPhotoUrls ()
Gets photo_urls.
Returns
string[]
Definition at line 442 of file Pet.php.
     {
         return $this->container['photo_urls'];
     }
getStatus()
Ally\PetStore\Schema\Pet::getStatus ()
Gets status.
Returns
string|null
Deprecated:
Definition at line 501 of file Pet.php.
     {
         return $this->container['status'];
     }
getStatusAllowableValues()
Ally\PetStore\Schema\Pet::getStatusAllowableValues ()
Gets allowable values of the enum.
Returns
string[]
Definition at line 261 of file Pet.php.
Referenced by Ally\PetStore\Schema\Pet\listInvalidProperties(), and Ally\PetStore\Schema\Pet\setStatus().
     {
         return [
             self::STATUS_AVAILABLE,
             self::STATUS_PENDING,
             self::STATUS_SOLD,
         ];
     }
getTags()
Ally\PetStore\Schema\Pet::getTags ()
Gets tags.
Returns
[]|null
Definition at line 471 of file Pet.php.
     {
         return $this->container['tags'];
     }
getters()
static Ally\PetStore\Schema\Pet::getters () static
Array of attributes to getter functions (for serialization of requests)
Returns
array
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 237 of file Pet.php.
     {
         return self::$getters;
     }
isNullable()
static Ally\PetStore\Schema\Pet::isNullable (string $property) static
Checks if a property is nullable.
Parameters
string $property
Returns
bool
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 152 of file Pet.php.
                                                        : bool
     {
         return self::openAPINullables()[$property] ?? false;
     }
isNullableSetToNull()
Ally\PetStore\Schema\Pet::isNullableSetToNull (string $property)
Checks if a nullable property is set to null.
Parameters
string $property
Returns
bool
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 163 of file Pet.php.
References Ally\PetStore\Schema\Pet\getOpenAPINullablesSetToNull().
                                                          : bool
     {
         return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
     }
jsonSerialize()
Ally\PetStore\Schema\Pet::jsonSerialize ()
Serializes the object to a value that can be serialized natively by json_encode().
mixed Returns data which can be serialized by json_encode(), which is a value of any type other than a resource.
Definition at line 597 of file Pet.php.
References Ally\PetStore\ObjectSerializer\sanitizeForSerialization().
     {
        return ObjectSerializer::sanitizeForSerialization($this);
     }
listInvalidProperties()
Ally\PetStore\Schema\Pet::listInvalidProperties ()
Show all the invalid properties with reasons.
Returns
array invalid properties with reasons
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 316 of file Pet.php.
References Ally\PetStore\Schema\Pet\getStatusAllowableValues().
Referenced by Ally\PetStore\Schema\Pet\valid().
     {
         $invalidProperties = [];
         if ($this->container['name'] === null) {
             $invalidProperties[] = "'name' can't be null";
         }
         if ($this->container['photo_urls'] === null) {
             $invalidProperties[] = "'photo_urls' can't be null";
         }
         $allowedValues = $this->getStatusAllowableValues();
         if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
             $invalidProperties[] = sprintf(
                 "invalid value '%s' for 'status', must be one of '%s'",
                 $this->container['status'],
                 implode("', '", $allowedValues)
             );
         }
         return $invalidProperties;
     }
offsetExists()
Ally\PetStore\Schema\Pet::offsetExists ($offset)
Returns true if offset exists.
False otherwise.
Parameters
integer $offset Offset
Returns
boolean
Definition at line 542 of file Pet.php.
                                          : bool
     {
         return isset($this->container[$offset]);
     }
offsetGet()
Ally\PetStore\Schema\Pet::offsetGet ($offset)
Gets offset.
Parameters
integer $offset Offset
Returns
mixed|null
Definition at line 555 of file Pet.php.
     {
         return $this->container[$offset] ?? null;
     }
offsetSet()
Ally\PetStore\Schema\Pet::offsetSet ($offset, $value)
Sets value based on offset.
Parameters
int | null $offset Offset
mixed $value Value to be set
Returns
void
Definition at line 568 of file Pet.php.
                                               : void
     {
         if (is_null($offset)) {
             $this->container[] = $value;
         } else {
             $this->container[$offset] = $value;
         }
     }
offsetUnset()
Ally\PetStore\Schema\Pet::offsetUnset ($offset)
Unsets offset.
Parameters
integer $offset Offset
Returns
void
Definition at line 584 of file Pet.php.
                                         : void
     {
         unset($this->container[$offset]);
     }
openAPIFormats()
static Ally\PetStore\Schema\Pet::openAPIFormats () static
Array of property to format mappings.
Used for (de)serialization
Returns
array
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 121 of file Pet.php.
     {
         return self::$openAPIFormats;
     }
openAPINullables()
static Ally\PetStore\Schema\Pet::openAPINullables () static protected
Array of nullable properties.
Returns
array
Definition at line 131 of file Pet.php.
                                                 : array
     {
         return self::$openAPINullables;
     }
openAPITypes()
static Ally\PetStore\Schema\Pet::openAPITypes () static
Array of property to type mappings.
Used for (de)serialization
Returns
array
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 111 of file Pet.php.
     {
         return self::$openAPITypes;
     }
setCategory()
Ally\PetStore\Schema\Pet::setCategory ($category)
Sets category.
Parameters
\Ally\PetStore\Schema\Category | null $category category
Returns
self
Definition at line 396 of file Pet.php.
     {
         if (is_null($category)) {
             throw new \InvalidArgumentException('non-nullable category cannot be null');
         }
         $this->container['category'] = $category;
         return $this;
     }
setId()
Ally\PetStore\Schema\Pet::setId ($id)
Sets id.
Parameters
int | null $id id
Returns
self
Definition at line 367 of file Pet.php.
     {
         if (is_null($id)) {
             throw new \InvalidArgumentException('non-nullable id cannot be null');
         }
         $this->container['id'] = $id;
         return $this;
     }
setIfExists()
Ally\PetStore\Schema\Pet::setIfExists (string $variableName, array $fields, $defaultValue) private
Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the $this->openAPINullablesSetToNull array.
Parameters
string $variableName
array $fields
mixed $defaultValue
Definition at line 302 of file Pet.php.
Referenced by Ally\PetStore\Schema\Pet\__construct().
                                                                                     : void
     {
         if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
             $this->openAPINullablesSetToNull[] = $variableName;
         }
         $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
     }
setName()
Ally\PetStore\Schema\Pet::setName ($name)
Sets name.
Parameters
string $name name
Returns
self
Definition at line 425 of file Pet.php.
     {
         if (is_null($name)) {
             throw new \InvalidArgumentException('non-nullable name cannot be null');
         }
         $this->container['name'] = $name;
         return $this;
     }
setPhotoUrls()
Ally\PetStore\Schema\Pet::setPhotoUrls ($photo_urls)
Sets photo_urls.
Parameters
string[] $photo_urls photo_urls
Returns
self
Definition at line 454 of file Pet.php.
     {
         if (is_null($photo_urls)) {
             throw new \InvalidArgumentException('non-nullable photo_urls cannot be null');
         }
         $this->container['photo_urls'] = $photo_urls;
         return $this;
     }
setStatus()
Ally\PetStore\Schema\Pet::setStatus ($status)
Sets status.
Parameters
string | null $status pet status in the store
Returns
self
Deprecated:
Definition at line 514 of file Pet.php.
References Ally\PetStore\Schema\Pet\getStatusAllowableValues().
     {
         $allowedValues = $this->getStatusAllowableValues();
         if (!is_null($status) && !in_array($status, $allowedValues, true)) {
             throw new \InvalidArgumentException(
                 sprintf(
                     "Invalid value '%s' for 'status', must be one of '%s'",
                     $status,
                     implode("', '", $allowedValues)
                 )
             );
         }
         if (is_null($status)) {
             throw new \InvalidArgumentException('non-nullable status cannot be null');
         }
         $this->container['status'] = $status;
         return $this;
     }
setTags()
Ally\PetStore\Schema\Pet::setTags ($tags)
Sets tags.
Parameters
Definition at line 483 of file Pet.php.
     {
         if (is_null($tags)) {
             throw new \InvalidArgumentException('non-nullable tags cannot be null');
         }
         $this->container['tags'] = $tags;
         return $this;
     }
setters()
static Ally\PetStore\Schema\Pet::setters () static
Array of attributes to setter functions (for deserialization of responses)
Returns
array
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 227 of file Pet.php.
     {
         return self::$setters;
     }
toHeaderValue()
Ally\PetStore\Schema\Pet::toHeaderValue ()
Gets a header-safe presentation of the object.
Returns
string
Definition at line 620 of file Pet.php.
References Ally\PetStore\ObjectSerializer\sanitizeForSerialization().
     {
         return json_encode(ObjectSerializer::sanitizeForSerialization($this));
     }
valid()
Ally\PetStore\Schema\Pet::valid ()
Validate all the properties in the model return true if all passed.
Returns
bool True if all properties are valid
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 344 of file Pet.php.
References Ally\PetStore\Schema\Pet\listInvalidProperties().
     {
         return count($this->listInvalidProperties()) === 0;
     }
Member Data Documentation
$attributeMap
Ally\PetStore\Schema\Pet::$attributeMap static protected
Initial value:
= [
        'id' => 'id'
Definition at line 174 of file Pet.php.
$container
Ally\PetStore\Schema\Pet::$container = [] protected
Definition at line 275 of file Pet.php.
$getters
Ally\PetStore\Schema\Pet::$getters static protected
Initial value:
= [
        'id' => 'getId'
Definition at line 202 of file Pet.php.
$openAPIFormats
Ally\PetStore\Schema\Pet::$openAPIFormats static protected
Initial value:
= [
        'id' => 'int64'
Definition at line 76 of file Pet.php.
$openAPIModelName
Ally\PetStore\Schema\Pet::$openAPIModelName = 'Pet' static protected
Definition at line 53 of file Pet.php.
$openAPINullables
array Ally\PetStore\Schema\Pet::$openAPINullables static protected
Initial value:
= [
        'id' => false
Definition at line 90 of file Pet.php.
$openAPINullablesSetToNull
array Ally\PetStore\Schema\Pet::$openAPINullablesSetToNull = [] protected
Definition at line 104 of file Pet.php.
Referenced by Ally\PetStore\Schema\Pet\getOpenAPINullablesSetToNull().
$openAPITypes
Ally\PetStore\Schema\Pet::$openAPITypes static protected
Initial value:
= [
        'id' => 'int'
Definition at line 60 of file Pet.php.
$setters
Ally\PetStore\Schema\Pet::$setters static protected
Initial value:
= [
        'id' => 'setId'
Definition at line 188 of file Pet.php.
DISCRIMINATOR
const Ally\PetStore\Schema\Pet::DISCRIMINATOR = null
Definition at line 46 of file Pet.php.
STATUS_AVAILABLE
const Ally\PetStore\Schema\Pet::STATUS_AVAILABLE = 'available'
Definition at line 252 of file Pet.php.
STATUS_PENDING
const Ally\PetStore\Schema\Pet::STATUS_PENDING = 'pending'
Definition at line 253 of file Pet.php.
STATUS_SOLD
const Ally\PetStore\Schema\Pet::STATUS_SOLD = 'sold'
Definition at line 254 of file Pet.php.
The documentation for this class was generated from the following file:
src/Schema/Pet.php