Ally'sPetStoreAPI: Ally\PetStore\HeaderSelector Class Reference
Ally\PetStore\HeaderSelector Class Reference
Public Member Functions
selectHeaders ($accept, $contentTypes)
selectHeadersForMultipart ($accept)
Private Member Functions
selectAcceptHeader ($accept)
Return the header 'Accept' based on an array of Accept provided.
selectContentTypeHeader ($contentType)
Return the content type based on an array of content-type provided.
Detailed Description
Definition at line 40 of file HeaderSelector.php.
Member Function Documentation
selectAcceptHeader()
Ally\PetStore\HeaderSelector::selectAcceptHeader ($accept) private
Return the header 'Accept' based on an array of Accept provided.
Parameters
string[] $accept Array of header
Returns
null|string Accept (e.g. application/json)
Definition at line 79 of file HeaderSelector.php.
Referenced by Ally\PetStore\HeaderSelector\selectHeaders().
     {
         if (count($accept) === 0 || (count($accept) === 1 && $accept[0] === '')) {
             return null;
         } elseif ($jsonAccept = preg_grep('~(?i)^(application/json|[^;/ \t]+/[^;/ \t]+[+]json)[ \t]*(;.*)?$~', $accept)) {
             return implode(',', $jsonAccept);
         } else {
             return implode(',', $accept);
         }
     }
selectContentTypeHeader()
Ally\PetStore\HeaderSelector::selectContentTypeHeader ($contentType) private
Return the content type based on an array of content-type provided.
Parameters
string[] $contentType Array fo content-type
Returns
string Content-Type (e.g. application/json)
Definition at line 97 of file HeaderSelector.php.
Referenced by Ally\PetStore\HeaderSelector\selectHeaders().
     {
         if (count($contentType) === 0 || (count($contentType) === 1 && $contentType[0] === '')) {
             return 'application/json';
         } elseif (preg_grep("/application\/json/i", $contentType)) {
             return 'application/json';
         } else {
             return implode(',', $contentType);
         }
     }
selectHeaders()
Ally\PetStore\HeaderSelector::selectHeaders ($accept, $contentTypes)
Parameters
string[] $accept
string[] $contentTypes
Returns
array
Definition at line 47 of file HeaderSelector.php.
References Ally\PetStore\HeaderSelector\selectAcceptHeader(), and Ally\PetStore\HeaderSelector\selectContentTypeHeader().
Referenced by Ally\PetStore\HeaderSelector\selectHeadersForMultipart().
     {
         $headers = [];
         $accept = $this->selectAcceptHeader($accept);
         if ($accept !== null) {
             $headers['Accept'] = $accept;
         }
         $headers['Content-Type'] = $this->selectContentTypeHeader($contentTypes);
         return $headers;
     }
selectHeadersForMultipart()
Ally\PetStore\HeaderSelector::selectHeadersForMultipart ($accept)
Parameters
string[] $accept
Returns
array
Definition at line 64 of file HeaderSelector.php.
References Ally\PetStore\HeaderSelector\selectHeaders().
     {
         $headers = $this->selectHeaders($accept, []);
         unset($headers['Content-Type']);
         return $headers;
     }
The documentation for this class was generated from the following file:
src/HeaderSelector.php