Ally'sPetStoreAPI: Ally\PetStore\Schema\ApiResponse Class Reference
Ally\PetStore\Schema\ApiResponse Class Reference
Public Member Functions
isNullableSetToNull (string $property)
Checks if a nullable property is set to null.
getModelName ()
The original name of the model.
__construct (array $data=null)
Constructor.
listInvalidProperties ()
Show all the invalid properties with reasons.
valid ()
Validate all the properties in the model return true if all passed.
getCode ()
Gets code.
setCode ($code)
Sets code.
getType ()
Gets type.
setType ($type)
Sets type.
getMessage ()
Gets message.
setMessage ($message)
Sets message.
offsetExists ($offset)
Returns true if offset exists.
offsetGet ($offset)
Gets offset.
offsetSet ($offset, $value)
Sets value based on offset.
offsetUnset ($offset)
Unsets offset.
jsonSerialize ()
Serializes the object to a value that can be serialized natively by json_encode().
__toString ()
Gets the string presentation of the object.
toHeaderValue ()
Gets a header-safe presentation of the object.
Static Public Member Functions
static openAPITypes ()
Array of property to type mappings.
static openAPIFormats ()
Array of property to format mappings.
static isNullable (string $property)
Checks if a property is nullable.
static static attributeMap ()
Array of attributes where the key is the local name, and the value is the original name.
static setters ()
Array of attributes to setter functions (for deserialization of responses)
static getters ()
Array of attributes to getter functions (for serialization of requests)
Public Attributes
const DISCRIMINATOR = null
Static Protected Member Functions
static openAPINullables ()
Array of nullable properties.
Protected Attributes
array $openAPINullablesSetToNull = []
$container = []
Static Protected Attributes
static $openAPIModelName = 'ApiResponse'
static $openAPITypes
static $openAPIFormats
static array $openAPINullables
static $attributeMap
static $setters
static $getters
Private Member Functions
getOpenAPINullablesSetToNull ()
Array of nullable field names deliberately set to null.
setIfExists (string $variableName, array $fields, $defaultValue)
Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the $this->openAPINullablesSetToNull array.
Detailed Description
Definition at line 44 of file ApiResponse.php.
Constructor & Destructor Documentation
__construct()
Ally\PetStore\Schema\ApiResponse::__construct (array $data = null)
Constructor.
Parameters
mixed[] $data Associated array of property values initializing the model
Definition at line 248 of file ApiResponse.php.
References Ally\PetStore\Schema\ApiResponse\setIfExists().
     {
         $this->setIfExists('code', $data ?? [], null);
         $this->setIfExists('type', $data ?? [], null);
         $this->setIfExists('message', $data ?? [], null);
     }
Member Function Documentation
__toString()
Ally\PetStore\Schema\ApiResponse::__toString ()
Gets the string presentation of the object.
Returns
string
Definition at line 455 of file ApiResponse.php.
References Ally\PetStore\ObjectSerializer\sanitizeForSerialization().
     {
         return json_encode(
             ObjectSerializer::sanitizeForSerialization($this),
             JSON_PRETTY_PRINT
         );
     }
attributeMap()
static static Ally\PetStore\Schema\ApiResponse::attributeMap () static
Array of attributes where the key is the local name, and the value is the original name.
Returns
array
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 199 of file ApiResponse.php.
     {
         return self::$attributeMap;
     }
getCode()
Ally\PetStore\Schema\ApiResponse::getCode ()
Gets code.
Returns
int|null
Definition at line 302 of file ApiResponse.php.
     {
         return $this->container['code'];
     }
getMessage()
Ally\PetStore\Schema\ApiResponse::getMessage ()
Gets message.
Returns
string|null
Definition at line 360 of file ApiResponse.php.
     {
         return $this->container['message'];
     }
getModelName()
Ally\PetStore\Schema\ApiResponse::getModelName ()
The original name of the model.
Returns
string
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 229 of file ApiResponse.php.
     {
         return self::$openAPIModelName;
     }
getOpenAPINullablesSetToNull()
Ally\PetStore\Schema\ApiResponse::getOpenAPINullablesSetToNull () private
Array of nullable field names deliberately set to null.
Returns
boolean[]
Definition at line 132 of file ApiResponse.php.
References Ally\PetStore\Schema\ApiResponse\$openAPINullablesSetToNull.
Referenced by Ally\PetStore\Schema\ApiResponse\isNullableSetToNull().
                                                    : array
     {
         return $this->openAPINullablesSetToNull;
     }
getters()
static Ally\PetStore\Schema\ApiResponse::getters () static
Array of attributes to getter functions (for serialization of requests)
Returns
array
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 219 of file ApiResponse.php.
     {
         return self::$getters;
     }
getType()
Ally\PetStore\Schema\ApiResponse::getType ()
Gets type.
Returns
string|null
Definition at line 331 of file ApiResponse.php.
     {
         return $this->container['type'];
     }
isNullable()
static Ally\PetStore\Schema\ApiResponse::isNullable (string $property) static
Checks if a property is nullable.
Parameters
string $property
Returns
bool
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 143 of file ApiResponse.php.
                                                        : bool
     {
         return self::openAPINullables()[$property] ?? false;
     }
isNullableSetToNull()
Ally\PetStore\Schema\ApiResponse::isNullableSetToNull (string $property)
Checks if a nullable property is set to null.
Parameters
string $property
Returns
bool
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 154 of file ApiResponse.php.
References Ally\PetStore\Schema\ApiResponse\getOpenAPINullablesSetToNull().
                                                          : bool
     {
         return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
     }
jsonSerialize()
Ally\PetStore\Schema\ApiResponse::jsonSerialize ()
Serializes the object to a value that can be serialized natively by json_encode().
mixed Returns data which can be serialized by json_encode(), which is a value of any type other than a resource.
Definition at line 445 of file ApiResponse.php.
References Ally\PetStore\ObjectSerializer\sanitizeForSerialization().
     {
        return ObjectSerializer::sanitizeForSerialization($this);
     }
listInvalidProperties()
Ally\PetStore\Schema\ApiResponse::listInvalidProperties ()
Show all the invalid properties with reasons.
Returns
array invalid properties with reasons
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 278 of file ApiResponse.php.
Referenced by Ally\PetStore\Schema\ApiResponse\valid().
     {
         $invalidProperties = [];
         return $invalidProperties;
     }
offsetExists()
Ally\PetStore\Schema\ApiResponse::offsetExists ($offset)
Returns true if offset exists.
False otherwise.
Parameters
integer $offset Offset
Returns
boolean
Definition at line 390 of file ApiResponse.php.
                                          : bool
     {
         return isset($this->container[$offset]);
     }
offsetGet()
Ally\PetStore\Schema\ApiResponse::offsetGet ($offset)
Gets offset.
Parameters
integer $offset Offset
Returns
mixed|null
Definition at line 403 of file ApiResponse.php.
     {
         return $this->container[$offset] ?? null;
     }
offsetSet()
Ally\PetStore\Schema\ApiResponse::offsetSet ($offset, $value)
Sets value based on offset.
Parameters
int | null $offset Offset
mixed $value Value to be set
Returns
void
Definition at line 416 of file ApiResponse.php.
                                               : void
     {
         if (is_null($offset)) {
             $this->container[] = $value;
         } else {
             $this->container[$offset] = $value;
         }
     }
offsetUnset()
Ally\PetStore\Schema\ApiResponse::offsetUnset ($offset)
Unsets offset.
Parameters
integer $offset Offset
Returns
void
Definition at line 432 of file ApiResponse.php.
                                         : void
     {
         unset($this->container[$offset]);
     }
openAPIFormats()
static Ally\PetStore\Schema\ApiResponse::openAPIFormats () static
Array of property to format mappings.
Used for (de)serialization
Returns
array
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 112 of file ApiResponse.php.
     {
         return self::$openAPIFormats;
     }
openAPINullables()
static Ally\PetStore\Schema\ApiResponse::openAPINullables () static protected
Array of nullable properties.
Returns
array
Definition at line 122 of file ApiResponse.php.
                                                 : array
     {
         return self::$openAPINullables;
     }
openAPITypes()
static Ally\PetStore\Schema\ApiResponse::openAPITypes () static
Array of property to type mappings.
Used for (de)serialization
Returns
array
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 102 of file ApiResponse.php.
     {
         return self::$openAPITypes;
     }
setCode()
Ally\PetStore\Schema\ApiResponse::setCode ($code)
Sets code.
Parameters
int | null $code code
Returns
self
Definition at line 314 of file ApiResponse.php.
     {
         if (is_null($code)) {
             throw new \InvalidArgumentException('non-nullable code cannot be null');
         }
         $this->container['code'] = $code;
         return $this;
     }
setIfExists()
Ally\PetStore\Schema\ApiResponse::setIfExists (string $variableName, array $fields, $defaultValue) private
Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the $this->openAPINullablesSetToNull array.
Parameters
string $variableName
array $fields
mixed $defaultValue
Definition at line 264 of file ApiResponse.php.
Referenced by Ally\PetStore\Schema\ApiResponse\__construct().
                                                                                     : void
     {
         if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
             $this->openAPINullablesSetToNull[] = $variableName;
         }
         $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
     }
setMessage()
Ally\PetStore\Schema\ApiResponse::setMessage ($message)
Sets message.
Parameters
string | null $message message
Returns
self
Definition at line 372 of file ApiResponse.php.
     {
         if (is_null($message)) {
             throw new \InvalidArgumentException('non-nullable message cannot be null');
         }
         $this->container['message'] = $message;
         return $this;
     }
setters()
static Ally\PetStore\Schema\ApiResponse::setters () static
Array of attributes to setter functions (for deserialization of responses)
Returns
array
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 209 of file ApiResponse.php.
     {
         return self::$setters;
     }
setType()
Ally\PetStore\Schema\ApiResponse::setType ($type)
Sets type.
Parameters
string | null $type type
Returns
self
Definition at line 343 of file ApiResponse.php.
     {
         if (is_null($type)) {
             throw new \InvalidArgumentException('non-nullable type cannot be null');
         }
         $this->container['type'] = $type;
         return $this;
     }
toHeaderValue()
Ally\PetStore\Schema\ApiResponse::toHeaderValue ()
Gets a header-safe presentation of the object.
Returns
string
Definition at line 468 of file ApiResponse.php.
References Ally\PetStore\ObjectSerializer\sanitizeForSerialization().
     {
         return json_encode(ObjectSerializer::sanitizeForSerialization($this));
     }
valid()
Ally\PetStore\Schema\ApiResponse::valid ()
Validate all the properties in the model return true if all passed.
Returns
bool True if all properties are valid
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 291 of file ApiResponse.php.
References Ally\PetStore\Schema\ApiResponse\listInvalidProperties().
     {
         return count($this->listInvalidProperties()) === 0;
     }
Member Data Documentation
$attributeMap
Ally\PetStore\Schema\ApiResponse::$attributeMap static protected
Initial value:
= [
        'code' => 'code'
Definition at line 165 of file ApiResponse.php.
$container
Ally\PetStore\Schema\ApiResponse::$container = [] protected
Definition at line 240 of file ApiResponse.php.
$getters
Ally\PetStore\Schema\ApiResponse::$getters static protected
Initial value:
= [
        'code' => 'getCode'
Definition at line 187 of file ApiResponse.php.
$openAPIFormats
Ally\PetStore\Schema\ApiResponse::$openAPIFormats static protected
Initial value:
= [
        'code' => 'int32'
Definition at line 73 of file ApiResponse.php.
$openAPIModelName
Ally\PetStore\Schema\ApiResponse::$openAPIModelName = 'ApiResponse' static protected
Definition at line 53 of file ApiResponse.php.
$openAPINullables
array Ally\PetStore\Schema\ApiResponse::$openAPINullables static protected
Initial value:
= [
        'code' => false
Definition at line 84 of file ApiResponse.php.
$openAPINullablesSetToNull
array Ally\PetStore\Schema\ApiResponse::$openAPINullablesSetToNull = [] protected
Definition at line 95 of file ApiResponse.php.
Referenced by Ally\PetStore\Schema\ApiResponse\getOpenAPINullablesSetToNull().
$openAPITypes
Ally\PetStore\Schema\ApiResponse::$openAPITypes static protected
Initial value:
= [
        'code' => 'int'
Definition at line 60 of file ApiResponse.php.
$setters
Ally\PetStore\Schema\ApiResponse::$setters static protected
Initial value:
= [
        'code' => 'setCode'
Definition at line 176 of file ApiResponse.php.
DISCRIMINATOR
const Ally\PetStore\Schema\ApiResponse::DISCRIMINATOR = null
Definition at line 46 of file ApiResponse.php.
The documentation for this class was generated from the following file:
src/Schema/ApiResponse.php