---
globalProperties:
  apiDocs: false
  modelDocs: false
  apiTests: false
  modelTests: false

# The main namespace to use for all classes.
invokerPackage: Ally\PetStore
# model/dto package
modelPackage: Schema
# path to folder, probably will just be same as gitRepoId for consistency
packageName: project-sdk
srcBasePath: src/
gitUserId: alistaircol
gitRepoId: project-sdk

# for the html2 docs
phpInvokerPackage: Ally\Project
