Ally'sPetStoreAPI: Ally\PetStore\Schema\Tag Class Reference
Ally\PetStore\Schema\Tag Class Reference
Public Member Functions
isNullableSetToNull (string $property)
Checks if a nullable property is set to null.
getModelName ()
The original name of the model.
__construct (array $data=null)
Constructor.
listInvalidProperties ()
Show all the invalid properties with reasons.
valid ()
Validate all the properties in the model return true if all passed.
getId ()
Gets id.
setId ($id)
Sets id.
getName ()
Gets name.
setName ($name)
Sets name.
offsetExists ($offset)
Returns true if offset exists.
offsetGet ($offset)
Gets offset.
offsetSet ($offset, $value)
Sets value based on offset.
offsetUnset ($offset)
Unsets offset.
jsonSerialize ()
Serializes the object to a value that can be serialized natively by json_encode().
__toString ()
Gets the string presentation of the object.
toHeaderValue ()
Gets a header-safe presentation of the object.
Static Public Member Functions
static openAPITypes ()
Array of property to type mappings.
static openAPIFormats ()
Array of property to format mappings.
static isNullable (string $property)
Checks if a property is nullable.
static static attributeMap ()
Array of attributes where the key is the local name, and the value is the original name.
static setters ()
Array of attributes to setter functions (for deserialization of responses)
static getters ()
Array of attributes to getter functions (for serialization of requests)
Public Attributes
const DISCRIMINATOR = null
Static Protected Member Functions
static openAPINullables ()
Array of nullable properties.
Protected Attributes
array $openAPINullablesSetToNull = []
$container = []
Static Protected Attributes
static $openAPIModelName = 'Tag'
static $openAPITypes
static $openAPIFormats
static array $openAPINullables
static $attributeMap
static $setters
static $getters
Private Member Functions
getOpenAPINullablesSetToNull ()
Array of nullable field names deliberately set to null.
setIfExists (string $variableName, array $fields, $defaultValue)
Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the $this->openAPINullablesSetToNull array.
Detailed Description
Definition at line 44 of file Tag.php.
Constructor & Destructor Documentation
__construct()
Ally\PetStore\Schema\Tag::__construct (array $data = null)
Constructor.
Parameters
mixed[] $data Associated array of property values initializing the model
Definition at line 242 of file Tag.php.
References Ally\PetStore\Schema\Tag\setIfExists().
     {
         $this->setIfExists('id', $data ?? [], null);
         $this->setIfExists('name', $data ?? [], null);
     }
Member Function Documentation
__toString()
Ally\PetStore\Schema\Tag::__toString ()
Gets the string presentation of the object.
Returns
string
Definition at line 419 of file Tag.php.
References Ally\PetStore\ObjectSerializer\sanitizeForSerialization().
     {
         return json_encode(
             ObjectSerializer::sanitizeForSerialization($this),
             JSON_PRETTY_PRINT
         );
     }
attributeMap()
static static Ally\PetStore\Schema\Tag::attributeMap () static
Array of attributes where the key is the local name, and the value is the original name.
Returns
array
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 193 of file Tag.php.
     {
         return self::$attributeMap;
     }
getId()
Ally\PetStore\Schema\Tag::getId ()
Gets id.
Returns
int|null
Definition at line 295 of file Tag.php.
     {
         return $this->container['id'];
     }
getModelName()
Ally\PetStore\Schema\Tag::getModelName ()
The original name of the model.
Returns
string
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 223 of file Tag.php.
     {
         return self::$openAPIModelName;
     }
getName()
Ally\PetStore\Schema\Tag::getName ()
Gets name.
Returns
string|null
Definition at line 324 of file Tag.php.
     {
         return $this->container['name'];
     }
getOpenAPINullablesSetToNull()
Ally\PetStore\Schema\Tag::getOpenAPINullablesSetToNull () private
Array of nullable field names deliberately set to null.
Returns
boolean[]
Definition at line 129 of file Tag.php.
References Ally\PetStore\Schema\Tag\$openAPINullablesSetToNull.
Referenced by Ally\PetStore\Schema\Tag\isNullableSetToNull().
                                                    : array
     {
         return $this->openAPINullablesSetToNull;
     }
getters()
static Ally\PetStore\Schema\Tag::getters () static
Array of attributes to getter functions (for serialization of requests)
Returns
array
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 213 of file Tag.php.
     {
         return self::$getters;
     }
isNullable()
static Ally\PetStore\Schema\Tag::isNullable (string $property) static
Checks if a property is nullable.
Parameters
string $property
Returns
bool
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 140 of file Tag.php.
                                                        : bool
     {
         return self::openAPINullables()[$property] ?? false;
     }
isNullableSetToNull()
Ally\PetStore\Schema\Tag::isNullableSetToNull (string $property)
Checks if a nullable property is set to null.
Parameters
string $property
Returns
bool
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 151 of file Tag.php.
References Ally\PetStore\Schema\Tag\getOpenAPINullablesSetToNull().
                                                          : bool
     {
         return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
     }
jsonSerialize()
Ally\PetStore\Schema\Tag::jsonSerialize ()
Serializes the object to a value that can be serialized natively by json_encode().
mixed Returns data which can be serialized by json_encode(), which is a value of any type other than a resource.
Definition at line 409 of file Tag.php.
References Ally\PetStore\ObjectSerializer\sanitizeForSerialization().
     {
        return ObjectSerializer::sanitizeForSerialization($this);
     }
listInvalidProperties()
Ally\PetStore\Schema\Tag::listInvalidProperties ()
Show all the invalid properties with reasons.
Returns
array invalid properties with reasons
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 271 of file Tag.php.
Referenced by Ally\PetStore\Schema\Tag\valid().
     {
         $invalidProperties = [];
         return $invalidProperties;
     }
offsetExists()
Ally\PetStore\Schema\Tag::offsetExists ($offset)
Returns true if offset exists.
False otherwise.
Parameters
integer $offset Offset
Returns
boolean
Definition at line 354 of file Tag.php.
                                          : bool
     {
         return isset($this->container[$offset]);
     }
offsetGet()
Ally\PetStore\Schema\Tag::offsetGet ($offset)
Gets offset.
Parameters
integer $offset Offset
Returns
mixed|null
Definition at line 367 of file Tag.php.
     {
         return $this->container[$offset] ?? null;
     }
offsetSet()
Ally\PetStore\Schema\Tag::offsetSet ($offset, $value)
Sets value based on offset.
Parameters
int | null $offset Offset
mixed $value Value to be set
Returns
void
Definition at line 380 of file Tag.php.
                                               : void
     {
         if (is_null($offset)) {
             $this->container[] = $value;
         } else {
             $this->container[$offset] = $value;
         }
     }
offsetUnset()
Ally\PetStore\Schema\Tag::offsetUnset ($offset)
Unsets offset.
Parameters
integer $offset Offset
Returns
void
Definition at line 396 of file Tag.php.
                                         : void
     {
         unset($this->container[$offset]);
     }
openAPIFormats()
static Ally\PetStore\Schema\Tag::openAPIFormats () static
Array of property to format mappings.
Used for (de)serialization
Returns
array
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 109 of file Tag.php.
     {
         return self::$openAPIFormats;
     }
openAPINullables()
static Ally\PetStore\Schema\Tag::openAPINullables () static protected
Array of nullable properties.
Returns
array
Definition at line 119 of file Tag.php.
                                                 : array
     {
         return self::$openAPINullables;
     }
openAPITypes()
static Ally\PetStore\Schema\Tag::openAPITypes () static
Array of property to type mappings.
Used for (de)serialization
Returns
array
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 99 of file Tag.php.
     {
         return self::$openAPITypes;
     }
setId()
Ally\PetStore\Schema\Tag::setId ($id)
Sets id.
Parameters
int | null $id id
Returns
self
Definition at line 307 of file Tag.php.
     {
         if (is_null($id)) {
             throw new \InvalidArgumentException('non-nullable id cannot be null');
         }
         $this->container['id'] = $id;
         return $this;
     }
setIfExists()
Ally\PetStore\Schema\Tag::setIfExists (string $variableName, array $fields, $defaultValue) private
Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the $this->openAPINullablesSetToNull array.
Parameters
string $variableName
array $fields
mixed $defaultValue
Definition at line 257 of file Tag.php.
Referenced by Ally\PetStore\Schema\Tag\__construct().
                                                                                     : void
     {
         if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
             $this->openAPINullablesSetToNull[] = $variableName;
         }
         $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
     }
setName()
Ally\PetStore\Schema\Tag::setName ($name)
Sets name.
Parameters
string | null $name name
Returns
self
Definition at line 336 of file Tag.php.
     {
         if (is_null($name)) {
             throw new \InvalidArgumentException('non-nullable name cannot be null');
         }
         $this->container['name'] = $name;
         return $this;
     }
setters()
static Ally\PetStore\Schema\Tag::setters () static
Array of attributes to setter functions (for deserialization of responses)
Returns
array
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 203 of file Tag.php.
     {
         return self::$setters;
     }
toHeaderValue()
Ally\PetStore\Schema\Tag::toHeaderValue ()
Gets a header-safe presentation of the object.
Returns
string
Definition at line 432 of file Tag.php.
References Ally\PetStore\ObjectSerializer\sanitizeForSerialization().
     {
         return json_encode(ObjectSerializer::sanitizeForSerialization($this));
     }
valid()
Ally\PetStore\Schema\Tag::valid ()
Validate all the properties in the model return true if all passed.
Returns
bool True if all properties are valid
Implements Ally\PetStore\Schema\ModelInterface.
Definition at line 284 of file Tag.php.
References Ally\PetStore\Schema\Tag\listInvalidProperties().
     {
         return count($this->listInvalidProperties()) === 0;
     }
Member Data Documentation
$attributeMap
Ally\PetStore\Schema\Tag::$attributeMap static protected
Initial value:
= [
        'id' => 'id'
Definition at line 162 of file Tag.php.
$container
Ally\PetStore\Schema\Tag::$container = [] protected
Definition at line 234 of file Tag.php.
$getters
Ally\PetStore\Schema\Tag::$getters static protected
Initial value:
= [
        'id' => 'getId'
Definition at line 182 of file Tag.php.
$openAPIFormats
Ally\PetStore\Schema\Tag::$openAPIFormats static protected
Initial value:
= [
        'id' => 'int64'
Definition at line 72 of file Tag.php.
$openAPIModelName
Ally\PetStore\Schema\Tag::$openAPIModelName = 'Tag' static protected
Definition at line 53 of file Tag.php.
$openAPINullables
array Ally\PetStore\Schema\Tag::$openAPINullables static protected
Initial value:
= [
        'id' => false
Definition at line 82 of file Tag.php.
$openAPINullablesSetToNull
array Ally\PetStore\Schema\Tag::$openAPINullablesSetToNull = [] protected
Definition at line 92 of file Tag.php.
Referenced by Ally\PetStore\Schema\Tag\getOpenAPINullablesSetToNull().
$openAPITypes
Ally\PetStore\Schema\Tag::$openAPITypes static protected
Initial value:
= [
        'id' => 'int'
Definition at line 60 of file Tag.php.
$setters
Ally\PetStore\Schema\Tag::$setters static protected
Initial value:
= [
        'id' => 'setId'
Definition at line 172 of file Tag.php.
DISCRIMINATOR
const Ally\PetStore\Schema\Tag::DISCRIMINATOR = null
Definition at line 46 of file Tag.php.
The documentation for this class was generated from the following file:
src/Schema/Tag.php